export const questoes = [ 
  
            // --- SUB: BIOLOGIA ---
            { id: "NAT-BIO-001", cat: "Natureza", sub: "Biologia", txt: "Usina de energia da célula:", opt: ["Mitocôndria", "Núcleo", "Ribossomo", "Vacúolo"], cor: 0 },
            { id: "NAT-BIO-002", cat: "Natureza", sub: "Biologia", txt: "Vírus são seres:", opt: ["Eucariontes", "Procariontes", "Acelulares", "Vegetais"], cor: 2 },
            { id: "NAT-BIO-003", cat: "Natureza", sub: "Biologia", txt: "Base nitrogenada exclusiva do RNA:", opt: ["Timina", "Uracila", "Citosina", "Guanina"], cor: 1 },
            { id: "NAT-BIO-004", cat: "Natureza", sub: "Biologia", txt: "Relação ecológica onde ambos se beneficiam:", opt: ["Parasitismo", "Competição", "Mutualismo", "Amensalismo"], cor: 2 },
            { id: "NAT-BIO-005", cat: "Natureza", sub: "Biologia", txt: "O sangue tipo O é conhecido como:", opt: ["Receptor Universal", "Doador Universal", "Neutro", "Positivo"], cor: 1 },
            { id: "NAT-BIO-006", cat: "Natureza", sub: "Biologia", txt: "Processo que plantas usam para criar energia:", opt: ["Respiração", "Fotossíntese", "Fermentação", "Oxidação"], cor: 1 },
            { id: "NAT-BIO-007", cat: "Natureza", sub: "Biologia", txt: "A base nitrogenada que se liga à Adenina no DNA é:", opt: ["Guanina", "Citosina", "Timina", "Uracila"], cor: 2 },
            { id: "NAT-BIO-008", cat: "Natureza", sub: "Biologia", txt: "Quem propôs a Teoria da Evolução por Seleção Natural?", opt: ["Lamarck", "Darwin", "Mendel", "Pasteur"], cor: 1 },
            { id: "NAT-BIO-009", cat: "Natureza", sub: "Biologia", txt: "O Reino Fungi inclui:", opt: ["Plantas", "Bactérias", "Cogumelos e Bolores", "Algas"], cor: 2 },
            { id: "NAT-BIO-010", cat: "Natureza", sub: "Biologia", txt: "Qual célula NÃO possui núcleo definido (procarionte)?", opt: ["Animal", "Vegetal", "Bacteriana", "Fúngica"], cor: 2 },
            { id: "NAT-BIO-011", cat: "Natureza", sub: "Biologia", txt: "A insulina é produzida por qual órgão?", opt: ["Fígado", "Pâncreas", "Rim", "Estômago"], cor: 1 },
            { id: "NAT-BIO-012", cat: "Natureza", sub: "Biologia", txt: "O processo de perda de água na forma de vapor pelas plantas é:", opt: ["Respiração", "Fotossíntese", "Transpiração", "Gutação"], cor: 2 },
            { id: "NAT-BIO-013", cat: "Natureza", sub: "Biologia", txt: "Quantos pares de cromossomos tem um humano normal?", opt: ["23", "46", "22", "44"], cor: 0 },
            { id: "NAT-BIO-014", cat: "Natureza", sub: "Biologia", txt: "Qual vitamina é produzida pela exposição ao sol?", opt: ["Vitamina C", "Vitamina A", "Vitamina D", "Vitamina B12"], cor: 2 },
            { id: "NAT-BIO-015", cat: "Natureza", sub: "Biologia", txt: "Os estômatos nas folhas servem para:", opt: ["Absorver água", "Trocas gasosas", "Fotossíntese", "Sustentação"], cor: 1 },
            { id: "NAT-BIO-016", cat: "Natureza", sub: "Biologia", txt: "O vetor da Dengue, Zika e Chikungunya é o mosquito:", opt: ["Anopheles", "Culex", "Aedes aegypti", "Barbeiro"], cor: 2 },
            { id: "NAT-BIO-017", cat: "Natureza", sub: "Biologia", txt: "A mitose resulta em:", opt: ["2 células idênticas", "4 células diferentes", "1 célula gigante", "Gametas"], cor: 0 },
            { id: "NAT-BIO-018", cat: "Natureza", sub: "Biologia", txt: "A meiose ocorre na produção de:", opt: ["Células da pele", "Neurônios", "Gametas (óvulos/espermatozoides)", "Hemácias"], cor: 2 },
            { id: "NAT-BIO-019", cat: "Natureza", sub: "Biologia", txt: "Qual bioma brasileiro é conhecido como 'Savana Brasileira'?", opt: ["Amazônia", "Caatinga", "Cerrado", "Mata Atlântica"], cor: 2 },
            { id: "NAT-BIO-020", cat: "Natureza", sub: "Biologia", txt: "Animais que mantêm a temperatura corporal constante são:", opt: ["Pecilotérmicos", "Homeotérmicos", "Heterotérmicos", "Exotérmicos"], cor: 1 },
            { id: "NAT-BIO-021", cat: "Natureza", sub: "Biologia", txt: "A parede celular das plantas é feita de:", opt: ["Quitina", "Celulose", "Proteína", "Lipídio"], cor: 1 },
            { id: "NAT-BIO-022", cat: "Natureza", sub: "Biologia", txt: "O RNA mensageiro (RNAm) tem a função de:", opt: ["Transportar aminoácidos", "Levar a informação do DNA para o ribossomo", "Formar o ribossomo", "Duplicar o DNA"], cor: 1 },
            { id: "NAT-BIO-023", cat: "Natureza", sub: "Biologia", txt: "Doença causada pela falta de Vitamina C:", opt: ["Raquitismo", "Escorbuto", "Cegueira noturna", "Anemia"], cor: 1 },
            { id: "NAT-BIO-024", cat: "Natureza", sub: "Biologia", txt: "O cruzamento Aa x Aa gera qual proporção genotípica?", opt: ["1:1", "3:1", "1:2:1", "100% Aa"], cor: 2 },
            { id: "NAT-BIO-025", cat: "Natureza", sub: "Biologia", txt: "As briófitas (musgos) são plantas:", opt: ["Avasculares (sem vasos)", "Vasculares", "Com sementes", "Com flores"], cor: 0 },
            { id: "NAT-BIO-026", cat: "Natureza", sub: "Biologia", txt: "Qual estrutura permite a respiração dos peixes?", opt: ["Pulmões", "Traqueias", "Brânquias", "Pele"], cor: 2 },
            { id: "NAT-BIO-027", cat: "Natureza", sub: "Biologia", txt: "A vacina estimula a produção de:", opt: ["Antígenos", "Antibióticos", "Anticorpos", "Plaquetas"], cor: 2 },
            { id: "NAT-BIO-028", cat: "Natureza", sub: "Biologia", txt: "O soro (antiofídico, por exemplo) contém:", opt: ["O vírus vivo", "Anticorpos prontos", "Bactérias mortas", "Antígenos"], cor: 1 },
            { id: "NAT-BIO-029", cat: "Natureza", sub: "Biologia", txt: "A digestão de proteínas começa no:", opt: ["Boca", "Estômago", "Intestino", "Fígado"], cor: 1 },
            { id: "NAT-BIO-030", cat: "Natureza", sub: "Biologia", txt: "Qual organela faz a digestão intracelular?", opt: ["Lisossomo", "Ribossomo", "Retículo", "Centríolo"], cor: 0 },
            { id: "NAT-BIO-031", cat: "Natureza", sub: "Biologia", txt: "A teoria de Lamarck baseava-se na:", opt: ["Seleção Natural", "Lei do Uso e Desuso", "Mutação", "Deriva Genética"], cor: 1 },
            { id: "NAT-BIO-032", cat: "Natureza", sub: "Biologia", txt: "O HIV ataca quais células?", opt: ["Hemácias", "Neurônios", "Linfócitos T (Imunidade)", "Hepatócitos"], cor: 2 },
            { id: "NAT-BIO-033", cat: "Natureza", sub: "Biologia", txt: "O processo de eutrofização em lagos é causado por:", opt: ["Excesso de nutrientes (nitrogênio/fósforo)", "Falta de oxigênio", "Excesso de peixes", "Seca"], cor: 0 },
            { id: "NAT-BIO-034", cat: "Natureza", sub: "Biologia", txt: "Os produtores na cadeia alimentar são:", opt: ["Autótrofos", "Heterótrofos", "Decompositores", "Carnívoros"], cor: 0 },
            { id: "NAT-BIO-035", cat: "Natureza", sub: "Biologia", txt: "O xilema transporta:", opt: ["Seiva elaborada (açúcar)", "Seiva bruta (água e sais)", "Hormônios", "Oxigênio"], cor: 1 },
            { id: "NAT-BIO-036", cat: "Natureza", sub: "Biologia", txt: "O floema transporta:", opt: ["Seiva bruta", "Seiva elaborada (açúcar)", "Água apenas", "Sais minerais"], cor: 1 },
            { id: "NAT-BIO-037", cat: "Natureza", sub: "Biologia", txt: "Qual filo pertence a estrela-do-mar?", opt: ["Artrópodes", "Moluscos", "Equinodermos", "Cordados"], cor: 2 },
            { id: "NAT-BIO-038", cat: "Natureza", sub: "Biologia", txt: "A maior artéria do corpo humano é a:", opt: ["Veia Cava", "Aorta", "Carótida", "Femoral"], cor: 1 },
            { id: "NAT-BIO-039", cat: "Natureza", sub: "Biologia", txt: "Os glóbulos vermelhos transportam:", opt: ["Defesa", "Oxigênio", "Coagulação", "Hormônios"], cor: 1 },
            { id: "NAT-BIO-040", cat: "Natureza", sub: "Biologia", txt: "A bile é armazenada na:", opt: ["Vesícula Biliar", "Fígado", "Pâncreas", "Estômago"], cor: 0 },
            { id: "NAT-BIO-041", cat: "Natureza", sub: "Biologia", txt: "Qual a função dos rins?", opt: ["Bombear sangue", "Filtrar o sangue e produzir urina", "Produzir bile", "Digestionar gordura"], cor: 1 },
            { id: "NAT-BIO-041", cat: "Natureza", sub: "Biologia", txt: "O hormônio que regula o açúcar no sangue é:", opt: ["Adrenalina", "Insulina", "Testosterona", "Melatonina"], cor: 1 },
            { id: "NAT-BIO-042", cat: "Natureza", sub: "Biologia", txt: "O daltonismo é uma herança ligada ao:", opt: ["Cromossomo Y", "Cromossomo X", "Cromossomo 21", "Mitocôndria"], cor: 1 },
            { id: "NAT-BIO-043", cat: "Natureza", sub: "Biologia", txt: "A queima de combustíveis fósseis agrava o:", opt: ["Efeito Estufa", "Buraco na Camada de Ozônio", "Vulcanismo", "Tsunami"], cor: 0 },
            { id: "NAT-BIO-044", cat: "Natureza", sub: "Biologia", txt: "Qual destes é um peixe cartilaginoso?", opt: ["Sardinha", "Tubarão", "Tilápia", "Salmão"], cor: 1 },
            { id: "NAT-BIO-045", cat: "Natureza", sub: "Biologia", txt: "Os antibióticos são eficazes contra:", opt: ["Vírus", "Bactérias", "Vermes", "Fungos"], cor: 1 },
            { id: "NAT-BIO-046", cat: "Natureza", sub: "Biologia", txt: "A 'Fase Clara' da fotossíntese ocorre nos:", opt: ["Estromas", "Tilacoides", "Cristas", "Citoplasma"], cor: 1 },
            { id: "NAT-BIO-047", cat: "Natureza", sub: "Biologia", txt: "O principal gás excretado na respiração humana é:", opt: ["Oxigênio", "Nitrogênio", "Gás Carbônico (CO2)", "Metano"], cor: 2 },
            { id: "NAT-BIO-048", cat: "Natureza", sub: "Biologia", txt: "Qual o tipo de reprodução das bactérias?", opt: ["Sexuada", "Bipartição (Assexuada)", "Esporulação", "Fertilização"], cor: 1 },
            { id: "NAT-BIO-049", cat: "Natureza", sub: "Biologia", txt: "O sistema linfático auxilia na:", opt: ["Digestão", "Defesa e drenagem de líquidos", "Respiração", "Visão"], cor: 1 },
            { id: "NAT-BIO-050", cat: "Natureza", sub: "Biologia", txt: "A adrenalina é produzida pelas glândulas:", opt: ["Tireoide", "Suprarrenais", "Hipófise", "Salivares"], cor: 1 },
            { id: "NAT-BIO-051", cat: "Natureza", sub: "Biologia", txt: "O 'Crossing-over' na meiose garante:", opt: ["Variabilidade Genética", "Clonagem", "Morte celular", "Câncer"], cor: 0 },
            { id: "NAT-BIO-052", cat: "Natureza", sub: "Biologia", txt: "A doença de Chagas é transmitida pelo:", opt: ["Mosquito Aedes", "Barbeiro", "Carrapato", "Rato"], cor: 1 },
            { id: "NAT-BIO-053", cat: "Natureza", sub: "Biologia", txt: "O néfron é a unidade funcional do:", opt: ["Fígado", "Rim", "Pulmão", "Coração"], cor: 1 },
            { id: "NAT-BIO-054", cat: "Natureza", sub: "Biologia", txt: "A fermentação lática ocorre nos músculos na falta de:", opt: ["Glicose", "Oxigênio", "Proteína", "Água"], cor: 1 },
            { id: "NAT-BIO-055", cat: "Natureza", sub: "Biologia", txt: "Qual vitamina previne problemas de visão?", opt: ["A", "B", "C", "D"], cor: 0 },
            { id: "NAT-BIO-056", cat: "Natureza", sub: "Biologia", txt: "A sucessão ecológica primária começa em:", opt: ["Floresta densa", "Rocha nua", "Campo agrícola", "Lago poluído"], cor: 1 },
            { id: "NAT-BIO-057", cat: "Natureza", sub: "Biologia", txt: "O conjunto de hifas forma o:", opt: ["Micélio (Fungos)", "Caule", "Fruto", "Raiz"], cor: 0 },
            { id: "NAT-BIO-058", cat: "Natureza", sub: "Biologia", txt: "O pâncreas produz insulina e:", opt: ["Bile", "Glucagon", "Adrenalina", "Saliva"], cor: 1 },
            { id: "NAT-BIO-059", cat: "Natureza", sub: "Biologia", txt: "A parte masculina da flor chama-se:", opt: ["Gineceu", "Androceu", "Pétala", "Sépala"], cor: 1 },
            { id: "NAT-BIO-060", cat: "Natureza", sub: "Biologia", txt: "O caramujo é hospedeiro intermediário da:", opt: ["Esquistossomose", "Teníase", "Dengue", "Malária"], cor: 0 },
            { id: "NAT-BIO-061", cat: "Natureza", sub: "Biologia", txt: "Quem possui sangue tipo AB é:", opt: ["Doador Universal", "Receptor Universal", "Receptor Parcial", "Doador de Plasma"], cor: 1 },
            { id: "NAT-BIO-062", cat: "Natureza", sub: "Biologia", txt: "A estrutura do DNA é uma:", opt: ["Hélice Simples", "Dupla Hélice", "Fita Linear", "Círculo"], cor: 1 },
            { id: "NAT-BIO-063", cat: "Natureza", sub: "Biologia", txt: "Os líquens são associação entre:", opt: ["Algas e Fungos", "Fungos e Plantas", "Bactérias e Vírus", "Animais e Plantas"], cor: 0 },
            { id: "NAT-BIO-064", cat: "Natureza", sub: "Biologia", txt: "A queima de biomassa libera CO2, mas é considerada neutra porque:", opt: ["Não polui", "A planta absorveu CO2 ao crescer", "É mentira", "O CO2 volta pra terra"], cor: 1 },
            { id: "NAT-BIO-065", cat: "Natureza", sub: "Biologia", txt: "Qual doença é causada por protozoário?", opt: ["Gripe", "Malária", "Tétano", "Dengue"], cor: 1 },
            { id: "NAT-BIO-066", cat: "Natureza", sub: "Biologia", txt: "O coração humano tem quantas câmaras?", opt: ["2", "3", "4", "5"], cor: 2 },
            { id: "NAT-BIO-067", cat: "Natureza", sub: "Biologia", txt: "Artérias levam sangue:", opt: ["Do coração para o corpo", "Do corpo para o coração", "Apenas para o pulmão", "Apenas para o cérebro"], cor: 0 },
            { id: "NAT-BIO-068", cat: "Natureza", sub: "Biologia", txt: "Veias levam sangue:", opt: ["Do coração para o corpo", "Do corpo para o coração", "Do rim para o fígado", "Nenhuma"], cor: 1 },
            { id: "NAT-BIO-069", cat: "Natureza", sub: "Biologia", txt: "A digestão de gorduras ocorre principalmente no:", opt: ["Estômago", "Intestino Delgado", "Boca", "Esôfago"], cor: 1 },
            { id: "NAT-BIO-070", cat: "Natureza", sub: "Biologia", txt: "A bile tem função de:", opt: ["Digestionar proteínas", "Emulsificar gorduras (detergente)", "Produzir insulina", "Matar bactérias"], cor: 1 },
            { id: "NAT-BIO-071", cat: "Natureza", sub: "Biologia", txt: "Os Anticorpos são:", opt: ["Açúcares", "Gorduras", "Proteínas", "Vírus"], cor: 2 },
            { id: "NAT-BIO-072", cat: "Natureza", sub: "Biologia", txt: "Plantas que possuem flores e frutos são:", opt: ["Briófitas", "Pteridófitas", "Gimnospermas", "Angiospermas"], cor: 3 },
            { id: "NAT-BIO-073", cat: "Natureza", sub: "Biologia", txt: "O Pinheiro-do-Paraná (Araucária) é uma:", opt: ["Angiosperma", "Gimnosperma", "Pteridófita", "Alga"], cor: 1 },
            { id: "NAT-BIO-074", cat: "Natureza", sub: "Biologia", txt: "Qual o principal gás responsável pelo Efeito Estufa?", opt: ["O2", "N2", "CO2", "He"], cor: 2 },
            { id: "NAT-BIO-075", cat: "Natureza", sub: "Biologia", txt: "Bioacumulação de mercúrio afeta mais:", opt: ["Os produtores", "Os herbívoros", "Os predadores de topo", "As plantas"], cor: 2 },
            { id: "NAT-BIO-076", cat: "Natureza", sub: "Biologia", txt: "Células-tronco têm capacidade de:", opt: ["Se diferenciar em diversos tecidos", "Apenas morrer", "Transportar oxigênio", "Produzir veneno"], cor: 0 },
            { id: "NAT-BIO-077", cat: "Natureza", sub: "Biologia", txt: "A Leptospirose é transmitida por:", opt: ["Urina de rato", "Picada de mosquito", "Ar contaminado", "Carne crua"], cor: 0 },
            { id: "NAT-BIO-078", cat: "Natureza", sub: "Biologia", txt: "Qual organela é abundante em músculos (energia)?", opt: ["Ribossomo", "Lisossomo", "Mitocôndria", "Golgi"], cor: 2 },
            { id: "NAT-BIO-079", cat: "Natureza", sub: "Biologia", txt: "A Teoria da Abiogênese dizia que:", opt: ["Vida surge de matéria bruta", "Vida surge de vida", "Deus criou tudo", "Vida veio do espaço"], cor: 0 },
            { id: "NAT-BIO-080", cat: "Natureza", sub: "Biologia", txt: "O experimento de Pasteur (pescoço de cisne) derrubou a:", opt: ["Biogênese", "Abiogênese", "Evolução", "Genética"], cor: 1 },
            { id: "NAT-BIO-081", cat: "Natureza", sub: "Biologia", txt: "Animais invertebrados com exoesqueleto de quitina:", opt: ["Moluscos", "Anelídeos", "Artrópodes", "Peixes"], cor: 2 },
            { id: "NAT-BIO-082", cat: "Natureza", sub: "Biologia", txt: "Respiração cutânea ocorre em:", opt: ["Humanos", "Minhocas e Anfíbios", "Aves", "Peixes"], cor: 1 },
            { id: "NAT-BIO-083", cat: "Natureza", sub: "Biologia", txt: "O Diafragma é um músculo exclusivo dos:", opt: ["Mamíferos", "Répteis", "Aves", "Peixes"], cor: 0 },
            { id: "NAT-BIO-084", cat: "Natureza", sub: "Biologia", txt: "A fecundação externa é comum em:", opt: ["Humanos", "Anfíbios e Peixes", "Aves", "Répteis"], cor: 1 },
            { id: "NAT-BIO-085", cat: "Natureza", sub: "Biologia", txt: "O ornitorrinco é um mamífero que:", opt: ["Voa", "Põe ovos", "Não tem pelos", "Respira por brânquias"], cor: 1 },
            { id: "NAT-BIO-086", cat: "Natureza", sub: "Biologia", txt: "A Hemofilia é uma doença que afeta:", opt: ["A respiração", "A coagulação do sangue", "A visão", "Os ossos"], cor: 1 },
            { id: "NAT-BIO-087", cat: "Natureza", sub: "Biologia", txt: "A Síndrome de Down é causada por uma trissomia no cromossomo:", opt: ["18", "13", "21", "X"], cor: 2 },
            { id: "NAT-BIO-088", cat: "Natureza", sub: "Biologia", txt: "A técnica de PCR é usada para:", opt: ["Amplificar DNA", "Criar proteínas", "Ferver água", "Medir pH"], cor: 0 },
            { id: "NAT-BIO-089", cat: "Natureza", sub: "Biologia", txt: "Transgênicos são organismos que:", opt: ["Receberam gene de outra espécie", "Foram clonados", "Não têm DNA", "São radioativos"], cor: 0 },
            { id: "NAT-BIO-090", cat: "Natureza", sub: "Biologia", txt: "Manguezais são importantes pois funcionam como:", opt: ["Berçários de vida marinha", "Depósitos de lixo", "Fontes de água doce", "Desertos"], cor: 0 },
            { id: "NAT-BIO-091", cat: "Natureza", sub: "Biologia", txt: "A sinapse é:", opt: ["Um osso", "O contato entre neurônios", "Um músculo", "Uma glândula"], cor: 1 },
            { id: "NAT-BIO-092", cat: "Natureza", sub: "Biologia", txt: "O Cerebelo controla principalmente:", opt: ["O pensamento", "O equilíbrio e coordenação", "A digestão", "A audição"], cor: 1 },
            { id: "NAT-BIO-093", cat: "Natureza", sub: "Biologia", txt: "A 'Glândula Mestra' do corpo é a:", opt: ["Tireoide", "Hipófise (Pituitária)", "Pâncreas", "Fígado"], cor: 1 },
            { id: "NAT-BIO-094", cat: "Natureza", sub: "Biologia", txt: "A placenta é exclusiva dos:", opt: ["Aves", "Mamíferos (exceto monotremados)", "Répteis", "Anfíbios"], cor: 1 },
            { id: "NAT-BIO-095", cat: "Natureza", sub: "Biologia", txt: "O nicho ecológico refere-se ao:", opt: ["Endereço da espécie", "Papel/função da espécie no ecossistema", "Predador", "Clima"], cor: 1 },
            { id: "NAT-BIO-096", cat: "Natureza", sub: "Biologia", txt: "Comensalismo é a relação onde:", opt: ["Um ganha e o outro perde", "Um ganha e o outro não é afetado", "Os dois ganham", "Os dois perdem"], cor: 1 },
            { id: "NAT-BIO-097", cat: "Natureza", sub: "Biologia", txt: "Nomes científicos devem ser escritos em:", opt: ["Inglês", "Latim", "Português", "Grego"], cor: 1 },
            { id: "NAT-BIO-098", cat: "Natureza", sub: "Biologia", txt: "A fecundação do óvulo ocorre geralmente na:", opt: ["Trompa uterina", "Vagina", "Útero", "Ovário"], cor: 0 },
            { id: "NAT-BIO-099", cat: "Natureza", sub: "Biologia", txt: "Qual destes é um Anelídeo?", opt: ["Minhoca", "Cobra", "Lesma", "Centopeia"], cor: 0 },
            { id: "NAT-BIO-100", cat: "Natureza", sub: "Biologia", txt: "A Teoria da Endossimbiose explica a origem de:", opt: ["Mitocôndrias e Cloroplastos", "Ribossomos", "Vírus", "Bactérias"], cor: 0 },
            
       ];
