export const questoes = [
            
            // --- SUB: FÍSICA ---
            { id: "NAT-FIS-001", cat: "Natureza", sub: "Física", txt: "A unidade de Força no SI é:", opt: ["Joule", "Watt", "Newton", "Pascal"], cor: 2 },
            { id: "NAT-FIS-002", cat: "Natureza", sub: "Física", txt: "Velocidade é a razão entre:", opt: ["Distância e Tempo", "Massa e Aceleração", "Força e Área", "Energia e Tempo"], cor: 0 },
            { id: "NAT-FIS-003", cat: "Natureza", sub: "Física", txt: "Qual lei diz 'Ação e Reação'?", opt: ["1ª Lei de Newton", "2ª Lei de Newton", "3ª Lei de Newton", "Lei de Ohm"], cor: 2 },
            { id: "NAT-FIS-004", cat: "Natureza", sub: "Física", txt: "V = R.i é a fórmula de:", opt: ["Potência", "1ª Lei de Ohm", "Velocidade", "Calorimetria"], cor: 1 },
            { id: "NAT-FIS-005", cat: "Natureza", sub: "Física", txt: "A gravidade na Terra é aproximadamente:", opt: ["5 m/s²", "9,8 m/s²", "15 m/s²", "20 m/s²"], cor: 1 },
            { id: "NAT-FIS-006", cat: "Natureza", sub: "Física", txt: "Energia associada ao movimento chama-se:", opt: ["Potencial", "Cinética", "Térmica", "Elástica"], cor: 1 },
            { id: "NAT-FIS-007", cat: "Natureza", sub: "Física", txt: "A luz é uma onda:", opt: ["Mecânica", "Eletromagnética", "Sonora", "Estacionária"], cor: 1 },
            { id: "NAT-FIS-008", cat: "Natureza", sub: "Física", txt: "Qual instrumento mede corrente elétrica?", opt: ["Voltímetro", "Amperímetro", "Termômetro", "Barômetro"], cor: 1 },
            { id: "NAT-FIS-009", cat: "Natureza", sub: "Física", txt: "A temperatura de 0°C equivale a quantos Kelvin?", opt: ["0 K", "100 K", "273 K", "373 K"], cor: 2 },
            { id: "NAT-FIS-010", cat: "Natureza", sub: "Física", txt: "O som NÃO se propaga no:", opt: ["Ar", "Água", "Ferro", "Vácuo"], cor: 3 },
            { id: "NAT-FIS-011", cat: "Natureza", sub: "Física", txt: "Qual a unidade de Potência no SI?", opt: ["Joule", "Watt", "Newton", "Volt"], cor: 1 },
            { id: "NAT-FIS-012", cat: "Natureza", sub: "Física", txt: "A 3ª Lei de Newton é conhecida como:", opt: ["Inércia", "Ação e Reação", "Gravitação", "Princípio Fundamental"], cor: 1 },
            { id: "NAT-FIS-013", cat: "Natureza", sub: "Física", txt: "Na reflexão em espelho plano, a imagem é:", opt: ["Real e invertida", "Virtual e direita", "Real e direita", "Virtual e invertida"], cor: 1 },
            { id: "NAT-FIS-014", cat: "Natureza", sub: "Física", txt: "A fórmula E=mc² foi proposta por:", opt: ["Newton", "Tesla", "Einstein", "Galileu"], cor: 2 },
            { id: "NAT-FIS-015", cat: "Natureza", sub: "Física", txt: "O que mede a resistência à passagem de corrente?", opt: ["Ohm", "Volt", "Ampere", "Watt"], cor: 0 },
            { id: "NAT-FIS-016", cat: "Natureza", sub: "Física", txt: "O Movimento Retilíneo Uniforme (MRU) tem:", opt: ["Aceleração constante", "Velocidade constante", "Velocidade variável", "Aceleração variável"], cor: 1 },
            { id: "NAT-FIS-017", cat: "Natureza", sub: "Física", txt: "Aceleração da gravidade (g) puxa os corpos para:", opt: ["Cima", "O centro da Terra", "O norte", "O leste"], cor: 1 },
            { id: "NAT-FIS-018", cat: "Natureza", sub: "Física", txt: "A unidade de Energia no SI é:", opt: ["Newton", "Watt", "Joule", "Pascal"], cor: 2 },
            { id: "NAT-FIS-019", cat: "Natureza", sub: "Física", txt: "Energia Cinética depende da:", opt: ["Altura", "Massa e Velocidade", "Mola", "Temperatura"], cor: 1 },
            { id: "NAT-FIS-020", cat: "Natureza", sub: "Física", txt: "Energia Potencial Gravitacional depende da:", opt: ["Velocidade", "Altura", "Deformação", "Carga elétrica"], cor: 1 },
            { id: "NAT-FIS-021", cat: "Natureza", sub: "Física", txt: "O empuxo (Princípio de Arquimedes) atua em:", opt: ["Corpos no vácuo", "Corpos submersos em fluidos", "Corpos em queda livre", "Corpos magnéticos"], cor: 1 },
            { id: "NAT-FIS-022", cat: "Natureza", sub: "Física", txt: "A pressão atmosférica diminui com:", opt: ["O aumento da altitude", "A diminuição da altitude", "O aumento da umidade", "A noite"], cor: 0 },
            { id: "NAT-FIS-023", cat: "Natureza", sub: "Física", txt: "Calor se propaga no vácuo por:", opt: ["Condução", "Convecção", "Irradiação", "Não se propaga"], cor: 2 },
            { id: "NAT-FIS-024", cat: "Natureza", sub: "Física", txt: "A mudança de Sólido para Gasoso direto é:", opt: ["Fusão", "Ebulição", "Sublimação", "Condensação"], cor: 2 },
            { id: "NAT-FIS-025", cat: "Natureza", sub: "Física", txt: "Espelhos convexos formam imagens:", opt: ["Virtuais, direitas e menores", "Reais e invertidas", "Virtuais e maiores", "Não formam imagem"], cor: 0 },
            { id: "NAT-FIS-026", cat: "Natureza", sub: "Física", txt: "A miopia é corrigida com lentes:", opt: ["Convergentes", "Divergentes", "Cilíndricas", "Planas"], cor: 1 },
            { id: "NAT-FIS-027", cat: "Natureza", sub: "Física", txt: "A hipermetropia é corrigida com lentes:", opt: ["Convergentes", "Divergentes", "Bifocais", "Escuras"], cor: 0 },
            { id: "NAT-FIS-028", cat: "Natureza", sub: "Física", txt: "Cargas de mesmo sinal se:", opt: ["Atraem", "Repelem", "Anulam", "Fundem"], cor: 1 },
            { id: "NAT-FIS-029", cat: "Natureza", sub: "Física", txt: "A unidade de Carga Elétrica é:", opt: ["Ampere", "Coulomb", "Volt", "Ohm"], cor: 1 },
            { id: "NAT-FIS-030", cat: "Natureza", sub: "Física", txt: "A resistência de um fio aumenta se:", opt: ["Ele for mais grosso", "Ele for mais curto", "Ele for mais comprido e fino", "Ele for de ouro"], cor: 2 },
            { id: "NAT-FIS-031", cat: "Natureza", sub: "Física", txt: "Em um circuito em série, a corrente é:", opt: ["Diferente em cada resistor", "A mesma em todos", "Nula", "Infinita"], cor: 1 },
            { id: "NAT-FIS-032", cat: "Natureza", sub: "Física", txt: "Em um circuito em paralelo, a tensão (voltagem) é:", opt: ["A mesma em todos", "Dividida", "Soma das tensões", "Zero"], cor: 0 },
            { id: "NAT-FIS-033", cat: "Natureza", sub: "Física", txt: "O som é uma onda:", opt: ["Eletromagnética", "Mecânica Longitudinal", "Transversal", "De rádio"], cor: 1 },
            { id: "NAT-FIS-034", cat: "Natureza", sub: "Física", txt: "A velocidade da luz no vácuo é:", opt: ["300 m/s", "340 m/s", "300.000 km/s", "Infinita"], cor: 2 },
            { id: "NAT-FIS-035", cat: "Natureza", sub: "Física", txt: "Frequência é medida em:", opt: ["Metros", "Segundos", "Hertz", "Decibéis"], cor: 2 },
            { id: "NAT-FIS-036", cat: "Natureza", sub: "Física", txt: "O Princípio da Inércia diz que:", opt: ["Corpos tendem a manter seu estado de movimento", "Ação gera reação", "Força é massa vezes aceleração", "Tudo cai"], cor: 0 },
            { id: "NAT-FIS-037", cat: "Natureza", sub: "Física", txt: "Trabalho (W) em física é:", opt: ["Esforço mental", "Força x Deslocamento", "Força / Área", "Massa x Gravidade"], cor: 1 },
            { id: "NAT-FIS-038", cat: "Natureza", sub: "Física", txt: "Potência é a rapidez com que se realiza:", opt: ["Força", "Trabalho", "Pressão", "Distância"], cor: 1 },
            { id: "NAT-FIS-039", cat: "Natureza", sub: "Física", txt: "Ímãs têm polos:", opt: ["Positivo e Negativo", "Norte e Sul", "Cima e Baixo", "Leste e Oeste"], cor: 1 },
            { id: "NAT-FIS-040", cat: "Natureza", sub: "Física", txt: "Se quebrarmos um ímã ao meio:", opt: ["Os polos se separam", "Temos dois novos ímãs completos", "Ele perde o magnetismo", "Vira eletricidade"], cor: 1 },
            { id: "NAT-FIS-041", cat: "Natureza", sub: "Física", txt: "Qual a unidade de Frequência?", opt: ["Segundo", "Metro", "Hertz", "Newton"], cor: 2 },
            { id: "NAT-FIS-042", cat: "Natureza", sub: "Física", txt: "O período (T) é o inverso da:", opt: ["Velocidade", "Frequência", "Amplitude", "Massa"], cor: 1 },
            { id: "NAT-FIS-043", cat: "Natureza", sub: "Física", txt: "O som é uma onda mecânica, logo não se propaga no:", opt: ["Ar", "Água", "Aço", "Vácuo"], cor: 3 },
            { id: "NAT-FIS-044", cat: "Natureza", sub: "Física", txt: "A altura do som (agudo/grave) depende da:", opt: ["Amplitude", "Frequência", "Velocidade", "Timbre"], cor: 1 },
            { id: "NAT-FIS-045", cat: "Natureza", sub: "Física", txt: "A intensidade do som (forte/fraco) depende da:", opt: ["Amplitude", "Frequência", "Cor", "Fase"], cor: 0 },
            { id: "NAT-FIS-046", cat: "Natureza", sub: "Física", txt: "Efeito Doppler ocorre quando há:", opt: ["Movimento relativo entre fonte e observador", "Silêncio total", "Eco", "Refração"], cor: 0 },
            { id: "NAT-FIS-047", cat: "Natureza", sub: "Física", txt: "A luz visível com menor frequência é a:", opt: ["Violeta", "Vermelha", "Azul", "Verde"], cor: 1 },
            { id: "NAT-FIS-048", cat: "Natureza", sub: "Física", txt: "A refração ocorre quando a luz:", opt: ["Bate e volta", "Muda de meio e altera velocidade", "É absorvida", "Contorna obstáculos"], cor: 1 },
            { id: "NAT-FIS-049", cat: "Natureza", sub: "Física", txt: "Um corpo negro ideal:", opt: ["Reflete tudo", "Absorve toda radiação incidente", "É transparente", "Emite luz branca"], cor: 1 },
            { id: "NAT-FIS-050", cat: "Natureza", sub: "Física", txt: "A dilatação térmica linear depende do:", opt: ["Volume", "Comprimento inicial e variação de temperatura", "Pressão", "Tempo"], cor: 1 },
            { id: "NAT-FIS-051", cat: "Natureza", sub: "Física", txt: "No zero absoluto (0 K), as moléculas:", opt: ["Vibram muito", "Cessam a agitação térmica", "Evaporam", "Ficam líquidas"], cor: 1 },
            { id: "NAT-FIS-052", cat: "Natureza", sub: "Física", txt: "A Lei de Coulomb calcula a força entre:", opt: ["Massas", "Cargas elétricas", "Ímãs", "Planetas"], cor: 1 },
            { id: "NAT-FIS-053", cat: "Natureza", sub: "Física", txt: "O campo elétrico é medido em:", opt: ["Newton/Coulomb", "Joule", "Watt", "Tesla"], cor: 0 },
            { id: "NAT-FIS-054", cat: "Natureza", sub: "Física", txt: "Capacitores servem para:", opt: ["Gerar energia", "Armazenar carga elétrica", "Resistir à corrente", "Medir tensão"], cor: 1 },
            { id: "NAT-FIS-055", cat: "Natureza", sub: "Física", txt: "Em um chuveiro, para água mais quente, a resistência deve ser:", opt: ["Maior", "Menor (para passar mais corrente)", "Nula", "Infinita"], cor: 1 },
            { id: "NAT-FIS-056", cat: "Natureza", sub: "Física", txt: "O kWh é unidade de:", opt: ["Potência", "Energia", "Corrente", "Tensão"], cor: 1 },
            { id: "NAT-FIS-057", cat: "Natureza", sub: "Física", txt: "A indução eletromagnética gera corrente através de:", opt: ["Campo magnético variável", "Campo elétrico constante", "Atrito", "Calor"], cor: 0 },
            { id: "NAT-FIS-058", cat: "Natureza", sub: "Física", txt: "Transformadores funcionam apenas com:", opt: ["Corrente Contínua (CC)", "Corrente Alternada (CA)", "Pilhas", "Baterias"], cor: 1 },
            { id: "NAT-FIS-059", cat: "Natureza", sub: "Física", txt: "A força de atrito cinético é:", opt: ["Maior que o estático máximo", "Menor que o estático máximo", "Igual ao peso", "Nula"], cor: 1 },
            { id: "NAT-FIS-060", cat: "Natureza", sub: "Física", txt: "No Movimento Circular Uniforme, a aceleração é:", opt: ["Nula", "Centrípeta", "Tangencial", "Variável"], cor: 1 },
            { id: "NAT-FIS-061", cat: "Natureza", sub: "Física", txt: "No lançamento vertical, no ponto mais alto, a velocidade é:", opt: ["Máxima", "Mínima (Zero)", "Constante", "Infinita"], cor: 1 },
            { id: "NAT-FIS-062", cat: "Natureza", sub: "Física", txt: "A área sob o gráfico Velocidade x Tempo dá o:", opt: ["Deslocamento", "Aceleração", "Tempo", "Força"], cor: 0 },
            { id: "NAT-FIS-063", cat: "Natureza", sub: "Física", txt: "Dois corpos de massas diferentes caem no vácuo:", opt: ["O mais pesado cai antes", "O mais leve cai antes", "Caem juntos", "Não caem"], cor: 2 },
            { id: "NAT-FIS-064", cat: "Natureza", sub: "Física", txt: "A força peso depende da:", opt: ["Massa e Gravidade", "Velocidade", "Altura", "Cor"], cor: 0 },
            { id: "NAT-FIS-065", cat: "Natureza", sub: "Física", txt: "O torque (momento) faz um corpo:", opt: ["Transladar", "Girar/Rotacionar", "Esquentar", "Flutuar"], cor: 1 },
            { id: "NAT-FIS-066", cat: "Natureza", sub: "Física", txt: "Máquinas simples (alavancas) servem para:", opt: ["Multiplicar força", "Criar energia", "Diminuir trabalho", "Aumentar atrito"], cor: 0 },
            { id: "NAT-FIS-067", cat: "Natureza", sub: "Física", txt: "A Pressão é definida como:", opt: ["Força x Área", "Força / Área", "Massa / Volume", "Energia / Tempo"], cor: 1 },
            { id: "NAT-FIS-068", cat: "Natureza", sub: "Física", txt: "Princípio de Pascal é usado em:", opt: ["Freios hidráulicos", "Aviões", "Foguetes", "Lâmpadas"], cor: 0 },
            { id: "NAT-FIS-069", cat: "Natureza", sub: "Física", txt: "A temperatura mede:", opt: ["Calor total", "Agitação média das moléculas", "Volume", "Pressão"], cor: 1 },
            { id: "NAT-FIS-070", cat: "Natureza", sub: "Física", txt: "Calor específico alto significa que a substância:", opt: ["Esquenta/Esfria difícil", "Esquenta rápido", "Não esquenta", "É isolante"], cor: 0 },
            { id: "NAT-FIS-071", cat: "Natureza", sub: "Física", txt: "A água ferve a 100°C ao nível do mar. No Everest:", opt: ["Ferve acima de 100°C", "Ferve abaixo de 100°C", "Não ferve", "Congela"], cor: 1 },
            { id: "NAT-FIS-072", cat: "Natureza", sub: "Física", txt: "O arco-íris é causado pela:", opt: ["Reflexão", "Difração", "Dispersão/Refração", "Interferência"], cor: 2 },
            { id: "NAT-FIS-073", cat: "Natureza", sub: "Física", txt: "A fibra óptica funciona baseada na:", opt: ["Refração total", "Reflexão interna total", "Difração", "Absorção"], cor: 1 },
            { id: "NAT-FIS-074", cat: "Natureza", sub: "Física", txt: "Lentes de bordas finas geralmente são:", opt: ["Convergentes", "Divergentes", "Planas", "Opacas"], cor: 0 },
            { id: "NAT-FIS-075", cat: "Natureza", sub: "Física", txt: "A carga de um elétron é:", opt: ["Positiva", "Negativa", "Neutra", "Variável"], cor: 1 },
            { id: "NAT-FIS-076", cat: "Natureza", sub: "Física", txt: "Materiais que não conduzem bem eletricidade são:", opt: ["Condutores", "Isolantes/Dieletricos", "Metais", "Semicondutores"], cor: 1 },
            { id: "NAT-FIS-077", cat: "Natureza", sub: "Física", txt: "O fusível serve para:", opt: ["Aumentar a corrente", "Proteger o circuito queimando", "Resfriar", "Gerar luz"], cor: 1 },
            { id: "NAT-FIS-078", cat: "Natureza", sub: "Física", txt: "O disjuntor desarma quando:", opt: ["A corrente é muito alta", "Acaba a luz", "Chove", "A tensão cai"], cor: 0 },
            { id: "NAT-FIS-079", cat: "Natureza", sub: "Física", txt: "Geradores convertem energia mecânica em:", opt: ["Térmica", "Elétrica", "Química", "Nuclear"], cor: 1 },
            { id: "NAT-FIS-080", cat: "Natureza", sub: "Física", txt: "Motores elétricos convertem energia elétrica em:", opt: ["Mecânica", "Química", "Nuclear", "Magnética"], cor: 0 },
            { id: "NAT-FIS-081", cat: "Natureza", sub: "Física", txt: "As ondas de rádio são:", opt: ["Sonoras", "Eletromagnéticas", "Mecânicas", "De choque"], cor: 1 },
            { id: "NAT-FIS-082", cat: "Natureza", sub: "Física", txt: "Ondas sonoras NÃO sofrem:", opt: ["Reflexão", "Refração", "Polarização", "Difração"], cor: 2 },
            { id: "NAT-FIS-083", cat: "Natureza", sub: "Física", txt: "A velocidade v = λ.f relaciona:", opt: ["Comprimento e Frequência", "Massa e Aceleração", "Força e Área", "Tempo e Espaço"], cor: 0 },
            { id: "NAT-FIS-084", cat: "Natureza", sub: "Física", txt: "Ressonância ocorre quando a frequência externa iguala a:", opt: ["Frequência natural", "Amplitude", "Velocidade", "Massa"], cor: 0 },
            { id: "NAT-FIS-085", cat: "Natureza", sub: "Física", txt: "Raios X são usados para:", opt: ["Bronzear", "Ver ossos", "Ouvir rádio", "Esquentar comida"], cor: 1 },
            { id: "NAT-FIS-086", cat: "Natureza", sub: "Física", txt: "A fissão nuclear ocorre em:", opt: ["Usinas nucleares e bombas atômicas", "No Sol", "Na queima de carvão", "Na bateria"], cor: 0 },
            { id: "NAT-FIS-087", cat: "Natureza", sub: "Física", txt: "A fusão nuclear ocorre no:", opt: ["Sol e Estrelas", "Centro da Terra", "Reator de Chernobyl", "Micro-ondas"], cor: 0 },
            { id: "NAT-FIS-088", cat: "Natureza", sub: "Física", txt: "O efeito fotoelétrico prova que a luz:", opt: ["É apenas onda", "Comporta-se como partícula (fóton)", "É magnética", "Não tem energia"], cor: 1 },
            { id: "NAT-FIS-089", cat: "Natureza", sub: "Física", txt: "Princípio da Incerteza de Heisenberg diz que:", opt: ["Tudo é incerto", "Não se pode saber posição e momento do elétron com precisão simultânea", "O elétron não existe", "Deus joga dados"], cor: 1 },
            { id: "NAT-FIS-090", cat: "Natureza", sub: "Física", txt: "Curto-circuito ocorre quando:", opt: ["A resistência é zero e a corrente tende ao infinito", "A luz apaga", "O fio quebra", "A resistência é máxima"], cor: 0 },
            { id: "NAT-FIS-091", cat: "Natureza", sub: "Física", txt: "O fio terra serve para:", opt: ["Economizar luz", "Descarregar excesso de carga para o solo (segurança)", "Aumentar a voltagem", "Colorir o circuito"], cor: 1 },
            { id: "NAT-FIS-092", cat: "Natureza", sub: "Física", txt: "A Gaiola de Faraday:", opt: ["Prende pássaros", "Bloqueia campos elétricos externos", "Gera energia", "Aumenta o sinal de celular"], cor: 1 },
            { id: "NAT-FIS-093", cat: "Natureza", sub: "Física", txt: "Ferromagnetismo é a propriedade de:", opt: ["Ser atraído fortemente por ímãs", "Repelir ímãs", "Não interagir", "Conduzir calor"], cor: 0 },
            { id: "NAT-FIS-094", cat: "Natureza", sub: "Física", txt: "O Decibel (dB) mede:", opt: ["Frequência", "Nível de intensidade sonora", "Velocidade", "Comprimento de onda"], cor: 1 },
            { id: "NAT-FIS-095", cat: "Natureza", sub: "Física", txt: "Ultrassom são ondas com frequência:", opt: ["Abaixo da audição humana", "Acima da audição humana (>20kHz)", "Visíveis", "De rádio"], cor: 1 },
            { id: "NAT-FIS-096", cat: "Natureza", sub: "Física", txt: "A 2ª Lei da Termodinâmica trata da:", opt: ["Entropia (desordem) sempre aumenta", "Energia se conserva", "Zero absoluto", "Pressão"], cor: 0 },
            { id: "NAT-FIS-097", cat: "Natureza", sub: "Física", txt: "Máquinas térmicas nunca têm rendimento de:", opt: ["50%", "10%", "100%", "90%"], cor: 2 },
            { id: "NAT-FIS-098", cat: "Natureza", sub: "Física", txt: "A pressão de 1 atm equivale a aprox.:", opt: ["100 Pa", "100.000 Pa (10^5 Pa)", "10 Pa", "1 Pa"], cor: 1 },
            { id: "NAT-FIS-099", cat: "Natureza", sub: "Física", txt: "O empuxo é igual ao:", opt: ["Peso do corpo", "Peso do volume de fluido deslocado", "Volume do corpo", "Densidade"], cor: 1 },
            { id: "NAT-FIS-100", cat: "Natureza", sub: "Física", txt: "Corpo em equilíbrio estável, se deslocado:", opt: ["Volta à posição original", "Cai", "Fica onde parou", "Explode"], cor: 0 },
           
];
