export const questoes = [ 

            // --- SUB: QUÍMICA ---
            { id: "NAT-QUI-001", cat: "Natureza", sub: "Química", txt: "O pH 7 é considerado:", opt: ["Ácido", "Básico", "Neutro", "Salino"], cor: 2 },
            { id: "NAT-QUI-002", cat: "Natureza", sub: "Química", txt: "Elemento químico 'Au':", opt: ["Prata", "Ouro", "Cobre", "Alumínio"], cor: 1 },
            { id: "NAT-QUI-003", cat: "Natureza", sub: "Química", txt: "Ligação onde há compartilhamento de elétrons:", opt: ["Iônica", "Covalente", "Metálica", "Hidrogênio"], cor: 1 },
            { id: "NAT-QUI-004", cat: "Natureza", sub: "Química", txt: "Principal gás do Efeito Estufa:", opt: ["Oxigênio", "Nitrogênio", "Dióxido de Carbono", "Hélio"], cor: 2 },
            { id: "NAT-QUI-005", cat: "Natureza", sub: "Química", txt: "Mistura Água + Óleo é:", opt: ["Homogênea", "Heterogênea", "Solúvel", "Coloidal"], cor: 1 },
            { id: "NAT-QUI-006", cat: "Natureza", sub: "Química", txt: "O átomo é composto por prótons, elétrons e:", opt: ["Fótons", "Nêutrons", "Quarks", "Pósitrons"], cor: 1 },
            { id: "NAT-QUI-007", cat: "Natureza", sub: "Química", txt: "A fórmula da água oxigenada é:", opt: ["H2O", "H2O2", "HO", "O2"], cor: 1 },
            { id: "NAT-QUI-008", cat: "Natureza", sub: "Química", txt: "Tabela Periódica é organizada por ordem crescente de:", opt: ["Massa Atômica", "Número Atômico", "Raio Atômico", "Data de descoberta"], cor: 1 },
            { id: "NAT-QUI-009", cat: "Natureza", sub: "Química", txt: "Mudança do estado sólido para líquido:", opt: ["Fusão", "Vaporização", "Solidificação", "Sublimação"], cor: 0 },
            { id: "NAT-QUI-010", cat: "Natureza", sub: "Química", txt: "Qual destes é um gás nobre?", opt: ["Oxigênio", "Hélio", "Cloro", "Hidrogênio"], cor: 1 },
            { id: "NAT-QUI-011", cat: "Natureza", sub: "Química", txt: "O número de Avogadro (6,02 x 10²³) refere-se a:", opt: ["Um Mol", "Um Átomo", "Uma Molécula", "Um Grama"], cor: 0 },
            { id: "NAT-QUI-012", cat: "Natureza", sub: "Química", txt: "Substância que libera H+ em solução aquosa é um:", opt: ["Ácido", "Base", "Sal", "Óxido"], cor: 0 },
            { id: "NAT-QUI-013", cat: "Natureza", sub: "Química", txt: "A ferrugem é resultado de uma reação de:", opt: ["Combustão", "Oxidação", "Fermentação", "Fusão"], cor: 1 },
            { id: "NAT-QUI-014", cat: "Natureza", sub: "Química", txt: "Qual o elemento mais abundante no universo?", opt: ["Oxigênio", "Carbono", "Hidrogênio", "Ferro"], cor: 2 },
            { id: "NAT-QUI-015", cat: "Natureza", sub: "Química", txt: "Isótopos são átomos com mesmo número de:", opt: ["Nêutrons", "Elétrons", "Prótons", "Massa"], cor: 2 },
            { id: "NAT-QUI-016", cat: "Natureza", sub: "Química", txt: "Isóbaros são átomos com mesmo:", opt: ["Número de Prótons", "Número de Nêutrons", "Número de Massa", "Número de Elétrons"], cor: 2 },
            { id: "NAT-QUI-017", cat: "Natureza", sub: "Química", txt: "Isótonos são átomos com mesmo:", opt: ["Número de Prótons", "Número de Nêutrons", "Número de Massa", "Elétrons"], cor: 1 },
            { id: "NAT-QUI-018", cat: "Natureza", sub: "Química", txt: "A regra do octeto diz que o átomo estabiliza com:", opt: ["2 elétrons", "4 elétrons", "8 elétrons na última camada", "10 elétrons"], cor: 2 },
            { id: "NAT-QUI-019", cat: "Natureza", sub: "Química", txt: "Cátions são íons de carga:", opt: ["Positiva (perdeu elétrons)", "Negativa (ganhou elétrons)", "Neutra", "Variável"], cor: 0 },
            { id: "NAT-QUI-020", cat: "Natureza", sub: "Química", txt: "Ânions são íons de carga:", opt: ["Positiva", "Negativa (ganhou elétrons)", "Neutra", "Magnética"], cor: 1 },
            { id: "NAT-QUI-021", cat: "Natureza", sub: "Química", txt: "O elemento Carbono faz quantas ligações?", opt: ["1", "2", "3", "4"], cor: 3 },
            { id: "NAT-QUI-022", cat: "Natureza", sub: "Química", txt: "Hidrocarbonetos são formados apenas por:", opt: ["Carbono e Oxigênio", "Carbono e Hidrogênio", "Nitrogênio", "Água"], cor: 1 },
            { id: "NAT-QUI-023", cat: "Natureza", sub: "Química", txt: "O metano (CH4) é o principal componente do:", opt: ["Gás de cozinha (GLP)", "Gás Natural (GNV)", "Gasolina", "Diesel"], cor: 1 },
            { id: "NAT-QUI-024", cat: "Natureza", sub: "Química", txt: "O etanol é um:", opt: ["Álcool", "Cetona", "Ácido", "Éter"], cor: 0 },
            { id: "NAT-QUI-025", cat: "Natureza", sub: "Química", txt: "Soluto + Solvente formam uma:", opt: ["Mistura heterogênea", "Solução", "Reação nuclear", "Precipitação"], cor: 1 },
            { id: "NAT-QUI-026", cat: "Natureza", sub: "Química", txt: "O solvente universal é:", opt: ["Álcool", "Acetona", "Água", "Óleo"], cor: 2 },
            { id: "NAT-QUI-027", cat: "Natureza", sub: "Química", txt: "Reação exotérmica:", opt: ["Absorve calor (esfria)", "Libera calor (esquenta)", "Não troca calor", "Congela"], cor: 1 },
            { id: "NAT-QUI-028", cat: "Natureza", sub: "Química", txt: "Reação endotérmica:", opt: ["Absorve calor (esfria)", "Libera calor", "Explode", "Brilha"], cor: 0 },
            { id: "NAT-QUI-029", cat: "Natureza", sub: "Química", txt: "Catalisador serve para:", opt: ["Aumentar o rendimento", "Acelerar a reação", "Esquentar a reação", "Mudar o produto"], cor: 1 },
            { id: "NAT-QUI-030", cat: "Natureza", sub: "Química", txt: "A pilha converte energia:", opt: ["Química em Elétrica", "Elétrica em Química", "Térmica em Elétrica", "Mecânica em Elétrica"], cor: 0 },
            { id: "NAT-QUI-031", cat: "Natureza", sub: "Química", txt: "Na eletrólise ocorre:", opt: ["Produção de eletricidade", "Consumo de eletricidade para reação química", "Fusão nuclear", "Nada"], cor: 1 },
            { id: "NAT-QUI-032", cat: "Natureza", sub: "Química", txt: "O pH de uma base forte é próximo de:", opt: ["0", "7", "14", "5"], cor: 2 },
            { id: "NAT-QUI-033", cat: "Natureza", sub: "Química", txt: "Chuva ácida é causada principalmente por óxidos de:", opt: ["Enxofre e Nitrogênio", "Ferro", "Cálcio", "Ouro"], cor: 0 },
            { id: "NAT-QUI-034", cat: "Natureza", sub: "Química", txt: "O modelo atômico 'Pudim de Passas' é de:", opt: ["Dalton", "Thomson", "Rutherford", "Bohr"], cor: 1 },
            { id: "NAT-QUI-035", cat: "Natureza", sub: "Química", txt: "O modelo 'Sistema Solar' é de:", opt: ["Dalton", "Thomson", "Rutherford", "Bohr"], cor: 2 },
            { id: "NAT-QUI-036", cat: "Natureza", sub: "Química", txt: "Separação de petróleo é feita por:", opt: ["Filtração", "Decantação", "Destilação Fracionada", "Centrifugação"], cor: 2 },
            { id: "NAT-QUI-037", cat: "Natureza", sub: "Química", txt: "Tratamento da água: a floculação usa:", opt: ["Sulfato de Alumínio", "Cloro", "Flúor", "Areia"], cor: 0 },
            { id: "NAT-QUI-038", cat: "Natureza", sub: "Química", txt: "Radioatividade: Partícula Alfa é igual a:", opt: ["Um elétron", "Um núcleo de Hélio", "Um raio X", "Um nêutron"], cor: 1 },
            { id: "NAT-QUI-039", cat: "Natureza", sub: "Química", txt: "Meia-vida é o tempo para:", opt: ["A amostra desaparecer", "A amostra reduzir à metade", "A radiação acabar", "A amostra dobrar"], cor: 1 },
            { id: "NAT-QUI-040", cat: "Natureza", sub: "Química", txt: "Qual metal é líquido a temperatura ambiente?", opt: ["Ferro", "Ouro", "Mercúrio", "Cobre"], cor: 2 },
            { id: "NAT-QUI-041", cat: "Natureza", sub: "Química", txt: "A massa molar da água (H2O) é aprox.: (H=1, O=16)", opt: ["16 g/mol", "17 g/mol", "18 g/mol", "20 g/mol"], cor: 2 },
            { id: "NAT-QUI-042", cat: "Natureza", sub: "Química", txt: "CNTP refere-se a:", opt: ["Condições Normais de Temperatura e Pressão", "Controle Nacional", "Carbono Neutro", "Carga Nuclear"], cor: 0 },
            { id: "NAT-QUI-043", cat: "Natureza", sub: "Química", txt: "Volume molar de um gás nas CNTP é:", opt: ["10 L", "22,4 L", "100 L", "1 L"], cor: 1 },
            { id: "NAT-QUI-044", cat: "Natureza", sub: "Química", txt: "Lei de Lavoisier diz que:", opt: ["A massa se perde", "Na natureza nada se cria, tudo se transforma", "Átomos são indivisíveis", "Energia é massa"], cor: 1 },
            { id: "NAT-QUI-045", cat: "Natureza", sub: "Química", txt: "Balancear uma equação química é igualar:", opt: ["O número de átomos nos reagentes e produtos", "O volume", "A cor", "A temperatura"], cor: 0 },
            { id: "NAT-QUI-046", cat: "Natureza", sub: "Química", txt: "Função orgânica com oxigênio ligado a dois carbonos (C-O-C):", opt: ["Álcool", "Éter", "Éster", "Cetona"], cor: 1 },
            { id: "NAT-QUI-047", cat: "Natureza", sub: "Química", txt: "O vinagre contém qual ácido?", opt: ["Clorídrico", "Sulfúrico", "Acético (Etanoico)", "Cítrico"], cor: 2 },
            { id: "NAT-QUI-048", cat: "Natureza", sub: "Química", txt: "O grupo funcional da cetona (ex: acetona) é:", opt: ["Hidroxila (-OH)", "Carbonila (C=O) entre carbonos", "Carboxila", "Amino"], cor: 1 },
            { id: "NAT-QUI-049", cat: "Natureza", sub: "Química", txt: "Polímeros são macromoléculas formadas por:", opt: ["Monômeros", "Átomos isolados", "Sais", "Gases"], cor: 0 },
            { id: "NAT-QUI-050", cat: "Natureza", sub: "Química", txt: "O plástico PET é um exemplo de:", opt: ["Metal", "Polímero", "Cerâmica", "Gás nobre"], cor: 1 },
            { id: "NAT-QUI-051", cat: "Natureza", sub: "Química", txt: "Saponificação é a reação que produz:", opt: ["Sabão", "Plástico", "Combustível", "Medicamento"], cor: 0 },
            { id: "NAT-QUI-052", cat: "Natureza", sub: "Química", txt: "A chuva ácida corrói mármore (CaCO3) liberando:", opt: ["O2", "CO2", "N2", "H2"], cor: 1 },
            { id: "NAT-QUI-053", cat: "Natureza", sub: "Química", txt: "O aumento da temperatura geralmente ___ a velocidade da reação.", opt: ["Diminui", "Não altera", "Aumenta", "Para"], cor: 2 },
            { id: "NAT-QUI-054", cat: "Natureza", sub: "Química", txt: "Enzimas atuam como:", opt: ["Reagentes", "Produtos", "Catalisadores biológicos", "Inibidores"], cor: 2 },
            { id: "NAT-QUI-055", cat: "Natureza", sub: "Química", txt: "A concentração molar (Molaridade) é:", opt: ["g/L", "mol/L", "L/mol", "%"], cor: 1 },
            { id: "NAT-QUI-056", cat: "Natureza", sub: "Química", txt: "Diluir uma solução significa:", opt: ["Adicionar mais soluto", "Adicionar mais solvente (água)", "Evaporar a água", "Esquentar"], cor: 1 },
            { id: "NAT-QUI-057", cat: "Natureza", sub: "Química", txt: "Qual destes é um ácido forte?", opt: ["Limão", "Vinagre", "H2SO4 (Sulfúrico)", "Água"], cor: 2 },
            { id: "NAT-QUI-058", cat: "Natureza", sub: "Química", txt: "Fenolftaleína em meio básico fica:", opt: ["Incolor", "Rosa/Vermelha", "Azul", "Verde"], cor: 1 },
            { id: "NAT-QUI-059", cat: "Natureza", sub: "Química", txt: "Oxidação é a ___ de elétrons.", opt: ["Perda", "Ganho", "Manutenção", "Criação"], cor: 0 },
            { id: "NAT-QUI-060", cat: "Natureza", sub: "Química", txt: "Redução é o ___ de elétrons.", opt: ["Perda", "Ganho", "Descarte", "Roubo"], cor: 1 },
            { id: "NAT-QUI-061", cat: "Natureza", sub: "Química", txt: "O NOX do Oxigênio na maioria dos compostos é:", opt: ["-1", "-2", "+1", "+2"], cor: 1 },
            { id: "NAT-QUI-062", cat: "Natureza", sub: "Química", txt: "Eletronegatividade é a tendência de:", opt: ["Doar elétrons", "Atrair elétrons", "Perder massa", "Emitir luz"], cor: 1 },
            { id: "NAT-QUI-063", cat: "Natureza", sub: "Química", txt: "O elemento mais eletronegativo é o:", opt: ["Flúor", "Frâncio", "Oxigênio", "Hidrogênio"], cor: 0 },
            { id: "NAT-QUI-064", cat: "Natureza", sub: "Química", txt: "Ligação entre Metal e Ametal geralmente é:", opt: ["Iônica", "Covalente", "Metálica", "Hidrogênio"], cor: 0 },
            { id: "NAT-QUI-065", cat: "Natureza", sub: "Química", txt: "Ligação entre Ametal e Ametal geralmente é:", opt: ["Iônica", "Covalente", "Metálica", "Magnética"], cor: 1 },
            { id: "NAT-QUI-066", cat: "Natureza", sub: "Química", txt: "O que é Alotropia?", opt: ["Mesmo elemento formando substâncias simples diferentes", "Elementos diferentes formando a mesma substância", "Isótopos", "Isóbaros"], cor: 0 },
            { id: "NAT-QUI-067", cat: "Natureza", sub: "Química", txt: "Diamante e Grafite são alótropos do:", opt: ["Oxigênio", "Carbono", "Enxofre", "Fósforo"], cor: 1 },
            { id: "NAT-QUI-068", cat: "Natureza", sub: "Química", txt: "Qual gás é liberado na reação de bicarbonato com vinagre?", opt: ["O2", "H2", "CO2", "N2"], cor: 2 },
            { id: "NAT-QUI-069", cat: "Natureza", sub: "Química", txt: "O formol pertence à função:", opt: ["Álcool", "Aldeído", "Cetona", "Ácido"], cor: 1 },
            { id: "NAT-QUI-070", cat: "Natureza", sub: "Química", txt: "Amina caracteriza-se pela presença de:", opt: ["Nitrogênio", "Enxofre", "Fósforo", "Cloro"], cor: 0 },
            { id: "NAT-QUI-071", cat: "Natureza", sub: "Química", txt: "O cheiro de peixe podre vem de uma:", opt: ["Cetona", "Amina", "Álcool", "Éster"], cor: 1 },
            { id: "NAT-QUI-072", cat: "Natureza", sub: "Química", txt: "Ésteres são usados como:", opt: ["Aromatizantes/Flavorizantes", "Combustíveis nucleares", "Metais", "Bases fortes"], cor: 0 },
            { id: "NAT-QUI-073", cat: "Natureza", sub: "Química", txt: "Reação de Esterificação: Ácido + Álcool = ?", opt: ["Éter + Água", "Éster + Água", "Sal + Água", "Aldeído"], cor: 1 },
            { id: "NAT-QUI-074", cat: "Natureza", sub: "Química", txt: "O Biodiesel é obtido por:", opt: ["Destilação", "Transesterificação", "Fermentação", "Eletrólise"], cor: 1 },
            { id: "NAT-QUI-075", cat: "Natureza", sub: "Química", txt: "Soluções tampão servem para:", opt: ["Manter o pH constante", "Mudar o pH drasticamente", "Colorir a solução", "Esquentar"], cor: 0 },
            { id: "NAT-QUI-076", cat: "Natureza", sub: "Química", txt: "Coloides são misturas que parecem homogêneas mas são:", opt: ["Heterogêneas", "Puras", "Elementos", "Gases"], cor: 0 },
            { id: "NAT-QUI-077", cat: "Natureza", sub: "Química", txt: "O efeito Tyndall ocorre em:", opt: ["Soluções verdadeiras", "Coloides (espalhamento de luz)", "Metais", "Vácuo"], cor: 1 },
            { id: "NAT-QUI-078", cat: "Natureza", sub: "Química", txt: "Leite e Maionese são exemplos de:", opt: ["Soluções", "Coloides (Emulsões)", "Substâncias puras", "Elementos"], cor: 1 },
            { id: "NAT-QUI-079", cat: "Natureza", sub: "Química", txt: "A Tensão Superficial permite que:", opt: ["Insetos andem na água", "O gelo afunde", "A água ferva a 0°C", "O óleo se misture"], cor: 0 },
            { id: "NAT-QUI-080", cat: "Natureza", sub: "Química", txt: "A destilação fracionada separa líquidos com:", opt: ["Pontos de ebulição diferentes", "Cores diferentes", "Densidades iguais", "Massas iguais"], cor: 0 },
            { id: "NAT-QUI-081", cat: "Natureza", sub: "Química", txt: "Decantação separa:", opt: ["Sólido dissolvido", "Líquidos imiscíveis ou Sólido-Líquido (sedimentação)", "Gases", "Álcool e Água"], cor: 1 },
            { id: "NAT-QUI-082", cat: "Natureza", sub: "Química", txt: "Filtração não separa:", opt: ["Sólido de Líquido", "Areia de Água", "Sal dissolvido na água", "Pó de café"], cor: 2 },
            { id: "NAT-QUI-083", cat: "Natureza", sub: "Química", txt: "O modelo de Bohr introduziu:", opt: ["Núcleo", "Níveis de energia (camadas)", "Elétron", "Nêutron"], cor: 1 },
            { id: "NAT-QUI-084", cat: "Natureza", sub: "Química", txt: "Sal de cozinha é:", opt: ["NaCl", "NaOH", "HCl", "Na2SO4"], cor: 0 },
            { id: "NAT-QUI-085", cat: "Natureza", sub: "Química", txt: "Soda cáustica é:", opt: ["NaCl", "NaOH (Hidróxido de Sódio)", "HCl", "H2O"], cor: 1 },
            { id: "NAT-QUI-086", cat: "Natureza", sub: "Química", txt: "Isômeros são compostos com:", opt: ["Mesma fórmula molecular, estruturas diferentes", "Átomos diferentes", "Massas diferentes", "Cores iguais"], cor: 0 },
            { id: "NAT-QUI-087", cat: "Natureza", sub: "Química", txt: "Carbono Quiral (assimétrico) está ligado a:", opt: ["4 grupos diferentes", "2 oxigênios", "3 hidrogênios", "Nada"], cor: 0 },
            { id: "NAT-QUI-088", cat: "Natureza", sub: "Química", txt: "O Teflon é um polímero antiaderente feito de:", opt: ["Flúor e Carbono", "Ferro", "Madeira", "Cloro"], cor: 0 },
            { id: "NAT-QUI-089", cat: "Natureza", sub: "Química", txt: "Água dura contém excesso de íons:", opt: ["Cálcio e Magnésio", "Sódio e Potássio", "Ferro e Ouro", "Cloro e Flúor"], cor: 0 },
            { id: "NAT-QUI-090", cat: "Natureza", sub: "Química", txt: "O Gás Metano (CH4) é produzido na:", opt: ["Decomposição de lixo/digestão de gado", "Respiração humana", "Fotossíntese", "Evaporação"], cor: 0 },
            { id: "NAT-QUI-091", cat: "Natureza", sub: "Química", txt: "Petróleo é uma mistura de:", opt: ["Hidrocarbonetos", "Álcoois", "Sais", "Metais"], cor: 0 },
            { id: "NAT-QUI-092", cat: "Natureza", sub: "Química", txt: "Craqueamento do petróleo serve para:", opt: ["Quebrar moléculas grandes em menores (gasolina)", "Juntar moléculas", "Limpar o óleo", "Solidificar"], cor: 0 },
            { id: "NAT-QUI-093", cat: "Natureza", sub: "Química", txt: "A obtenção de Alumínio é feita por:", opt: ["Eletrólise da Bauxita", "Destilação", "Filtração", "Decantação"], cor: 0 },
            { id: "NAT-QUI-094", cat: "Natureza", sub: "Química", txt: "Galvanização protege o ferro usando:", opt: ["Zinco", "Cobre", "Plástico", "Água"], cor: 0 },
            { id: "NAT-QUI-095", cat: "Natureza", sub: "Química", txt: "O Bronze é uma liga de:", opt: ["Cobre e Estanho", "Ferro e Carbono", "Ouro e Prata", "Mercúrio e Zinco"], cor: 0 },
            { id: "NAT-QUI-096", cat: "Natureza", sub: "Química", txt: "O Aço é uma liga de:", opt: ["Ferro e Carbono", "Cobre e Zinco", "Alumínio e Magnésio", "Prata e Ouro"], cor: 0 },
            { id: "NAT-QUI-097", cat: "Natureza", sub: "Química", txt: "Ozonólise é uma reação que quebra:", opt: ["Duplas ligações com Ozônio", "Ligações simples", "Núcleos", "Vidros"], cor: 0 },
            { id: "NAT-QUI-098", cat: "Natureza", sub: "Química", txt: "Princípio de Le Chatelier trata do:", opt: ["Deslocamento de equilíbrio químico", "Movimento dos gases", "Átomo", "Elétron"], cor: 0 },
            { id: "NAT-QUI-099", cat: "Natureza", sub: "Química", txt: "Energia de Ativação é a energia:", opt: ["Mínima para iniciar a reação", "Liberada no final", "Absorvida", "Nuclear"], cor: 0 },
            { id: "NAT-QUI-100", cat: "Natureza", sub: "Química", txt: "A Lei de Hess diz que a variação de entalpia depende:", opt: ["Apenas dos estados inicial e final", "Do caminho percorrido", "Do tempo", "Da temperatura"], cor: 0 },
          
  ];
