export const questoes = [ 
 
            // --- SUB: FILOSOFIA ---
            { id: "HUM-FIL-001", cat: "Humanas", sub: "Filosofia", txt: "Autor de 'O Príncipe':", opt: ["Maquiavel", "Hobbes", "Rousseau", "Kant"], cor: 0 },
            { id: "HUM-FIL-002", cat: "Humanas", sub: "Filosofia", txt: "'Penso, logo existo' é de:", opt: ["Sócrates", "Descartes", "Nietzsche", "Platão"], cor: 1 },
            { id: "HUM-FIL-003", cat: "Humanas", sub: "Filosofia", txt: "A frase 'Só sei que nada sei' é atribuída a:", opt: ["Aristóteles", "Sócrates", "Platão", "Kant"], cor: 1 },
            { id: "HUM-FIL-004", cat: "Humanas", sub: "Filosofia", txt: "Corrente filosófica que valoriza a razão:", opt: ["Empirismo", "Racionalismo", "Ceticismo", "Hedonismo"], cor: 1 },
            { id: "HUM-FIL-005", cat: "Humanas", sub: "Filosofia", txt: "O Mito da Caverna de Platão discute:", opt: ["A realidade vs. aparência", "A origem do universo", "A política ateniense", "A arte da guerra"], cor: 0 },
            { id: "HUM-FIL-006", cat: "Humanas", sub: "Filosofia", txt: "Aristóteles foi aluno de:", opt: ["Sócrates", "Platão", "Alexandre, o Grande", "Heráclito"], cor: 1 },
            { id: "HUM-FIL-007", cat: "Humanas", sub: "Filosofia", txt: "A Ética estuda:", opt: ["O movimento dos astros", "O comportamento moral", "A estrutura da matéria", "A história antiga"], cor: 1 },
            { id: "HUM-FIL-008", cat: "Humanas", sub: "Filosofia", txt: "Nietzsche é famoso pela frase:", opt: ["Deus está morto", "Penso, logo existo", "O homem é o lobo do homem", "Conhece-te a ti mesmo"], cor: 0 },
            { id: "HUM-FIL-009", cat: "Humanas", sub: "Filosofia", txt: "O Empirismo defende que o conhecimento vem da:", opt: ["Razão pura", "Experiência sensorial", "Fé divina", "Imaginação"], cor: 1 },
            { id: "HUM-FIL-010", cat: "Humanas", sub: "Filosofia", txt: "Para Kant, o Imperativo Categórico é:", opt: ["Uma lei moral universal", "Uma sugestão", "Uma lei religiosa", "Uma regra política"], cor: 0 },
            { id: "HUM-FIL-011", cat: "Humanas", sub: "Filosofia", txt: "A busca pela felicidade (Eudaimonia) é central em:", opt: ["Aristóteles", "Marx", "Freud", "Maquiavel"], cor: 0 },
            { id: "HUM-FIL-012", cat: "Humanas", sub: "Filosofia", txt: "Jean-Paul Sartre foi um filósofo do:", opt: ["Existencialismo", "Estoicismo", "Epicurismo", "Idealismo"], cor: 0 },
            { id: "HUM-FIL-013", cat: "Humanas", sub: "Filosofia", txt: "Thomas Hobbes escreveu qual obra política?", opt: ["O Leviatã", "A República", "O Contrato Social", "A Política"], cor: 0 },
            { id: "HUM-FIL-014", cat: "Humanas", sub: "Filosofia", txt: "Rousseau acreditava que o homem nasce:", opt: ["Mau e a sociedade o educa", "Bom e a sociedade o corrompe", "Neutro", "Pecador"], cor: 1 },
            { id: "HUM-FIL-015", cat: "Humanas", sub: "Filosofia", txt: "A Maiêutica socrática é a arte de:", opt: ["Pintar quadros", "Parir ideias (dar à luz o conhecimento)", "Governar cidades", "Escrever livros"], cor: 1 },
            { id: "HUM-FIL-016", cat: "Humanas", sub: "Filosofia", txt: "O Estoicismo prega:", opt: ["Busca desenfreada pelo prazer", "Controle das emoções e aceitação do destino", "Negação de Deus", "Revolução armada"], cor: 1 },
            { id: "HUM-FIL-017", cat: "Humanas", sub: "Filosofia", txt: "Foucault estudou as relações de:", opt: ["Poder e saber", "Amor e ódio", "Dinheiro e mercado", "Deus e diabo"], cor: 0 },
            { id: "HUM-FIL-018", cat: "Humanas", sub: "Filosofia", txt: "São Tomás de Aquino tentou unir:", opt: ["Fé cristã e Razão aristotélica", "Budismo e Cristianismo", "Ciência e Magia", "Política e Religião"], cor: 0 },
            { id: "HUM-FIL-019", cat: "Humanas", sub: "Filosofia", txt: "A Dialética é um método associado a:", opt: ["Hegel e Marx", "Newton e Einstein", "Da Vinci", "Homero"], cor: 0 },
            { id: "HUM-FIL-020", cat: "Humanas", sub: "Filosofia", txt: "A Lógica estuda:", opt: ["As emoções", "A estrutura do raciocínio válido", "A história da arte", "A moral"], cor: 1 },
            { id: "HUM-FIL-021", cat: "Humanas", sub: "Filosofia", txt: "O Utilitarismo busca:", opt: ["O maior bem para o maior número de pessoas", "O lucro máximo", "A obediência cega", "A tradição"], cor: 0 },
            { id: "HUM-FIL-022", cat: "Humanas", sub: "Filosofia", txt: "Tales de Mileto dizia que o princípio de tudo era:", opt: ["A Água", "O Fogo", "O Ar", "O Átomo"], cor: 0 },
            { id: "HUM-FIL-023", cat: "Humanas", sub: "Filosofia", txt: "Heráclito afirmava que:", opt: ["Tudo flui (panta rhei)", "Nada muda", "O ser é imutável", "Tudo é número"], cor: 0 },
            { id: "HUM-FIL-024", cat: "Humanas", sub: "Filosofia", txt: "Para Platão, o mundo sensível é:", opt: ["Uma cópia imperfeita do mundo das ideias", "A única realidade", "A verdade", "O paraíso"], cor: 0 },
            { id: "HUM-FIL-025", cat: "Humanas", sub: "Filosofia", txt: "Aristóteles definiu o homem como:", opt: ["Animal Político", "Lobo do homem", "Sombra de Deus", "Máquina"], cor: 0 },
            { id: "HUM-FIL-026", cat: "Humanas", sub: "Filosofia", txt: "Santo Agostinho adaptou a filosofia de:", opt: ["Platão", "Aristóteles", "Epicuro", "Marx"], cor: 0 },
            { id: "HUM-FIL-027", cat: "Humanas", sub: "Filosofia", txt: "A 'Navalha de Ockham' sugere:", opt: ["A explicação mais simples costuma ser a correta", "Cortar o mal pela raiz", "A dúvida metódica", "A fé cega"], cor: 0 },
            { id: "HUM-FIL-028", cat: "Humanas", sub: "Filosofia", txt: "Maquiavel escreveu 'O Príncipe' para:", opt: ["Ensinar como manter o poder", "Criar uma democracia", "Defender a igreja", "Libertar o povo"], cor: 0 },
            { id: "HUM-FIL-029", cat: "Humanas", sub: "Filosofia", txt: "Descartes é o pai do:", opt: ["Racionalismo Moderno", "Empirismo", "Existencialismo", "Marxismo"], cor: 0 },
            { id: "HUM-FIL-030", cat: "Humanas", sub: "Filosofia", txt: "Kant propôs a 'Maioridade' como:", opt: ["Sair da tutela de outros e pensar por si", "Fazer 18 anos", "Obedecer ao rei", "Ir para a guerra"], cor: 0 },
            { id: "HUM-FIL-031", cat: "Humanas", sub: "Filosofia", txt: "Hegel via a história como um processo:", opt: ["Dialético (Tese, Antítese, Síntese)", "Linear", "Estático", "Divino"], cor: 0 },
            { id: "HUM-FIL-032", cat: "Humanas", sub: "Filosofia", txt: "Schopenhauer dizia que o mundo é:", opt: ["Vontade e Representação", "Belo e Justo", "Racional", "Matemático"], cor: 0 },
            { id: "HUM-FIL-033", cat: "Humanas", sub: "Filosofia", txt: "Para Marx, o motor da história é a:", opt: ["Luta de Classes", "Vontade de Deus", "Evolução das espécies", "Ideia absoluta"], cor: 0 },
            { id: "HUM-FIL-034", cat: "Humanas", sub: "Filosofia", txt: "O 'Super-Homem' (Übermensch) de Nietzsche é:", opt: ["Quem cria seus próprios valores", "Um herói de HQ", "Um deus", "Um tirano"], cor: 0 },
            { id: "HUM-FIL-035", cat: "Humanas", sub: "Filosofia", txt: "Sartre dizia que 'A existência precede a...':", opt: ["Essência", "Vida", "Morte", "Consciência"], cor: 0 },
            { id: "HUM-FIL-036", cat: "Humanas", sub: "Filosofia", txt: "A Escola de Frankfurt criticava a:", opt: ["Indústria Cultural", "Arte Clássica", "Religião", "Filosofia Grega"], cor: 0 },
            { id: "HUM-FIL-037", cat: "Humanas", sub: "Filosofia", txt: "Hannah Arendt criou o conceito de:", opt: ["Banalidade do Mal", "Fim da História", "Amor Líquido", "Vontade de Potência"], cor: 0 },
            { id: "HUM-FIL-038", cat: "Humanas", sub: "Filosofia", txt: "A Bioética estuda:", opt: ["Questões éticas sobre a vida/ciência", "A vida dos animais", "Biologia marinha", "História da medicina"], cor: 0 },
            { id: "HUM-FIL-039", cat: "Humanas", sub: "Filosofia", txt: "O que é Epistemologia?", opt: ["Teoria do Conhecimento", "Estudo de Deus", "Estudo da moral", "Estudo da arte"], cor: 0 },
            { id: "HUM-FIL-040", cat: "Humanas", sub: "Filosofia", txt: "O mito de Sísifo (Camus) fala sobre:", opt: ["O absurdo da vida", "A força física", "A esperança", "A justiça divina"], cor: 0 },
            { id: "HUM-FIL-041", cat: "Humanas", sub: "Filosofia", txt: "Os Pré-Socráticos buscavam a:", opt: ["Arché (princípio da natureza)", "Política", "Moral", "Arte"], cor: 0 },
            { id: "HUM-FIL-042", cat: "Humanas", sub: "Filosofia", txt: "Os Sofistas eram mestres da:", opt: ["Retórica e persuasão", "Verdade absoluta", "Matemática", "Medicina"], cor: 0 },
            { id: "HUM-FIL-043", cat: "Humanas", sub: "Filosofia", txt: "Epicuro defendia que a felicidade vem do:", opt: ["Prazer moderado e ausência de dor", "Sofrimento", "Poder", "Dinheiro"], cor: 0 },
            { id: "HUM-FIL-044", cat: "Humanas", sub: "Filosofia", txt: "Diógenes, o Cínico, vivia em:", opt: ["Um barril", "Um palácio", "Uma escola", "Uma caverna"], cor: 0 },
            { id: "HUM-FIL-045", cat: "Humanas", sub: "Filosofia", txt: "A Escolástica tentou unir:", opt: ["Fé cristã e razão grega", "Ciência e Magia", "Ateísmo e Fé", "Política e Arte"], cor: 0 },
            { id: "HUM-FIL-046", cat: "Humanas", sub: "Filosofia", txt: "A frase 'Os fins justificam os meios' é associada a:", opt: ["Maquiavel", "Jesus", "Kant", "Platão"], cor: 0 },
            { id: "HUM-FIL-047", cat: "Humanas", sub: "Filosofia", txt: "Francis Bacon propôs o método:", opt: ["Indutivo (experiência)", "Dedutivo", "Místico", "Poético"], cor: 0 },
            { id: "HUM-FIL-048", cat: "Humanas", sub: "Filosofia", txt: "John Locke dizia que a mente é uma:", opt: ["Tábula Rasa (folha em branco)", "Caixa cheia", "Máquina", "Prisão"], cor: 0 },
            { id: "HUM-FIL-049", cat: "Humanas", sub: "Filosofia", txt: "David Hume criticava a ideia de:", opt: ["Causalidade necessária", "Experiência", "Sentidos", "Prazer"], cor: 0 },
            { id: "HUM-FIL-050", cat: "Humanas", sub: "Filosofia", txt: "O Iluminismo é chamado de:", opt: ["Século das Luzes", "Idade das Trevas", "Era da Fé", "Renascimento"], cor: 0 },
            { id: "HUM-FIL-051", cat: "Humanas", sub: "Filosofia", txt: "Montesquieu propôs a:", opt: ["Separação dos Três Poderes", "Monarquia Absoluta", "Anarquia", "Ditadura"], cor: 0 },
            { id: "HUM-FIL-052", cat: "Humanas", sub: "Filosofia", txt: "Voltaire defendia a:", opt: ["Liberdade de expressão", "Censura", "Igreja Católica", "Escravidão"], cor: 0 },
            { id: "HUM-FIL-053", cat: "Humanas", sub: "Filosofia", txt: "O lema 'Ordem e Progresso' vem do:", opt: ["Positivismo (Comte)", "Marxismo", "Niilismo", "Liberalismo"], cor: 0 },
            { id: "HUM-FIL-054", cat: "Humanas", sub: "Filosofia", txt: "A Fenomenologia estuda:", opt: ["Como as coisas aparecem à consciência", "Os fenômenos naturais", "Fantasmas", "O cérebro físico"], cor: 0 },
            { id: "HUM-FIL-055", cat: "Humanas", sub: "Filosofia", txt: "A Escola de Frankfurt criou a:", opt: ["Teoria Crítica", "Teoria do Caos", "Teoria da Relatividade", "Teoria das Cores"], cor: 0 },
            { id: "HUM-FIL-056", cat: "Humanas", sub: "Filosofia", txt: "Adorno e Horkheimer criticaram a:", opt: ["Indústria Cultural", "Arte Erudita", "Educação", "Filosofia Antiga"], cor: 0 },
            { id: "HUM-FIL-057", cat: "Humanas", sub: "Filosofia", txt: "Jürgen Habermas foca na:", opt: ["Ação Comunicativa", "Ação Violenta", "Ação Divina", "Ação Econômica"], cor: 0 },
            { id: "HUM-FIL-058", cat: "Humanas", sub: "Filosofia", txt: "Hannah Arendt estudou as origens do:", opt: ["Totalitarismo", "Capitalismo", "Liberalismo", "Feudalismo"], cor: 0 },
            { id: "HUM-FIL-059", cat: "Humanas", sub: "Filosofia", txt: "Simone de Beauvoir escreveu:", opt: ["O Segundo Sexo", "O Capital", "A República", "Ética"], cor: 0 },
            { id: "HUM-FIL-060", cat: "Humanas", sub: "Filosofia", txt: "Zygmunt Bauman fala sobre o:", opt: ["Amor Líquido", "Amor Sólido", "Amor Eterno", "Ódio"], cor: 0 },
            { id: "HUM-FIL-061", cat: "Humanas", sub: "Filosofia", txt: "Parmenides defendia que:", opt: ["O ser é imóvel e a mudança é ilusão", "Tudo muda", "Tudo é fogo", "Deus não existe"], cor: 0 },
            { id: "HUM-FIL-062", cat: "Humanas", sub: "Filosofia", txt: "Protágoras (Sofista) dizia que:", opt: ["O homem é a medida de todas as coisas", "A verdade é absoluta", "Deus é o centro", "A lei é divina"], cor: 0 },
            { id: "HUM-FIL-063", cat: "Humanas", sub: "Filosofia", txt: "O Silogismo ('Todo homem é mortal...') é de:", opt: ["Aristóteles", "Platão", "Sócrates", "Epicuro"], cor: 0 },
            { id: "HUM-FIL-064", cat: "Humanas", sub: "Filosofia", txt: "Ataraxia no Helenismo significa:", opt: ["Tranquilidade da alma/imperturbabilidade", "Busca por fama", "Guerra constante", "Medo da morte"], cor: 0 },
            { id: "HUM-FIL-065", cat: "Humanas", sub: "Filosofia", txt: "A Patrística buscava conciliar:", opt: ["Fé cristã e filosofia grega", "Ciência e Magia", "Política e Religião", "Ricos e Pobres"], cor: 0 },
            { id: "HUM-FIL-066", cat: "Humanas", sub: "Filosofia", txt: "A 'Querela dos Universais' discutia se:", opt: ["Ideias gerais (ex: 'Homem') são reais ou apenas nomes", "Deus existe", "A Terra é plana", "Anjos voam"], cor: 0 },
            { id: "HUM-FIL-067", cat: "Humanas", sub: "Filosofia", txt: "A 'Aposta de Pascal' argumenta que:", opt: ["É racional acreditar em Deus", "Deus não existe", "Devemos jogar cartas", "A vida é um jogo"], cor: 0 },
            { id: "HUM-FIL-068", cat: "Humanas", sub: "Filosofia", txt: "Spinoza identificava Deus com:", opt: ["A Natureza (Deus sive Natura)", "Um homem barbudo", "O nada", "O rei"], cor: 0 },
            { id: "HUM-FIL-069", cat: "Humanas", sub: "Filosofia", txt: "Leibniz dizia que vivemos no:", opt: ["Melhor dos mundos possíveis", "Pior mundo", "Mundo das ilusões", "Inferno"], cor: 0 },
            { id: "HUM-FIL-070", cat: "Humanas", sub: "Filosofia", txt: "Rousseau defendia a soberania da:", opt: ["Vontade Geral", "Vontade do Rei", "Vontade de Deus", "Vontade dos Ricos"], cor: 0 },
            { id: "HUM-FIL-071", cat: "Humanas", sub: "Filosofia", txt: "Heidegger focou sua filosofia no:", opt: ["Dasein (Ser-aí/Existência)", "Átomo", "Deus", "Animal"], cor: 0 },
            { id: "HUM-FIL-072", cat: "Humanas", sub: "Filosofia", txt: "Auguste Comte fundou a sociologia e o:", opt: ["Positivismo", "Negativismo", "Comunismo", "Liberalismo"], cor: 0 },
            { id: "HUM-FIL-073", cat: "Humanas", sub: "Filosofia", txt: "O Materialismo Histórico é de:", opt: ["Karl Marx", "Hegel", "Kant", "Weber"], cor: 0 },
            { id: "HUM-FIL-074", cat: "Humanas", sub: "Filosofia", txt: "Kierkegaard é considerado o pai do:", opt: ["Existencialismo cristão", "Ateísmo", "Positivismo", "Marxismo"], cor: 0 },
            { id: "HUM-FIL-075", cat: "Humanas", sub: "Filosofia", txt: "Freud influenciou a filosofia com o conceito de:", opt: ["Inconsciente", "Razão Pura", "Dever Moral", "Lógica"], cor: 0 },
            { id: "HUM-FIL-076", cat: "Humanas", sub: "Filosofia", txt: "Bertrand Russell trabalhou com:", opt: ["Lógica e Filosofia Analítica", "Misticismo", "Arte", "Política"], cor: 0 },
            { id: "HUM-FIL-077", cat: "Humanas", sub: "Filosofia", txt: "Wittgenstein falava sobre:", opt: ["Jogos de Linguagem", "Jogos de Tabuleiro", "Jogos de Poder", "Jogos de Guerra"], cor: 0 },
            { id: "HUM-FIL-078", cat: "Humanas", sub: "Filosofia", txt: "Karl Popper propôs o critério da:", opt: ["Falseabilidade (Ciência deve poder ser testada)", "Verdade absoluta", "Fé cega", "Opinião"], cor: 0 },
            { id: "HUM-FIL-079", cat: "Humanas", sub: "Filosofia", txt: "John Rawls propôs o 'Véu da Ignorância' para:", opt: ["Criar uma sociedade justa", "Ignorar problemas", "Esconder crimes", "Fazer mágica"], cor: 0 },
            { id: "HUM-FIL-080", cat: "Humanas", sub: "Filosofia", txt: "Foucault estudou o conceito de:", opt: ["Biopolítica e Poder", "Bioenergia", "Bioluminescência", "Biologia"], cor: 0 },
            { id: "HUM-FIL-081", cat: "Humanas", sub: "Filosofia", txt: "A 'Banalidade do Mal' (Arendt) refere-se a:", opt: ["Cometer o mal sem reflexão, cumprindo ordens", "Ser muito malvado", "O mal não existe", "O diabo"], cor: 0 },
            { id: "HUM-FIL-082", cat: "Humanas", sub: "Filosofia", txt: "O 'Mito de Narciso' alerta sobre:", opt: ["A vaidade e o amor excessivo por si", "A importância da água", "A beleza da flor", "A guerra"], cor: 0 },
            { id: "HUM-FIL-083", cat: "Humanas", sub: "Filosofia", txt: "Thomas More escreveu sobre uma ilha perfeita chamada:", opt: ["Utopia", "Atlântida", "Nárnia", "Olimpo"], cor: 0 },
            { id: "HUM-FIL-084", cat: "Humanas", sub: "Filosofia", txt: "A Estética estuda:", opt: ["O belo e a arte", "A moral", "A verdade", "A política"], cor: 0 },
            { id: "HUM-FIL-085", cat: "Humanas", sub: "Filosofia", txt: "Heródoto é considerado o pai da:", opt: ["História", "Filosofia", "Matemática", "Medicina"], cor: 0 },
            { id: "HUM-FIL-086", cat: "Humanas", sub: "Filosofia", txt: "Sêneca foi um filósofo:", opt: ["Estoico", "Epicurista", "Cínico", "Socrático"], cor: 0 },
            { id: "HUM-FIL-087", cat: "Humanas", sub: "Filosofia", txt: "A frase 'O homem nasce livre, mas por toda parte encontra-se acorrentado' é de:", opt: ["Rousseau", "Hobbes", "Locke", "Marx"], cor: 0 },
            { id: "HUM-FIL-088", cat: "Humanas", sub: "Filosofia", txt: "O Niilismo (Nietzsche) é a:", opt: ["Desvalorização dos valores supremos/sentido", "Crença em tudo", "Fé absoluta", "Amor à vida"], cor: 0 },
            { id: "HUM-FIL-089", cat: "Humanas", sub: "Filosofia", txt: "A Teoria das Ideias é de:", opt: ["Platão", "Aristóteles", "Sócrates", "Kant"], cor: 0 },
            { id: "HUM-FIL-090", cat: "Humanas", sub: "Filosofia", txt: "O Hilemorfismo (Matéria e Forma) é de:", opt: ["Aristóteles", "Platão", "Descartes", "Hume"], cor: 0 },
            { id: "HUM-FIL-091", cat: "Humanas", sub: "Filosofia", txt: "A Dúvida Metódica serve para:", opt: ["Alcançar uma verdade indubitável", "Duvidar por duvidar", "Ser cético pra sempre", "Ignorar tudo"], cor: 0 },
            { id: "HUM-FIL-092", cat: "Humanas", sub: "Filosofia", txt: "O imperativo 'Age de tal modo que tua ação possa virar lei universal' é de:", opt: ["Kant", "Mill", "Bentham", "Hume"], cor: 0 },
            { id: "HUM-FIL-093", cat: "Humanas", sub: "Filosofia", txt: "A 'Mão Invisível' (Adam Smith) regula:", opt: ["O mercado", "O Estado", "A igreja", "A guerra"], cor: 0 },
            { id: "HUM-FIL-094", cat: "Humanas", sub: "Filosofia", txt: "Karl Marx chamava a religião de:", opt: ["O ópio do povo", "A salvação", "A verdade", "A ciência"], cor: 0 },
            { id: "HUM-FIL-095", cat: "Humanas", sub: "Filosofia", txt: "O 'Desencantamento do Mundo' é um conceito de:", opt: ["Weber", "Marx", "Durkheim", "Comte"], cor: 0 },
            { id: "HUM-FIL-096", cat: "Humanas", sub: "Filosofia", txt: "Simone de Beauvoir era companheira de:", opt: ["Sartre", "Camus", "Foucault", "Heidegger"], cor: 0 },
            { id: "HUM-FIL-097", cat: "Humanas", sub: "Filosofia", txt: "A obra 'Leviatã' defende o:", opt: ["Estado Absoluto", "Anarquismo", "Democracia", "Comunismo"], cor: 0 },
            { id: "HUM-FIL-098", cat: "Humanas", sub: "Filosofia", txt: "Para Hume, o costume/hábito é o guia da:", opt: ["Vida humana", "Razão pura", "Verdade divina", "Matemática"], cor: 0 },
            { id: "HUM-FIL-099", cat: "Humanas", sub: "Filosofia", txt: "A Fenomenologia do Espírito é obra de:", opt: ["Hegel", "Kant", "Marx", "Schopenhauer"], cor: 0 },
            { id: "HUM-FIL-100", cat: "Humanas", sub: "Filosofia", txt: "Bioética discute temas como:", opt: ["Eutanásia, Aborto, Clonagem", "Política monetária", "História da arte", "Geometria"], cor: 0 },

];
