export const questoes = [ 

            // --- SUB: GEOGRAFIA ---
            { id: "HUM-GEO-001", cat: "Humanas", sub: "Geografia", txt: "Maior floresta tropical do mundo:", opt: ["Congo", "Amazônia", "Taiga", "Mata Atlântica"], cor: 1 },
            { id: "HUM-GEO-002", cat: "Humanas", sub: "Geografia", txt: "Capital dos Estados Unidos:", opt: ["New York", "Los Angeles", "Washington D.C.", "Miami"], cor: 2 },
            { id: "HUM-GEO-003", cat: "Humanas", sub: "Geografia", txt: "Movimento de placas tectônicas causa:", opt: ["Furacões", "Terremotos", "Secas", "Chuvas"], cor: 1 },
            { id: "HUM-GEO-004", cat: "Humanas", sub: "Geografia", txt: "Setor da economia ligado à agricultura:", opt: ["Primário", "Secundário", "Terciário", "Quaternário"], cor: 0 },
            { id: "HUM-GEO-005", cat: "Humanas", sub: "Geografia", txt: "País mais populoso do mundo (2023):", opt: ["EUA", "Brasil", "Índia", "Rússia"], cor: 2 },
            { id: "HUM-GEO-006", cat: "Humanas", sub: "Geografia", txt: "O instrumento usado para orientação pelos pontos cardeais:", opt: ["Termômetro", "Bússola", "Barômetro", "Anemômetro"], cor: 1 },
            { id: "HUM-GEO-007", cat: "Humanas", sub: "Geografia", txt: "Linha imaginária que divide a Terra em Norte e Sul:", opt: ["Meridiano de Greenwich", "Trópico de Câncer", "Linha do Equador", "Trópico de Capricórnio"], cor: 2 },
            { id: "HUM-GEO-008", cat: "Humanas", sub: "Geografia", txt: "Qual é o continente mais frio?", opt: ["Ásia", "Europa", "Antártida", "América do Norte"], cor: 2 },
            { id: "HUM-GEO-009", cat: "Humanas", sub: "Geografia", txt: "A camada de ozônio protege contra:", opt: ["Raios UV", "Chuva ácida", "Furacões", "Terremotos"], cor: 0 },
            { id: "HUM-GEO-010", cat: "Humanas", sub: "Geografia", txt: "O maior deserto quente do mundo é o:", opt: ["Atacama", "Saara", "Gobi", "Kalahari"], cor: 1 },
            { id: "HUM-GEO-011", cat: "Humanas", sub: "Geografia", txt: "Qual país tem o formato de uma bota?", opt: ["Portugal", "Espanha", "Itália", "Grécia"], cor: 2 },
            { id: "HUM-GEO-012", cat: "Humanas", sub: "Geografia", txt: "O Canal do Panamá liga os oceanos:", opt: ["Atlântico e Índico", "Atlântico e Pacífico", "Pacífico e Índico", "Ártico e Antártico"], cor: 1 },
            { id: "HUM-GEO-013", cat: "Humanas", sub: "Geografia", txt: "A capital do Japão é:", opt: ["Pequim", "Seul", "Tóquio", "Bangkok"], cor: 2 },
            { id: "HUM-GEO-014", cat: "Humanas", sub: "Geografia", txt: "O Rio Amazonas deságua no Oceano:", opt: ["Pacífico", "Atlântico", "Índico", "Glacial Ártico"], cor: 1 },
            { id: "HUM-GEO-015", cat: "Humanas", sub: "Geografia", txt: "A Cordilheira dos Andes fica na:", opt: ["América do Norte", "África", "América do Sul", "Ásia"], cor: 2 },
            { id: "HUM-GEO-016", cat: "Humanas", sub: "Geografia", txt: "Globalização é o processo de:", opt: ["Isolamento dos países", "Integração econômica e cultural", "Criação de muros", "Guerra mundial"], cor: 1 },
            { id: "HUM-GEO-017", cat: "Humanas", sub: "Geografia", txt: "O efeito estufa é agravado pela emissão de:", opt: ["Oxigênio", "Nitrogênio", "Dióxido de Carbono (CO2)", "Hidrogênio"], cor: 2 },
            { id: "HUM-GEO-018", cat: "Humanas", sub: "Geografia", txt: "Qual bloco econômico o Brasil faz parte?", opt: ["União Europeia", "Nafta", "Mercosul", "Apec"], cor: 2 },
            { id: "HUM-GEO-019", cat: "Humanas", sub: "Geografia", txt: "O IDH mede o:", opt: ["Índice de Dólar Hoje", "Desenvolvimento Humano", "Desemprego Habitual", "Dinheiro dos Homens"], cor: 1 },
            { id: "HUM-GEO-020", cat: "Humanas", sub: "Geografia", txt: "A urbanização é o crescimento das:", opt: ["Zonas rurais", "Florestas", "Cidades", "Praias"], cor: 2 },
            { id: "HUM-GEO-021", cat: "Humanas", sub: "Geografia", txt: "Qual o maior país da América do Sul?", opt: ["Argentina", "Colômbia", "Brasil", "Peru"], cor: 2 },
            { id: "HUM-GEO-022", cat: "Humanas", sub: "Geografia", txt: "O clima predominante no Nordeste brasileiro (sertão) é:", opt: ["Equatorial", "Tropical Úmido", "Semiárido", "Subtropical"], cor: 2 },
            { id: "HUM-GEO-023", cat: "Humanas", sub: "Geografia", txt: "Latitude é a distância em graus até a:", opt: ["Linha do Equador", "Meridiano de Greenwich", "Polo Norte", "Polo Sul"], cor: 0 },
            { id: "HUM-GEO-024", cat: "Humanas", sub: "Geografia", txt: "Longitude é a distância em graus até o:", opt: ["Linha do Equador", "Meridiano de Greenwich", "Trópico de Câncer", "Círculo Polar"], cor: 1 },
            { id: "HUM-GEO-025", cat: "Humanas", sub: "Geografia", txt: "Tsunamis são causados geralmente por:", opt: ["Ventos fortes", "Maremotos (terremotos no mar)", "Chuvas", "Navios"], cor: 1 },
            { id: "HUM-GEO-026", cat: "Humanas", sub: "Geografia", txt: "Qual destes é um combustível fóssil?", opt: ["Petróleo", "Etanol", "Energia Solar", "Hidrogênio"], cor: 0 },
            { id: "HUM-GEO-027", cat: "Humanas", sub: "Geografia", txt: "A camada sólida externa da Terra chama-se:", opt: ["Litosfera", "Hidrosfera", "Atmosfera", "Núcleo"], cor: 0 },
            { id: "HUM-GEO-028", cat: "Humanas", sub: "Geografia", txt: "O relevo predominante no Brasil é:", opt: ["Planalto", "Montanha", "Planície", "Depressão Absoluta"], cor: 0 },
            { id: "HUM-GEO-029", cat: "Humanas", sub: "Geografia", txt: "O Rio São Francisco nasce em:", opt: ["Minas Gerais", "Bahia", "São Paulo", "Pernambuco"], cor: 0 },
            { id: "HUM-GEO-030", cat: "Humanas", sub: "Geografia", txt: "Qual região brasileira tem mais indústrias?", opt: ["Sudeste", "Sul", "Nordeste", "Norte"], cor: 0 },
            { id: "HUM-GEO-031", cat: "Humanas", sub: "Geografia", txt: "A Mata Atlântica é uma floresta:", opt: ["Tropical", "Temperada", "Boreal", "Desértica"], cor: 0 },
            { id: "HUM-GEO-032", cat: "Humanas", sub: "Geografia", txt: "O El Niño causa no Sul do Brasil:", opt: ["Aumento de chuvas", "Seca", "Frio extremo", "Neve"], cor: 0 },
            { id: "HUM-GEO-033", cat: "Humanas", sub: "Geografia", txt: "A capital da Rússia é:", opt: ["Moscou", "São Petersburgo", "Kiev", "Minsk"], cor: 0 },
            { id: "HUM-GEO-034", cat: "Humanas", sub: "Geografia", txt: "O Canal de Suez fica no:", opt: ["Egito", "Panamá", "Brasil", "China"], cor: 0 },
            { id: "HUM-GEO-035", cat: "Humanas", sub: "Geografia", txt: "Qual país tem a maior população do mundo (2023/24)?", opt: ["Índia", "China", "EUA", "Indonésia"], cor: 0 },
            { id: "HUM-GEO-036", cat: "Humanas", sub: "Geografia", txt: "A OTAN é uma aliança:", opt: ["Militar", "Econômica", "Cultural", "Esportiva"], cor: 0 },
            { id: "HUM-GEO-037", cat: "Humanas", sub: "Geografia", txt: "Brexit foi a saída do Reino Unido da:", opt: ["União Europeia", "ONU", "OTAN", "Zona do Euro"], cor: 0 },
            { id: "HUM-GEO-038", cat: "Humanas", sub: "Geografia", txt: "A Cartografia estuda:", opt: ["Mapas", "Rochas", "Climas", "Populações"], cor: 0 },
            { id: "HUM-GEO-039", cat: "Humanas", sub: "Geografia", txt: "Escala 1:100.000 significa que 1cm no mapa vale:", opt: ["1km na realidade", "100m", "10km", "100km"], cor: 0 },
            { id: "HUM-GEO-040", cat: "Humanas", sub: "Geografia", txt: "O Meridiano 0° é o de:", opt: ["Greenwich", "Tordesilhas", "Equador", "Data"], cor: 0 },
            { id: "HUM-GEO-041", cat: "Humanas", sub: "Geografia", txt: "Fusos horários têm intervalos de:", opt: ["15 graus", "10 graus", "30 graus", "45 graus"], cor: 0 },
            { id: "HUM-GEO-042", cat: "Humanas", sub: "Geografia", txt: "A transição demográfica ocorre quando:", opt: ["Natalidade e mortalidade caem", "Natalidade sobe", "População explode", "Ninguém nasce"], cor: 0 },
            { id: "HUM-GEO-043", cat: "Humanas", sub: "Geografia", txt: "Migração pendular é:", opt: ["Ir e voltar do trabalho todo dia", "Mudar de país", "Fugir de guerra", "Nômades"], cor: 0 },
            { id: "HUM-GEO-044", cat: "Humanas", sub: "Geografia", txt: "O setor terciário da economia engloba:", opt: ["Comércio e Serviços", "Indústria", "Agricultura", "Pesquisa"], cor: 0 },
            { id: "HUM-GEO-045", cat: "Humanas", sub: "Geografia", txt: "Commodities são produtos:", opt: ["Básicos com preço internacional", "Industrializados", "Tecnológicos", "Artesanais"], cor: 0 },
            { id: "HUM-GEO-046", cat: "Humanas", sub: "Geografia", txt: "Metrópole é uma cidade que:", opt: ["Exerce influência sobre outras", "Tem praia", "Não tem indústrias", "É capital obrigatoriamente"], cor: 0 },
            { id: "HUM-GEO-047", cat: "Humanas", sub: "Geografia", txt: "Conurbação é:", opt: ["Unificação da mancha urbana de duas cidades", "Criação de favelas", "Poluição do ar", "Trânsito"], cor: 0 },
            { id: "HUM-GEO-048", cat: "Humanas", sub: "Geografia", txt: "Macrocefalia urbana ocorre quando:", opt: ["Há inchaço populacional desordenado", "A cidade é planejada", "Há muito verde", "Não há carros"], cor: 0 },
            { id: "HUM-GEO-049", cat: "Humanas", sub: "Geografia", txt: "Voçoroca é um tipo grave de:", opt: ["Erosão do solo", "Chuva ácida", "Furacão", "Poluição"], cor: 0 },
            { id: "HUM-GEO-050", cat: "Humanas", sub: "Geografia", txt: "O movimento convergente de placas tectônicas:", opt: ["Choque (uma desce, outra sobe)", "Afastamento", "Deslizamento lateral", "Não existe"], cor: 0 },
            { id: "HUM-GEO-051", cat: "Humanas", sub: "Geografia", txt: "Quando o magma sai do vulcão, chama-se:", opt: ["Lava", "Rocha", "Manto", "Núcleo"], cor: 0 },
            { id: "HUM-GEO-052", cat: "Humanas", sub: "Geografia", txt: "O Aquífero Guarani é uma reserva de:", opt: ["Água subterrânea", "Petróleo", "Gás natural", "Minério de ferro"], cor: 0 },
            { id: "HUM-GEO-053", cat: "Humanas", sub: "Geografia", txt: "Dessalinização é o processo de:", opt: ["Tirar sal da água do mar", "Salgada a água", "Congelar água", "Ferver água"], cor: 0 },
            { id: "HUM-GEO-054", cat: "Humanas", sub: "Geografia", txt: "Carvão Mineral é formado por:", opt: ["Restos vegetais fossilizados", "Rochas vulcânicas", "Ossos de dinossauro", "Areia"], cor: 0 },
            { id: "HUM-GEO-055", cat: "Humanas", sub: "Geografia", txt: "Energia Eólica vem do:", opt: ["Vento", "Sol", "Mar", "Carvão"], cor: 0 },
            { id: "HUM-GEO-056", cat: "Humanas", sub: "Geografia", txt: "A OPEP controla o preço do:", opt: ["Petróleo", "Ouro", "Dólar", "Café"], cor: 0 },
            { id: "HUM-GEO-057", cat: "Humanas", sub: "Geografia", txt: "Os Tigres Asiáticos são países com:", opt: ["Rápida industrialização recente", "Muitos tigres", "Economia agrícola", "Baixa tecnologia"], cor: 0 },
            { id: "HUM-GEO-058", cat: "Humanas", sub: "Geografia", txt: "BRICS é formado por:", opt: ["Brasil, Rússia, Índia, China, África do Sul", "Brasil e EUA", "Europa", "Países ricos"], cor: 0 },
            { id: "HUM-GEO-059", cat: "Humanas", sub: "Geografia", txt: "O IDH avalia três pilares:", opt: ["Saúde, Educação e Renda", "Felicidade, Amor e Dinheiro", "Indústria, Comércio e Agro", "Votos, Leis e Prisões"], cor: 0 },
            { id: "HUM-GEO-060", cat: "Humanas", sub: "Geografia", txt: "O Coeficiente de Gini mede a:", opt: ["Desigualdade de renda", "População", "Inflação", "Área do país"], cor: 0 },
            { id: "HUM-GEO-061", cat: "Humanas", sub: "Geografia", txt: "A Pirâmide Etária mostra:", opt: ["Distribuição da população por idade/sexo", "Riqueza do país", "Relevo", "Clima"], cor: 0 },
            { id: "HUM-GEO-062", cat: "Humanas", sub: "Geografia", txt: "Fatores repulsivos na migração são:", opt: ["Guerras, fome, desemprego", "Bons salários", "Paz", "Clima agradável"], cor: 0 },
            { id: "HUM-GEO-063", cat: "Humanas", sub: "Geografia", txt: "Refugiado é quem migra por:", opt: ["Temor fundado de perseguição/guerra", "Vontade de viajar", "Turismo", "Estudos apenas"], cor: 0 },
            { id: "HUM-GEO-064", cat: "Humanas", sub: "Geografia", txt: "O Cerrado é considerado um Hotspot pois:", opt: ["Tem alta biodiversidade e está ameaçado", "É muito quente", "Pega fogo sozinho", "É deserto"], cor: 0 },
            { id: "HUM-GEO-065", cat: "Humanas", sub: "Geografia", txt: "A Caatinga possui plantas xerófitas, que são:", opt: ["Adaptadas à seca (cactos)", "Aquáticas", "Gigantes", "Carnívoras"], cor: 0 },
            { id: "HUM-GEO-066", cat: "Humanas", sub: "Geografia", txt: "Frente Fria é o encontro de:", opt: ["Massa de ar frio com massa quente", "Dois furacões", "Chuva e sol", "Vento e mar"], cor: 0 },
            { id: "HUM-GEO-067", cat: "Humanas", sub: "Geografia", txt: "Os 'Rios Voadores' transportam umidade da:", opt: ["Amazônia para o Sul/Sudeste", "Caatinga para o Sul", "Mar para o Sertão", "Andes para o Mar"], cor: 0 },
            { id: "HUM-GEO-068", cat: "Humanas", sub: "Geografia", txt: "O Pré-Sal brasileiro é rico em:", opt: ["Petróleo", "Ouro", "Carvão", "Diamante"], cor: 0 },
            { id: "HUM-GEO-069", cat: "Humanas", sub: "Geografia", txt: "A matriz energética brasileira destaca-se por ser:", opt: ["Majoritariamente renovável (Hidrelétrica)", "Fóssil", "Nuclear", "Eólica apenas"], cor: 0 },
            { id: "HUM-GEO-070", cat: "Humanas", sub: "Geografia", txt: "O principal modal de transporte no Brasil é o:", opt: ["Rodoviário", "Ferroviário", "Hidroviário", "Aéreo"], cor: 0 },
            { id: "HUM-GEO-071", cat: "Humanas", sub: "Geografia", txt: "Soja e Minério de Ferro são exemplos de:", opt: ["Commodities", "Manufaturados", "Serviços", "Tecnologia"], cor: 0 },
            { id: "HUM-GEO-072", cat: "Humanas", sub: "Geografia", txt: "A expansão da Fronteira Agrícola avança sobre a:", opt: ["Amazônia e Cerrado", "Mata Atlântica", "Pampa", "Caatinga"], cor: 0 },
            { id: "HUM-GEO-073", cat: "Humanas", sub: "Geografia", txt: "Desmetropolização é o crescimento das:", opt: ["Cidades médias", "Capitais", "Zonas rurais", "Favelas"], cor: 0 },
            { id: "HUM-GEO-074", cat: "Humanas", sub: "Geografia", txt: "Favelização é consequência de:", opt: ["Urbanização rápida e desigualdade", "Planejamento urbano", "Excesso de casas", "Riqueza"], cor: 0 },
            { id: "HUM-GEO-075", cat: "Humanas", sub: "Geografia", txt: "Ilhas de Calor são áreas urbanas com:", opt: ["Temperaturas mais altas que o entorno", "Muitas árvores", "Ar condicionado natural", "Muitos rios"], cor: 0 },
            { id: "HUM-GEO-076", cat: "Humanas", sub: "Geografia", txt: "A Inversão Térmica no inverno causa:", opt: ["Retenção de poluentes no ar", "Chuvas torrenciais", "Neve", "Ventos fortes"], cor: 0 },
            { id: "HUM-GEO-077", cat: "Humanas", sub: "Geografia", txt: "Lixo eletrônico contém metais pesados como:", opt: ["Chumbo e Mercúrio", "Ferro e Aço", "Ouro puro", "Plástico biodegradável"], cor: 0 },
            { id: "HUM-GEO-078", cat: "Humanas", sub: "Geografia", txt: "Pegada Ecológica mede:", opt: ["Impacto humano sobre a natureza", "Tamanho do pé", "Quantidade de floresta", "Número de animais"], cor: 0 },
            { id: "HUM-GEO-079", cat: "Humanas", sub: "Geografia", txt: "A Eco-92 (Rio-92) foi uma conferência sobre:", opt: ["Meio Ambiente e Desenvolvimento", "Economia Global", "Guerra", "Saúde"], cor: 0 },
            { id: "HUM-GEO-080", cat: "Humanas", sub: "Geografia", txt: "Conflitos pela água são comuns no:", opt: ["Oriente Médio", "Brasil", "Canadá", "Antártida"], cor: 0 },
            { id: "HUM-GEO-081", cat: "Humanas", sub: "Geografia", txt: "A Caxemira é uma região disputada por:", opt: ["Índia, Paquistão e China", "EUA e Rússia", "Coreias", "Israel e Palestina"], cor: 0 },
            { id: "HUM-GEO-082", cat: "Humanas", sub: "Geografia", txt: "A Questão Palestina envolve disputas territoriais com:", opt: ["Israel", "Egito", "Turquia", "Irã"], cor: 0 },
            { id: "HUM-GEO-083", cat: "Humanas", sub: "Geografia", txt: "A 'Guerra Comercial' recente envolveu principalmente:", opt: ["EUA e China", "Brasil e Argentina", "Rússia e Ucrânia", "Japão e Coreia"], cor: 0 },
            { id: "HUM-GEO-084", cat: "Humanas", sub: "Geografia", txt: "A Nova Rota da Seda é um projeto da:", opt: ["China", "Índia", "Rússia", "União Europeia"], cor: 0 },
            { id: "HUM-GEO-085", cat: "Humanas", sub: "Geografia", txt: "Qual bloco econômico substituiu o NAFTA?", opt: ["USMCA", "Mercosul", "União Europeia", "ALCA"], cor: 0 },
            { id: "HUM-GEO-086", cat: "Humanas", sub: "Geografia", txt: "O Pantanal é caracterizado por ser uma:", opt: ["Planície alagável", "Floresta densa", "Montanha alta", "Área desértica"], cor: 0 },
            { id: "HUM-GEO-087", cat: "Humanas", sub: "Geografia", txt: "O solo de 'Terra Roxa' é favorável ao:", opt: ["Café", "Cacto", "Arroz alagado", "Trigo"], cor: 0 },
            { id: "HUM-GEO-088", cat: "Humanas", sub: "Geografia", txt: "O fenômeno La Niña causa no Sul do Brasil:", opt: ["Secas (diminuição de chuvas)", "Enchentes", "Calor extremo", "Furacões"], cor: 0 },
            { id: "HUM-GEO-089", cat: "Humanas", sub: "Geografia", txt: "A Projeção de Mercator (cilíndrica) distorce:", opt: ["Os tamanhos (aumenta polos)", "As formas", "O centro", "Nada"], cor: 0 },
            { id: "HUM-GEO-090", cat: "Humanas", sub: "Geografia", txt: "A Projeção de Peters (cilíndrica) é conhecida por:", opt: ["Manter as proporções reais das áreas", "Aumentar a Europa", "Ser redonda", "Não ter mapa"], cor: 0 },
            { id: "HUM-GEO-091", cat: "Humanas", sub: "Geografia", txt: "O Círculo de Fogo do Pacífico concentra:", opt: ["A maioria dos vulcões e terremotos", "As maiores florestas", "Os países mais ricos", "O gelo polar"], cor: 0 },
            { id: "HUM-GEO-092", cat: "Humanas", sub: "Geografia", txt: "Biocombustíveis são derivados de:", opt: ["Matéria orgânica (cana, milho)", "Petróleo", "Urânio", "Carvão"], cor: 0 },
            { id: "HUM-GEO-093", cat: "Humanas", sub: "Geografia", txt: "O Tratado de Paris (2015) visa combater:", opt: ["O aquecimento global", "O terrorismo", "A fome", "A pobreza"], cor: 0 },
            { id: "HUM-GEO-094", cat: "Humanas", sub: "Geografia", txt: "Xenofobia é:", opt: ["Aversão a estrangeiros", "Medo de altura", "Amor ao próximo", "Gosto por viagens"], cor: 0 },
            { id: "HUM-GEO-095", cat: "Humanas", sub: "Geografia", txt: "A Revolução Verde foi:", opt: ["Modernização da agricultura (tecnologia/química)", "Plantio de árvores", "Agricultura orgânica", "Fim da fome"], cor: 0 },
            { id: "HUM-GEO-096", cat: "Humanas", sub: "Geografia", txt: "Obsolescência Programada é:", opt: ["Produtos feitos para durar pouco", "Produtos eternos", "Reciclagem", "Garantia estendida"], cor: 0 },
            { id: "HUM-GEO-097", cat: "Humanas", sub: "Geografia", txt: "Dumping comercial é:", opt: ["Vender abaixo do custo para quebrar concorrência", "Jogar lixo no mar", "Aumentar preços", "Taxar importação"], cor: 0 },
            { id: "HUM-GEO-098", cat: "Humanas", sub: "Geografia", txt: "O Canal da Mancha liga:", opt: ["França e Inglaterra", "Espanha e África", "Brasil e África", "EUA e Canadá"], cor: 0 },
            { id: "HUM-GEO-099", cat: "Humanas", sub: "Geografia", txt: "A capital da Ucrânia é:", opt: ["Kiev", "Moscou", "Varsóvia", "Minsk"], cor: 0 },
            { id: "HUM-GEO-100", cat: "Humanas", sub: "Geografia", txt: "O Rio Nilo fica na:", opt: ["África (Egito)", "América do Sul", "Ásia", "Europa"], cor: 0 },


];
