export const questoes = [
  
            // --- SUB: HISTÓRIA ---
            { id: "HUM-HIS-001", cat: "Humanas", sub: "História", txt: "Quem descobriu o Brasil?", opt: ["Cabral", "Colombo", "Vasco da Gama", "Pero Vaz"], cor: 0 },
            { id: "HUM-HIS-002", cat: "Humanas", sub: "História", txt: "Era Vargas durou de:", opt: ["1930-1945", "1964-1985", "1889-1930", "1500-1822"], cor: 0 },
            { id: "HUM-HIS-003", cat: "Humanas", sub: "História", txt: "A Lei Áurea aboliu:", opt: ["A Monarquia", "A Escravidão", "O Imposto", "A Guerra"], cor: 1 },
            { id: "HUM-HIS-004", cat: "Humanas", sub: "História", txt: "Ditadura Militar no Brasil iniciou em:", opt: ["1945", "1950", "1964", "1985"], cor: 2 },
            { id: "HUM-HIS-005", cat: "Humanas", sub: "História", txt: "Revolução que decapitou Luís XVI:", opt: ["Industrial", "Francesa", "Russa", "Americana"], cor: 1 },
            { id: "HUM-HIS-006", cat: "Humanas", sub: "História", txt: "A Segunda Guerra Mundial terminou em:", opt: ["1939", "1942", "1945", "1950"], cor: 2 },
            { id: "HUM-HIS-007", cat: "Humanas", sub: "História", txt: "Civilização que construiu as Pirâmides:", opt: ["Grega", "Romana", "Egípcia", "Maia"], cor: 2 },
            { id: "HUM-HIS-008", cat: "Humanas", sub: "História", txt: "O feudalismo foi o sistema típico da:", opt: ["Idade Antiga", "Idade Média", "Idade Moderna", "Idade Contemporânea"], cor: 1 },
            { id: "HUM-HIS-009", cat: "Humanas", sub: "História", txt: "Líder da luta contra o Apartheid na África do Sul:", opt: ["Gandhi", "Mandela", "Martin Luther King", "Malcolm X"], cor: 1 },
            { id: "HUM-HIS-010", cat: "Humanas", sub: "História", txt: "A Queda da Bastilha marcou o início da:", opt: ["Revolução Russa", "Revolução Francesa", "Independência do Brasil", "Guerra Fria"], cor: 1 },
            { id: "HUM-HIS-011", cat: "Humanas", sub: "História", txt: "Quem proclamou a independência do Brasil?", opt: ["D. Pedro I", "D. Pedro II", "Tiradentes", "Deodoro da Fonseca"], cor: 0 },
            { id: "HUM-HIS-012", cat: "Humanas", sub: "História", txt: "A Guerra Fria foi um conflito entre:", opt: ["EUA e China", "EUA e URSS", "Alemanha e Inglaterra", "Coreia do Norte e Sul"], cor: 1 },
            { id: "HUM-HIS-013", cat: "Humanas", sub: "História", txt: "O Holocausto vitimou principalmente:", opt: ["Judeus", "Cristãos", "Budistas", "Muçulmanos"], cor: 0 },
            { id: "HUM-HIS-014", cat: "Humanas", sub: "História", txt: "A Revolução Industrial começou na:", opt: ["França", "Inglaterra", "Alemanha", "Itália"], cor: 1 },
            { id: "HUM-HIS-015", cat: "Humanas", sub: "História", txt: "O Muro de Berlim dividia:", opt: ["Berlim Norte e Sul", "Alemanha Oriental e Ocidental", "França e Alemanha", "Europa e Ásia"], cor: 1 },
            { id: "HUM-HIS-016", cat: "Humanas", sub: "História", txt: "Machu Picchu é uma cidade da civilização:", opt: ["Asteca", "Maia", "Inca", "Olmeca"], cor: 2 },
            { id: "HUM-HIS-017", cat: "Humanas", sub: "História", txt: "Quem foi o primeiro presidente do Brasil?", opt: ["Getúlio Vargas", "Deodoro da Fonseca", "Floriano Peixoto", "Prudente de Morais"], cor: 1 },
            { id: "HUM-HIS-018", cat: "Humanas", sub: "História", txt: "A Crise de 1929 começou com:", opt: ["A Quebra da Bolsa de NY", "A 1ª Guerra Mundial", "A Revolução Russa", "A Gripe Espanhola"], cor: 0 },
            { id: "HUM-HIS-019", cat: "Humanas", sub: "História", txt: "O Renascimento Cultural valorizava o:", opt: ["Teocentrismo", "Antropocentrismo", "Misticismo", "Feudalismo"], cor: 1 },
            { id: "HUM-HIS-020", cat: "Humanas", sub: "História", txt: "Zumbi dos Palmares foi líder do:", opt: ["Quilombo dos Palmares", "Revolta da Chibata", "Guerra de Canudos", "Inconfidência Mineira"], cor: 0 },
            { id: "HUM-HIS-021", cat: "Humanas", sub: "História", txt: "A Guerra do Paraguai envolveu Brasil, Argentina e:", opt: ["Chile", "Uruguai", "Bolívia", "Equador"], cor: 1 },
            { id: "HUM-HIS-022", cat: "Humanas", sub: "História", txt: "O Plano Real foi criado no governo de:", opt: ["Sarney", "Collor", "Itamar Franco", "FHC"], cor: 2 },
            { id: "HUM-HIS-023", cat: "Humanas", sub: "História", txt: "Napoleão Bonaparte foi imperador da:", opt: ["Inglaterra", "Espanha", "França", "Áustria"], cor: 2 },
            { id: "HUM-HIS-024", cat: "Humanas", sub: "História", txt: "A Rota da Seda ligava:", opt: ["Europa e Ásia (China)", "Europa e América", "África e Ásia", "Brasil e Portugal"], cor: 0 },
            { id: "HUM-HIS-025", cat: "Humanas", sub: "História", txt: "Quem pintou a Mona Lisa?", opt: ["Michelangelo", "Rafael", "Donatello", "Leonardo da Vinci"], cor: 3 },
            { id: "HUM-HIS-026", cat: "Humanas", sub: "História", txt: "A Guerra de Canudos ocorreu no sertão da:", opt: ["Bahia", "Paraíba", "Pernambuco", "Ceará"], cor: 0 },
            { id: "HUM-HIS-027", cat: "Humanas", sub: "História", txt: "O movimento Tenentismo exigia:", opt: ["Fim da corrupção e voto secreto", "Volta da Monarquia", "Escravidão", "Ditadura"], cor: 0 },
            { id: "HUM-HIS-028", cat: "Humanas", sub: "História", txt: "A Política do Café com Leite alternava poder entre:", opt: ["SP e MG", "RJ e SP", "MG e RS", "BA e PE"], cor: 0 },
            { id: "HUM-HIS-029", cat: "Humanas", sub: "História", txt: "A 'Intentona Comunista' foi liderada por:", opt: ["Luís Carlos Prestes", "Getúlio Vargas", "Plínio Salgado", "Lampião"], cor: 0 },
            { id: "HUM-HIS-030", cat: "Humanas", sub: "História", txt: "O 'Milagre Econômico' ocorreu durante:", opt: ["A Ditadura Militar", "A Era Vargas", "O governo Lula", "O Império"], cor: 0 },
            { id: "HUM-HIS-031", cat: "Humanas", sub: "História", txt: "A Lei Eusébio de Queirós (1850) proibia:", opt: ["O tráfico negreiro", "A escravidão", "O trabalho infantil", "A venda de café"], cor: 0 },
            { id: "HUM-HIS-032", cat: "Humanas", sub: "História", txt: "Tiradentes foi enforcado por participar da:", opt: ["Inconfidência Mineira", "Conjuração Baiana", "Revolta da Vacina", "Guerra dos Farrapos"], cor: 0 },
            { id: "HUM-HIS-033", cat: "Humanas", sub: "História", txt: "A Tríplice Entente na 1ª Guerra era formada por:", opt: ["Inglaterra, França e Rússia", "Alemanha, Áustria e Itália", "EUA, Japão e Brasil", "China, Coreia e Vietnã"], cor: 0 },
            { id: "HUM-HIS-034", cat: "Humanas", sub: "História", txt: "O Fascismo surgiu na:", opt: ["Itália", "Alemanha", "Espanha", "Rússia"], cor: 0 },
            { id: "HUM-HIS-035", cat: "Humanas", sub: "História", txt: "O Nazismo foi liderado por:", opt: ["Hitler", "Mussolini", "Stalin", "Franco"], cor: 0 },
            { id: "HUM-HIS-036", cat: "Humanas", sub: "História", txt: "A Revolução Russa de 1917 implantou o:", opt: ["Socialismo", "Capitalismo", "Feudalismo", "Anarquismo"], cor: 0 },
            { id: "HUM-HIS-037", cat: "Humanas", sub: "História", txt: "O 'New Deal' foi um plano para recuperar os EUA após:", opt: ["A Crise de 29", "A 2ª Guerra", "A Guerra Civil", "O 11 de Setembro"], cor: 0 },
            { id: "HUM-HIS-038", cat: "Humanas", sub: "História", txt: "Gandhi lutou pela independência da:", opt: ["Índia", "África do Sul", "China", "Paquistão"], cor: 0 },
            { id: "HUM-HIS-039", cat: "Humanas", sub: "História", txt: "A Guerra do Vietnã foi um conflito da:", opt: ["Guerra Fria", "2ª Guerra Mundial", "Era Napoleônica", "Idade Média"], cor: 0 },
            { id: "HUM-HIS-040", cat: "Humanas", sub: "História", txt: "O Muro de Berlim caiu em:", opt: ["1989", "1945", "1961", "1991"], cor: 0 },
            { id: "HUM-HIS-041", cat: "Humanas", sub: "História", txt: "Quem descobriu a América em 1492?", opt: ["Colombo", "Cabral", "Vasco da Gama", "Magalhães"], cor: 0 },
            { id: "HUM-HIS-042", cat: "Humanas", sub: "História", txt: "A Reforma Protestante foi iniciada por:", opt: ["Martinho Lutero", "João Calvino", "Henrique VIII", "Papa Leão X"], cor: 0 },
            { id: "HUM-HIS-043", cat: "Humanas", sub: "História", txt: "O Iluminismo defendia:", opt: ["A razão e a liberdade", "O poder absoluto dos reis", "A fé cega", "A escravidão"], cor: 0 },
            { id: "HUM-HIS-044", cat: "Humanas", sub: "História", txt: "A Bastilha era uma prisão símbolo do:", opt: ["Absolutismo", "Democracia", "Comunismo", "Nazismo"], cor: 0 },
            { id: "HUM-HIS-045", cat: "Humanas", sub: "História", txt: "A Guerra de Secessão ocorreu nos:", opt: ["Estados Unidos", "Brasil", "França", "Rússia"], cor: 0 },
            { id: "HUM-HIS-046", cat: "Humanas", sub: "História", txt: "O Tratado de Tordesilhas dividiu o mundo entre:", opt: ["Portugal e Espanha", "Inglaterra e França", "EUA e URSS", "Igreja e Estado"], cor: 0 },
            { id: "HUM-HIS-047", cat: "Humanas", sub: "História", txt: "A Conjuração Baiana (Revolta dos Alfaiates) queria:", opt: ["Fim da escravidão e República", "Volta do Rei", "Manter a escravidão", "Separar apenas o Sul"], cor: 0 },
            { id: "HUM-HIS-048", cat: "Humanas", sub: "História", txt: "A principal fonte de energia da 1ª Revolução Industrial foi:", opt: ["Carvão Mineral", "Petróleo", "Energia Nuclear", "Solar"], cor: 0 },
            { id: "HUM-HIS-049", cat: "Humanas", sub: "História", txt: "O estopim da 1ª Guerra Mundial foi:", opt: ["A morte de Francisco Ferdinando", "A invasão da Polônia", "A bomba de Hiroshima", "A queda da Bastilha"], cor: 0 },
            { id: "HUM-HIS-050", cat: "Humanas", sub: "História", txt: "A Belle Époque foi um período de:", opt: ["Otimismo e avanço cultural em Paris", "Guerra total", "Peste Negra", "Escravidão"], cor: 0 },
            { id: "HUM-HIS-051", cat: "Humanas", sub: "História", txt: "O Populismo no Brasil é associado à figura de:", opt: ["Getúlio Vargas", "Dom Pedro II", "Tiradentes", "Cabral"], cor: 0 },
            { id: "HUM-HIS-052", cat: "Humanas", sub: "História", txt: "O lema '50 anos em 5' pertence a:", opt: ["Juscelino Kubitschek (JK)", "Vargas", "Lula", "Médici"], cor: 0 },
            { id: "HUM-HIS-053", cat: "Humanas", sub: "História", txt: "O movimento 'Diretas Já' (1984) pedia:", opt: ["Eleições diretas para Presidente", "Volta da Monarquia", "Fim do Plano Real", "Guerra contra a Argentina"], cor: 0 },
            { id: "HUM-HIS-054", cat: "Humanas", sub: "História", txt: "O lema da Revolução Francesa era:", opt: ["Liberdade, Igualdade, Fraternidade", "Deus, Pátria e Família", "Ordem e Progresso", "Pão e Circo"], cor: 0 },
            { id: "HUM-HIS-055", cat: "Humanas", sub: "História", txt: "O Império Romano do Ocidente caiu em:", opt: ["476 d.C.", "1453 d.C.", "1000 a.C.", "2000 d.C."], cor: 0 },
            { id: "HUM-HIS-056", cat: "Humanas", sub: "História", txt: "As Cruzadas tinham como objetivo principal:", opt: ["Retomar Jerusalém (Terra Santa)", "Descobrir a América", "Vender especiarias", "Destruir Roma"], cor: 0 },
            { id: "HUM-HIS-057", cat: "Humanas", sub: "História", txt: "A Peste Negra (século XIV) dizimou a Europa e era transmitida por:", opt: ["Pulgas de ratos", "Mosquitos", "Água suja", "Ar"], cor: 0 },
            { id: "HUM-HIS-058", cat: "Humanas", sub: "História", txt: "O Mercantilismo visava:", opt: ["Acúmulo de metais preciosos", "Livre mercado", "Igualdade social", "Fim do Estado"], cor: 0 },
            { id: "HUM-HIS-059", cat: "Humanas", sub: "História", txt: "A Independência dos EUA ocorreu em:", opt: ["4 de Julho de 1776", "7 de Setembro de 1822", "14 de Julho de 1789", "15 de Novembro de 1889"], cor: 0 },
            { id: "HUM-HIS-060", cat: "Humanas", sub: "História", txt: "A Crise dos Mísseis (1962) envolveu:", opt: ["EUA, URSS e Cuba", "Brasil e Argentina", "China e Japão", "Alemanha e França"], cor: 0 },
            { id: "HUM-HIS-061", cat: "Humanas", sub: "História", txt: "O acidente nuclear de Chernobyl ocorreu na:", opt: ["Ucrânia (Antiga URSS)", "Japão", "EUA", "Brasil"], cor: 0 },
            { id: "HUM-HIS-062", cat: "Humanas", sub: "História", txt: "O Apartheid foi um regime de segregação na:", opt: ["África do Sul", "Nigéria", "Angola", "Índia"], cor: 0 },
            { id: "HUM-HIS-063", cat: "Humanas", sub: "História", txt: "Nelson Mandela ficou preso por:", opt: ["27 anos", "5 anos", "1 ano", "Nunca foi preso"], cor: 0 },
            { id: "HUM-HIS-064", cat: "Humanas", sub: "História", txt: "O Golpe Militar no Brasil ocorreu em:", opt: ["1964", "1954", "1945", "1985"], cor: 0 },
            { id: "HUM-HIS-065", cat: "Humanas", sub: "História", txt: "A Constituição de 1988 é conhecida como:", opt: ["Constituição Cidadã", "Constituição Polaca", "Carta Magna Libertadora", "Lei Áurea"], cor: 0 },
            { id: "HUM-HIS-066", cat: "Humanas", sub: "História", txt: "As Capitanias Hereditárias fracassaram devido à:", opt: ["Falta de recursos e ataques indígenas", "Falta de terra", "Proibição do Rei", "Falta de mar"], cor: 0 },
            { id: "HUM-HIS-067", cat: "Humanas", sub: "História", txt: "As Bandeiras eram expedições para:", opt: ["Capturar indígenas e achar ouro", "Plantar café", "Fundar escolas", "Proteger a floresta"], cor: 0 },
            { id: "HUM-HIS-068", cat: "Humanas", sub: "História", txt: "A Inconfidência Mineira foi um movimento:", opt: ["Elitista e separatista", "Popular e abolicionista", "Monarquista", "Religioso"], cor: 0 },
            { id: "HUM-HIS-069", cat: "Humanas", sub: "História", txt: "A vinda da Família Real (1808) causou a:", opt: ["Abertura dos Portos", "Guerra do Paraguai", "Proclamação da República", "Fim da escravidão"], cor: 0 },
            { id: "HUM-HIS-070", cat: "Humanas", sub: "História", txt: "O Primeiro Reinado (D. Pedro I) terminou com:", opt: ["A abdicação do imperador", "A morte do rei", "Um golpe militar", "A eleição"], cor: 0 },
            { id: "HUM-HIS-071", cat: "Humanas", sub: "História", txt: "O Período Regencial foi marcado por:", opt: ["Muitas revoltas provinciais (Cabanagem, Farroupilha)", "Paz absoluta", "Riqueza extrema", "Democracia plena"], cor: 0 },
            { id: "HUM-HIS-072", cat: "Humanas", sub: "História", txt: "A Guerra do Paraguai resultou em:", opt: ["Fortalecimento do Exército Brasileiro e dívidas", "Vitória do Paraguai", "Anexação da Argentina", "Fim do Uruguai"], cor: 0 },
            { id: "HUM-HIS-073", cat: "Humanas", sub: "História", txt: "A Lei do Ventre Livre declarava livres:", opt: ["Os filhos de escravos nascidos a partir daquela data", "Todos os escravos", "Os idosos", "Os doentes"], cor: 0 },
            { id: "HUM-HIS-074", cat: "Humanas", sub: "História", txt: "O 'Voto de Cabresto' era comum na:", opt: ["República Velha (Coronelismo)", "Era Vargas", "Ditadura", "Nova República"], cor: 0 },
            { id: "HUM-HIS-075", cat: "Humanas", sub: "História", txt: "A Revolução de 1930 levou ao poder:", opt: ["Getúlio Vargas", "Juscelino Kubitschek", "Washington Luís", "Dom Pedro II"], cor: 0 },
            { id: "HUM-HIS-076", cat: "Humanas", sub: "História", txt: "O DIP (Departamento de Imprensa e Propaganda) servia para:", opt: ["Censurar e fazer propaganda de Vargas", "Imprimir jornais livres", "Educar crianças", "Vender rádio"], cor: 0 },
            { id: "HUM-HIS-077", cat: "Humanas", sub: "História", txt: "A Petrobras foi criada com o lema:", opt: ["O petróleo é nosso", "Ordem e Progresso", "Brasil acima de tudo", "Energia para todos"], cor: 0 },
            { id: "HUM-HIS-078", cat: "Humanas", sub: "História", txt: "O Ato Institucional nº 5 (AI-5) decretou:", opt: ["O endurecimento da Ditadura e fim de direitos", "A volta da democracia", "Eleições diretas", "Fim da censura"], cor: 0 },
            { id: "HUM-HIS-079", cat: "Humanas", sub: "História", txt: "O movimento 'Caras-Pintadas' pedia:", opt: ["O impeachment de Collor", "A volta de Vargas", "Diretas Já", "Fim da Ditadura"], cor: 0 },
            { id: "HUM-HIS-080", cat: "Humanas", sub: "História", txt: "A Primavera Árabe foi uma série de:", opt: ["Protestos por democracia no Oriente Médio/África", "Festivais de música", "Guerras religiosas", "Acordos de paz"], cor: 0 },
            { id: "HUM-HIS-081", cat: "Humanas", sub: "História", txt: "A Contrarreforma Católica criou a:", opt: ["Companhia de Jesus (Jesuítas) e Inquisição", "Igreja Anglicana", "Bíblia alemã", "Liberdade de culto"], cor: 0 },
            { id: "HUM-HIS-082", cat: "Humanas", sub: "História", txt: "O Absolutismo defendia que o poder do rei vinha de:", opt: ["Deus (Direito Divino)", "Do povo", "Do exército", "Dos comerciantes"], cor: 0 },
            { id: "HUM-HIS-083", cat: "Humanas", sub: "História", txt: "Adam Smith é o pai do:", opt: ["Liberalismo Econômico", "Comunismo", "Anarquismo", "Mercantilismo"], cor: 0 },
            { id: "HUM-HIS-084", cat: "Humanas", sub: "História", txt: "O Anarquismo defende:", opt: ["Fim do Estado e autogestão", "Estado forte", "Monarquia", "Ditadura do proletariado"], cor: 0 },
            { id: "HUM-HIS-085", cat: "Humanas", sub: "História", txt: "Os atentados de 11 de Setembro (2001) ocorreram em:", opt: ["Nova York (World Trade Center)", "Washington", "Londres", "Paris"], cor: 0 },
            { id: "HUM-HIS-086", cat: "Humanas", sub: "História", txt: "A Lei de Terras (1850) determinou que:", opt: ["A terra só poderia ser adquirida por compra", "A terra era de quem ocupasse", "Escravos ganhariam terras", "Índios teriam reservas"], cor: 0 },
            { id: "HUM-HIS-087", cat: "Humanas", sub: "História", txt: "O Ciclo da Borracha enriqueceu a região:", opt: ["Norte (Manaus/Belém)", "Sudeste", "Sul", "Nordeste"], cor: 0 },
            { id: "HUM-HIS-088", cat: "Humanas", sub: "História", txt: "A Revolução Constitucionalista de 1932 foi liderada por:", opt: ["São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia"], cor: 0 },
            { id: "HUM-HIS-089", cat: "Humanas", sub: "História", txt: "O Plano Marshall foi:", opt: ["Ajuda dos EUA para reconstruir a Europa pós-2ª Guerra", "Plano de invasão da URSS", "Criação da Bomba Atômica", "Plano econômico brasileiro"], cor: 0 },
            { id: "HUM-HIS-090", cat: "Humanas", sub: "História", txt: "A Queda do Muro de Berlim simbolizou o fim:", opt: ["Da Guerra Fria", "Da 2ª Guerra Mundial", "Da 1ª Guerra Mundial", "Do Império Romano"], cor: 0 },
            { id: "HUM-HIS-091", cat: "Humanas", sub: "História", txt: "O voto feminino no Brasil foi conquistado em:", opt: ["1932 (Era Vargas)", "1889 (República)", "1988 (Constituição)", "2000"], cor: 0 },
            { id: "HUM-HIS-092", cat: "Humanas", sub: "História", txt: "A Guerra de Canudos teve como líder:", opt: ["Antônio Conselheiro", "Lampião", "Padre Cícero", "Zumbi"], cor: 0 },
            { id: "HUM-HIS-093", cat: "Humanas", sub: "História", txt: "O Período entre as duas guerras mundiais viu a ascensão do:", opt: ["Totalitarismo (Nazifascismo)", "Liberalismo pleno", "Comunismo global", "Paz mundial"], cor: 0 },
            { id: "HUM-HIS-094", cat: "Humanas", sub: "História", txt: "A Descolonização da África e Ásia ocorreu principalmente:", opt: ["Após a 2ª Guerra Mundial", "No século XIX", "Na Idade Média", "Hoje em dia"], cor: 0 },
            { id: "HUM-HIS-095", cat: "Humanas", sub: "História", txt: "O Impeachment de Dilma Rousseff ocorreu em:", opt: ["2016", "2014", "2018", "2010"], cor: 0 },
            { id: "HUM-HIS-096", cat: "Humanas", sub: "História", txt: "A Lei da Anistia (1979) permitiu:", opt: ["O retorno de exilados políticos", "A prisão de militares", "A pena de morte", "O fim da eleição"], cor: 0 },
            { id: "HUM-HIS-097", cat: "Humanas", sub: "História", txt: "A Guerra das Malvinas foi entre:", opt: ["Argentina e Reino Unido", "Brasil e Argentina", "Chile e Peru", "EUA e Cuba"], cor: 0 },
            { id: "HUM-HIS-098", cat: "Humanas", sub: "História", txt: "O Massacre de Tiananmen ocorreu na:", opt: ["China", "Rússia", "Coreia", "Japão"], cor: 0 },
            { id: "HUM-HIS-099", cat: "Humanas", sub: "História", txt: "A Revolução Cubana (1959) foi liderada por:", opt: ["Fidel Castro e Che Guevara", "Pinochet", "Perón", "Bolívar"], cor: 0 },
            { id: "HUM-HIS-100", cat: "Humanas", sub: "História", txt: "O 'Dia D' na 2ª Guerra foi:", opt: ["O desembarque aliado na Normandia", "A bomba atômica", "A invasão da Polônia", "A rendição da Alemanha"], cor: 0 },

];
