export const questoes = [
 
            // --- SUB: SOCIOLOGIA ---
            { id: "HUM-SOC-001", cat: "Humanas", sub: "Sociologia", txt: "Conceito de 'Fato Social' é de:", opt: ["Weber", "Durkheim", "Marx", "Comte"], cor: 1 },
            { id: "HUM-SOC-002", cat: "Humanas", sub: "Sociologia", txt: "Karl Marx dividia a sociedade em Burguesia e:", opt: ["Nobreza", "Clero", "Proletariado", "Camponeses"], cor: 2 },
            { id: "HUM-SOC-003", cat: "Humanas", sub: "Sociologia", txt: "Max Weber estudou a Ética Protestante e o:", opt: ["Espírito do Capitalismo", "Comunismo", "Feudalismo", "Anarquismo"], cor: 0 },
            { id: "HUM-SOC-004", cat: "Humanas", sub: "Sociologia", txt: "O Positivismo foi criado por:", opt: ["Auguste Comte", "Durkheim", "Weber", "Marx"], cor: 0 },
            { id: "HUM-SOC-005", cat: "Humanas", sub: "Sociologia", txt: "Para Durkheim, o suicídio é um fato:", opt: ["Psicológico", "Biológico", "Social", "Divino"], cor: 2 },
            { id: "HUM-SOC-006", cat: "Humanas", sub: "Sociologia", txt: "Gilberto Freyre escreveu:", opt: ["Raízes do Brasil", "Casa-Grande & Senzala", "O Povo Brasileiro", "Os Sertões"], cor: 1 },
            { id: "HUM-SOC-007", cat: "Humanas", sub: "Sociologia", txt: "Sérgio Buarque de Holanda criou o conceito de:", opt: ["Homem Cordial", "Mito da Democracia Racial", "Jeitinho Brasileiro", "Antropofagia"], cor: 0 },
            { id: "HUM-SOC-008", cat: "Humanas", sub: "Sociologia", txt: "Estratificação social refere-se à:", opt: ["Divisão da sociedade em camadas/classes", "União de todos", "Igualdade total", "Migração"], cor: 0 },
            { id: "HUM-SOC-009", cat: "Humanas", sub: "Sociologia", txt: "Cultura de Massa é produzida pela:", opt: ["Indústria Cultural", "Elite intelectual", "Tradição oral", "Escola"], cor: 0 },
            { id: "HUM-SOC-010", cat: "Humanas", sub: "Sociologia", txt: "O conceito de 'Mais-Valia' (lucro extraído do trabalho) é de:", opt: ["Marx", "Weber", "Durkheim", "Smith"], cor: 0 },
            { id: "HUM-SOC-011", cat: "Humanas", sub: "Sociologia", txt: "Anomia social (falta de normas) é um conceito de:", opt: ["Durkheim", "Marx", "Weber", "Comte"], cor: 0 },
            { id: "HUM-SOC-012", cat: "Humanas", sub: "Sociologia", txt: "A 'Ação Social' é o foco de estudo de:", opt: ["Max Weber", "Karl Marx", "Durkheim", "Platão"], cor: 0 },
            { id: "HUM-SOC-013", cat: "Humanas", sub: "Sociologia", txt: "Zygmunt Bauman criou o conceito de:", opt: ["Modernidade Líquida", "Fim da História", "Aldeia Global", "Sociedade do Espetáculo"], cor: 0 },
            { id: "HUM-SOC-014", cat: "Humanas", sub: "Sociologia", txt: "Pierre Bourdieu estudou o:", opt: ["Capital Cultural", "Capital Financeiro", "Capital Político", "Capital Natural"], cor: 0 },
            { id: "HUM-SOC-015", cat: "Humanas", sub: "Sociologia", txt: "O que é Etnocentrismo?", opt: ["Julgar outra cultura pela sua própria", "Aceitar todas as culturas", "Estudar etnias", "Viajar muito"], cor: 0 },
            { id: "HUM-SOC-016", cat: "Humanas", sub: "Sociologia", txt: "Movimentos sociais buscam:", opt: ["Mudanças ou manutenção na sociedade", "Apenas festa", "Vender produtos", "Isolamento"], cor: 0 },
            { id: "HUM-SOC-017", cat: "Humanas", sub: "Sociologia", txt: "A Democracia Racial no Brasil é considerada:", opt: ["Uma realidade plena", "Um mito", "Uma lei", "Uma religião"], cor: 1 },
            { id: "HUM-SOC-018", cat: "Humanas", sub: "Sociologia", txt: "Globalização cultural pode levar à:", opt: ["Padronização de costumes", "Extinção da internet", "Paz mundial imediata", "Fim do comércio"], cor: 0 },
            { id: "HUM-SOC-019", cat: "Humanas", sub: "Sociologia", txt: "Desigualdade social é medida pelo Índice de:", opt: ["Gini", "Big Mac", "Massa Corporal", "Audiência"], cor: 0 },
            { id: "HUM-SOC-020", cat: "Humanas", sub: "Sociologia", txt: "Patriarcado é um sistema onde:", opt: ["Mulheres dominam", "Homens detêm o poder principal", "Crianças governam", "Ninguém manda"], cor: 1 },
            { id: "HUM-SOC-021", cat: "Humanas", sub: "Sociologia", txt: "Meritocracia defende que o sucesso depende do:", opt: ["Mérito/Esforço individual", "Sorte", "Sobrenome", "Governo"], cor: 0 },
            { id: "HUM-SOC-022", cat: "Humanas", sub: "Sociologia", txt: "A família é uma instituição:", opt: ["Social", "Política", "Econômica apenas", "Militar"], cor: 0 },
            { id: "HUM-SOC-023", cat: "Humanas", sub: "Sociologia", txt: "O Estado detém o monopólio do:", opt: ["Uso legítimo da força", "Comércio", "Pensamento", "Amor"], cor: 0 },
            { id: "HUM-SOC-024", cat: "Humanas", sub: "Sociologia", txt: "Alienção no trabalho (Marx) é:", opt: ["Não se reconhecer no produto", "Trabalhar em outro país", "Ser louco", "Ganhar pouco"], cor: 0 },
            { id: "HUM-SOC-025", cat: "Humanas", sub: "Sociologia", txt: "Burocracia para Weber é:", opt: ["Forma racional de organização", "Papelada inútil", "Corrupção", "Lentidão"], cor: 0 },
            { id: "HUM-SOC-026", cat: "Humanas", sub: "Sociologia", txt: "Solidariedade Orgânica (Durkheim) ocorre em:", opt: ["Sociedades complexas/modernas", "Tribos", "Famílias", "Clãs"], cor: 0 },
            { id: "HUM-SOC-027", cat: "Humanas", sub: "Sociologia", txt: "Habitus (Bourdieu) é:", opt: ["Disposições incorporadas", "Uma roupa de monge", "Um vício", "Um lugar"], cor: 0 },
            { id: "HUM-SOC-028", cat: "Humanas", sub: "Sociologia", txt: "A violência simbólica é:", opt: ["Imposição de significados como legítimos", "Agressão física", "Guerra", "Assalto"], cor: 0 },
            { id: "HUM-SOC-029", cat: "Humanas", sub: "Sociologia", txt: "O Panóptico (Foucault) representa:", opt: ["Vigilância constante", "Liberdade total", "Caos", "Cegueira"], cor: 0 },
            { id: "HUM-SOC-030", cat: "Humanas", sub: "Sociologia", txt: "Sociedade de Consumo foca na:", opt: ["Aquisição de bens", "Poupança", "Produção artesanal", "Troca direta"], cor: 0 },
            { id: "HUM-SOC-031", cat: "Humanas", sub: "Sociologia", txt: "Gentrificação é:", opt: ["Enobrecimento de áreas urbanas (expulsando pobres)", "Criação de favelas", "Plantio de árvores", "Doação de casas"], cor: 0 },
            { id: "HUM-SOC-032", cat: "Humanas", sub: "Sociologia", txt: "O feminismo busca:", opt: ["Igualdade de direitos", "Superioridade feminina", "Odiar homens", "Acabar com a família"], cor: 0 },
            { id: "HUM-SOC-033", cat: "Humanas", sub: "Sociologia", txt: "Cidadania envolve:", opt: ["Direitos e Deveres", "Apenas voto", "Ter passaporte", "Morar na cidade"], cor: 0 },
            { id: "HUM-SOC-034", cat: "Humanas", sub: "Sociologia", txt: "Movimento Sem Terra (MST) luta por:", opt: ["Reforma Agrária", "Casas na cidade", "Fim do agronegócio", "Comunismo"], cor: 0 },
            { id: "HUM-SOC-035", cat: "Humanas", sub: "Sociologia", txt: "A 'Casa Grande & Senzala' analisa a:", opt: ["Formação da sociedade brasileira", "Arquitetura colonial", "Economia do ouro", "Literatura"], cor: 0 },
            { id: "HUM-SOC-036", cat: "Humanas", sub: "Sociologia", txt: "Sincretismo religioso é:", opt: ["Mistura de crenças", "Ateísmo", "Fanatismo", "Guerra santa"], cor: 0 },
            { id: "HUM-SOC-037", cat: "Humanas", sub: "Sociologia", txt: "O Jeitinho Brasileiro é visto como:", opt: ["Burlar normas informalmente", "Crime grave", "Virtude ética", "Lei oficial"], cor: 0 },
            { id: "HUM-SOC-038", cat: "Humanas", sub: "Sociologia", txt: "A Constituição de 1988 é chamada de:", opt: ["Cidadã", "Polaca", "Outorgada", "Militar"], cor: 0 },
            { id: "HUM-SOC-039", cat: "Humanas", sub: "Sociologia", txt: "Preconceito é uma:", opt: ["Opinião pré-formada sem conhecimento", "Verdade científica", "Lei natural", "Escolha racional"], cor: 0 },
            { id: "HUM-SOC-040", cat: "Humanas", sub: "Sociologia", txt: "Discriminação é:", opt: ["Ato/comportamento de exclusão", "Pensamento", "Sentimento", "Teoria"], cor: 0 },
            { id: "HUM-SOC-041", cat: "Humanas", sub: "Sociologia", txt: "Socialização primária ocorre na:", opt: ["Família", "Escola", "Empresa", "Política"], cor: 0 },
            { id: "HUM-SOC-042", cat: "Humanas", sub: "Sociologia", txt: "Controle Social serve para:", opt: ["Manter a ordem e normas", "Prender todos", "Liberar tudo", "Aumentar crimes"], cor: 0 },
            { id: "HUM-SOC-043", cat: "Humanas", sub: "Sociologia", txt: "Desvio social é o comportamento que:", opt: ["Foge das normas aceitas", "Segue as regras", "É elogiado", "É neutro"], cor: 0 },
            { id: "HUM-SOC-044", cat: "Humanas", sub: "Sociologia", txt: "Estigma (Goffman) é uma marca que:", opt: ["Desqualifica o indivíduo socialmente", "Elogia", "Promove", "Enriquece"], cor: 0 },
            { id: "HUM-SOC-045", cat: "Humanas", sub: "Sociologia", txt: "Instituições Totais (prisões, manicômios) controlam:", opt: ["Todos os aspectos da vida do interno", "Apenas o trabalho", "Apenas o sono", "Nada"], cor: 0 },
            { id: "HUM-SOC-046", cat: "Humanas", sub: "Sociologia", txt: "Fordismo caracteriza-se pela:", opt: ["Linha de montagem e produção em massa", "Produção artesanal", "Produção sob demanda", "Trabalho remoto"], cor: 0 },
            { id: "HUM-SOC-047", cat: "Humanas", sub: "Sociologia", txt: "Taylorismo foca na:", opt: ["Eficiência e controle do tempo", "Criatividade", "Liberdade do operário", "Preguiça"], cor: 0 },
            { id: "HUM-SOC-048", cat: "Humanas", sub: "Sociologia", txt: "Toyotismo (Just-in-Time) produz:", opt: ["De acordo com a demanda", "Para estoque", "Em massa sem parar", "Sem qualidade"], cor: 0 },
            { id: "HUM-SOC-049", cat: "Humanas", sub: "Sociologia", txt: "O Precariado é uma classe com:", opt: ["Trabalho instável e sem direitos", "Estabilidade total", "Altos salários", "Poder político"], cor: 0 },
            { id: "HUM-SOC-050", cat: "Humanas", sub: "Sociologia", txt: "Uberização do trabalho refere-se a:", opt: ["Trabalho por aplicativos sem vínculo", "Trabalho em táxi", "Transporte público", "Carros voadores"], cor: 0 },
            { id: "HUM-SOC-051", cat: "Humanas", sub: "Sociologia", txt: "Mobilidade Social é a mudança de:", opt: ["Posição na hierarquia social", "Cidade", "Carro", "Roupa"], cor: 0 },
            { id: "HUM-SOC-052", cat: "Humanas", sub: "Sociologia", txt: "O sistema de Castas na Índia é baseado em:", opt: ["Hereditariedade e religião", "Dinheiro", "Mérito", "Sorte"], cor: 0 },
            { id: "HUM-SOC-053", cat: "Humanas", sub: "Sociologia", txt: "Racismo Estrutural é aquele que:", opt: ["Está enraizado nas práticas sociais e instituições", "Acontece raramente", "É individual", "Não existe"], cor: 0 },
            { id: "HUM-SOC-054", cat: "Humanas", sub: "Sociologia", txt: "Ações Afirmativas (Cotas) visam:", opt: ["Corrigir desigualdades históricas", "Prejudicar", "Segregar", "Punir"], cor: 0 },
            { id: "HUM-SOC-055", cat: "Humanas", sub: "Sociologia", txt: "Identidade de Gênero é:", opt: ["Como a pessoa se sente/identifica", "O órgão genital", "A roupa", "A genética"], cor: 0 },
            { id: "HUM-SOC-056", cat: "Humanas", sub: "Sociologia", txt: "Secularização é o processo de:", opt: ["Perda de influência da religião na vida pública", "Aumento da fé", "Criação de seitas", "Fim da ciência"], cor: 0 },
            { id: "HUM-SOC-057", cat: "Humanas", sub: "Sociologia", txt: "Fundamentalismo religioso prega a:", opt: ["Interpretação literal e rigorosa dos textos", "Liberdade total", "Ciência acima de tudo", "Mudança constante"], cor: 0 },
            { id: "HUM-SOC-058", cat: "Humanas", sub: "Sociologia", txt: "Consumismo é o consumo:", opt: ["Exagerado e desnecessário", "Básico para viver", "Consciente", "De alimentos apenas"], cor: 0 },
            { id: "HUM-SOC-059", cat: "Humanas", sub: "Sociologia", txt: "Sustentabilidade busca equilibrar:", opt: ["Social, Econômico e Ambiental", "Lucro e Gasto", "Passado e Futuro", "Ricos e Pobres"], cor: 0 },
            { id: "HUM-SOC-060", cat: "Humanas", sub: "Sociologia", txt: "Exclusão Digital afeta quem:", opt: ["Não tem acesso à tecnologia/internet", "Não gosta de jogos", "Não tem TV", "Usa muito o celular"], cor: 0 },
            { id: "HUM-SOC-061", cat: "Humanas", sub: "Sociologia", txt: "Coesão Social é:", opt: ["O que mantém a sociedade unida", "Uma cola", "Uma briga", "Uma lei"], cor: 0 },
            { id: "HUM-SOC-062", cat: "Humanas", sub: "Sociologia", txt: "A Divisão Social do Trabalho gera:", opt: ["Interdependência", "Isolamento", "Autossuficiência", "Guerra"], cor: 0 },
            { id: "HUM-SOC-063", cat: "Humanas", sub: "Sociologia", txt: "O Feticismo da Mercadoria (Marx) é:", opt: ["Dar vida/poder às coisas e esquecer quem produziu", "Gostar de comprar", "Adorar estátuas", "Colecionar itens"], cor: 0 },
            { id: "HUM-SOC-064", cat: "Humanas", sub: "Sociologia", txt: "A 'Jaula de Ferro' de Weber refere-se à:", opt: ["Racionalização e burocratização da vida", "Prisão real", "Indústria metalúrgica", "Liberdade total"], cor: 0 },
            { id: "HUM-SOC-065", cat: "Humanas", sub: "Sociologia", txt: "Características do Fato Social (Durkheim):", opt: ["Coercitividade, Exterioridade, Generalidade", "Individualidade, Liberdade, Amor", "Caos, Desordem, Medo", "Lei, Ordem, Progresso"], cor: 0 },
            { id: "HUM-SOC-066", cat: "Humanas", sub: "Sociologia", txt: "Capital Cultural (Bourdieu) envolve:", opt: ["Conhecimentos, diplomas e gostos", "Dinheiro no banco", "Máquinas e terras", "Amigos políticos"], cor: 0 },
            { id: "HUM-SOC-067", cat: "Humanas", sub: "Sociologia", txt: "A 'Distinção' social ocorre através do:", opt: ["Gosto e consumo cultural", "Uso da força", "Voto", "Trabalho braçal"], cor: 0 },
            { id: "HUM-SOC-068", cat: "Humanas", sub: "Sociologia", txt: "Estigma (Goffman) pode ser:", opt: ["Físico, de caráter ou tribal", "Apenas físico", "Apenas religioso", "Positivo"], cor: 0 },
            { id: "HUM-SOC-069", cat: "Humanas", sub: "Sociologia", txt: "Exemplo de Instituição Total:", opt: ["Prisão ou Convento", "Shopping", "Praça", "Internet"], cor: 0 },
            { id: "HUM-SOC-070", cat: "Humanas", sub: "Sociologia", txt: "Amor Líquido (Bauman) caracteriza-se por:", opt: ["Laços frágeis e passageiros", "Casamentos de 50 anos", "Fidelidade absoluta", "Amor à distância"], cor: 0 },
            { id: "HUM-SOC-071", cat: "Humanas", sub: "Sociologia", txt: "A Sociedade em Rede (Castells) é baseada na:", opt: ["Informação e Tecnologia", "Agricultura", "Indústria Pesada", "Religião"], cor: 0 },
            { id: "HUM-SOC-072", cat: "Humanas", sub: "Sociologia", txt: "Sociedade de Risco (Ulrich Beck) lida com:", opt: ["Riscos globais criados pela modernidade (nuclear, ambiental)", "Riscos naturais apenas", "Risco de cair", "Risco financeiro"], cor: 0 },
            { id: "HUM-SOC-073", cat: "Humanas", sub: "Sociologia", txt: "Aldeia Global (McLuhan) refere-se à:", opt: ["Conexão mundial pela mídia", "Uma vila pequena", "Volta ao campo", "Fim das cidades"], cor: 0 },
            { id: "HUM-SOC-074", cat: "Humanas", sub: "Sociologia", txt: "Multiculturalismo defende a:", opt: ["Convivência de diversas culturas", "Imposição de uma cultura", "Guerra entre culturas", "Separação total"], cor: 0 },
            { id: "HUM-SOC-075", cat: "Humanas", sub: "Sociologia", txt: "Apropriação Cultural é:", opt: ["Uso de elementos de uma cultura oprimida por dominantes", "Aprender outra língua", "Comer comida estrangeira", "Viajar"], cor: 0 },
            { id: "HUM-SOC-076", cat: "Humanas", sub: "Sociologia", txt: "Fake News prosperam na era da:", opt: ["Pós-Verdade", "Verdade Absoluta", "Ciência", "Iluminismo"], cor: 0 },
            { id: "HUM-SOC-077", cat: "Humanas", sub: "Sociologia", txt: "Capitalismo de Vigilância lucra com:", opt: ["Dados comportamentais dos usuários", "Venda de câmeras", "Segurança privada", "Espionagem militar"], cor: 0 },
            { id: "HUM-SOC-078", cat: "Humanas", sub: "Sociologia", txt: "Novos Movimentos Sociais focam em:", opt: ["Identidade e Cultura (Gênero, Raça, Meio Ambiente)", "Salário apenas", "Revolução armada", "Voto apenas"], cor: 0 },
            { id: "HUM-SOC-079", cat: "Humanas", sub: "Sociologia", txt: "ONGs (Terceiro Setor) atuam onde:", opt: ["O Estado e o Mercado falham", "Onde há lucro", "Apenas em guerras", "No governo"], cor: 0 },
            { id: "HUM-SOC-080", cat: "Humanas", sub: "Sociologia", txt: "Desobediência Civil é:", opt: ["Quebrar leis injustas pacificamente", "Crime violento", "Não pagar imposto por preguiça", "Fugir da polícia"], cor: 0 },
            { id: "HUM-SOC-081", cat: "Humanas", sub: "Sociologia", txt: "A 'Sociedade do Espetáculo' (Guy Debord) foca na:", opt: ["Imagem e aparência", "Realidade crua", "Tradição", "Leitura"], cor: 0 },
            { id: "HUM-SOC-082", cat: "Humanas", sub: "Sociologia", txt: "O termo 'Aldeia Global' sugere que:", opt: ["O mundo está interconectado", "Todos moram em aldeias", "O mundo é pequeno", "Não há cidades"], cor: 0 },
            { id: "HUM-SOC-083", cat: "Humanas", sub: "Sociologia", txt: "Aporofobia é o medo/rejeição aos:", opt: ["Pobres", "Ricos", "Estrangeiros", "Doentes"], cor: 0 },
            { id: "HUM-SOC-084", cat: "Humanas", sub: "Sociologia", txt: "Nepotismo é:", opt: ["Favorecer parentes em cargos públicos", "Roubar dinheiro", "Ser honesto", "Pagar impostos"], cor: 0 },
            { id: "HUM-SOC-085", cat: "Humanas", sub: "Sociologia", txt: "Cleptocracia é um governo de:", opt: ["Ladrões", "Sábios", "Ricos", "Pobres"], cor: 0 },
            { id: "HUM-SOC-086", cat: "Humanas", sub: "Sociologia", txt: "Plutocracia é o governo dos:", opt: ["Ricos", "Pobres", "Militares", "Religiosos"], cor: 0 },
            { id: "HUM-SOC-087", cat: "Humanas", sub: "Sociologia", txt: "Teocracia é o governo baseado em:", opt: ["Religião/Deus", "Povo", "Rei", "Dinheiro"], cor: 0 },
            { id: "HUM-SOC-088", cat: "Humanas", sub: "Sociologia", txt: "Demagogia é:", opt: ["Manipular o povo com falsas promessas", "Falar a verdade", "Governar bem", "Estudar o povo"], cor: 0 },
            { id: "HUM-SOC-089", cat: "Humanas", sub: "Sociologia", txt: "O 'Homem Cordial' age movido pela:", opt: ["Emoção/Coração (não pela razão)", "Razão fria", "Lei", "Violência"], cor: 0 },
            { id: "HUM-SOC-090", cat: "Humanas", sub: "Sociologia", txt: "Florestan Fernandes estudou a:", opt: ["Integração do negro na sociedade de classes", "Culinária", "Música", "Arquitetura"], cor: 0 },
            { id: "HUM-SOC-091", cat: "Humanas", sub: "Sociologia", txt: "Darcy Ribeiro focou nos estudos sobre:", opt: ["Povos indígenas e educação", "Economia", "Europa", "Ásia"], cor: 0 },
            { id: "HUM-SOC-092", cat: "Humanas", sub: "Sociologia", txt: "O mito da 'Democracia Racial' diz que:", opt: ["Não há racismo no Brasil (falso)", "Há muito racismo", "Somos todos iguais na lei", "O Brasil é racista"], cor: 0 },
            { id: "HUM-SOC-093", cat: "Humanas", sub: "Sociologia", txt: "Patrimonialismo é:", opt: ["Confundir o público com o privado", "Cuidar do patrimônio", "Ser rico", "Ter terras"], cor: 0 },
            { id: "HUM-SOC-094", cat: "Humanas", sub: "Sociologia", txt: "Coronelismo foi marcante na:", opt: ["República Velha", "Era Vargas", "Ditadura", "Hoje"], cor: 0 },
            { id: "HUM-SOC-095", cat: "Humanas", sub: "Sociologia", txt: "Luta de Classes ocorre entre:", opt: ["Burguesia e Proletariado", "Homem e Mulher", "Adulto e Criança", "Cidade e Campo"], cor: 0 },
            { id: "HUM-SOC-096", cat: "Humanas", sub: "Sociologia", txt: "Mais-Valia Relativa aumenta o lucro por meio da:", opt: ["Tecnologia/Produtividade", "Aumento da jornada", "Roubo", "Imposto"], cor: 0 },
            { id: "HUM-SOC-097", cat: "Humanas", sub: "Sociologia", txt: "Indústria Cultural transforma arte em:", opt: ["Mercadoria de consumo", "Obra prima", "Educação", "Religião"], cor: 0 },
            { id: "HUM-SOC-098", cat: "Humanas", sub: "Sociologia", txt: "Pan-africanismo defende a:", opt: ["União dos povos africanos", "Divisão da África", "Colonização", "Guerra tribal"], cor: 0 },
            { id: "HUM-SOC-099", cat: "Humanas", sub: "Sociologia", txt: "Feminicídio é:", opt: ["Homicídio de mulher por condição de gênero", "Qualquer morte de mulher", "Acidente", "Suicídio"], cor: 0 },
            { id: "HUM-SOC-100", cat: "Humanas", sub: "Sociologia", txt: "O IDH brasileiro é prejudicado principalmente pela:", opt: ["Desigualdade de renda/Educação", "Falta de água", "Falta de sol", "Preguiça"], cor: 0 },
             
        
];
