export const questoes = [
 
            // --- SUB: ARTES ---
            { id: "LIN-ART-001", cat: "Linguagens", sub: "Artes", txt: "Picasso é o ícone do:", opt: ["Surrealismo", "Cubismo", "Impressionismo", "Dadaísmo"], cor: 1 },
            { id: "LIN-ART-002", cat: "Linguagens", sub: "Artes", txt: "Tarsila do Amaral pintou o:", opt: ["Abaporu", "Grito", "Monalisa", "Noite Estrelada"], cor: 0 },
            { id: "LIN-ART-003", cat: "Linguagens", sub: "Artes", txt: "O Impressionismo foca na:", opt: ["Luz e cor do momento", "Forma geométrica", "Tristeza", "História"], cor: 0 },
            { id: "LIN-ART-004", cat: "Linguagens", sub: "Artes", txt: "Salvador Dalí é o ícone do:", opt: ["Surrealismo", "Cubismo", "Realismo", "Barroco"], cor: 0 },
            { id: "LIN-ART-005", cat: "Linguagens", sub: "Artes", txt: "Cândido Portinari retratou muito:", opt: ["A realidade social do Brasil (Retirantes)", "Reis e Rainhas", "Paisagens europeias", "Abstracionismo"], cor: 0 },
            { id: "LIN-ART-006", cat: "Linguagens", sub: "Artes", txt: "Frida Kahlo é famosa por seus:", opt: ["Autorretratos", "Prédios", "Esculturas", "Filmes"], cor: 0 },
            { id: "LIN-ART-007", cat: "Linguagens", sub: "Artes", txt: "O Renascimento valorizava:", opt: ["A perspectiva e o humanismo", "A arte plana", "O medo de Deus", "O abstrato"], cor: 0 },
            { id: "LIN-ART-008", cat: "Linguagens", sub: "Artes", txt: "Aleijadinho foi o mestre do:", opt: ["Barroco Mineiro", "Modernismo", "Gótico", "Rococó Francês"], cor: 0 },
            { id: "LIN-ART-009", cat: "Linguagens", sub: "Artes", txt: "Anita Malfatti foi precursora do:", opt: ["Modernismo no Brasil", "Romantismo", "Academia", "Cinema"], cor: 0 },
            { id: "LIN-ART-010", cat: "Linguagens", sub: "Artes", txt: "Van Gogh pintou:", opt: ["A Noite Estrelada", "Guernica", "A Última Ceia", "O Beijo"], cor: 0 },
            { id: "LIN-ART-011", cat: "Linguagens", sub: "Artes", txt: "Romero Britto usa estilo:", opt: ["Pop Art (cores vibrantes/geométrico)", "Sombrio", "Renapascentista", "Gótico"], cor: 0 },
            { id: "LIN-ART-012", cat: "Linguagens", sub: "Artes", txt: "O Cubismo (Picasso) usa:", opt: ["Formas geométricas para decompor a imagem", "Sonhos", "Luz solar", "Pontilhismo"], cor: 0 },
            { id: "LIN-ART-013", cat: "Linguagens", sub: "Artes", txt: "A Vênus de Milo é uma:", opt: ["Escultura grega sem braços", "Pintura", "Música", "Cidade"], cor: 0 },
            { id: "LIN-ART-014", cat: "Linguagens", sub: "Artes", txt: "Grafite é considerado:", opt: ["Arte urbana", "Vandalismo apenas", "Pintura a óleo", "Escultura"], cor: 0 },
            { id: "LIN-ART-015", cat: "Linguagens", sub: "Artes", txt: "O Oscar Niemeyer foi um:", opt: ["Arquiteto modernista", "Pintor", "Músico", "Escritor"], cor: 0 },
            { id: "LIN-ART-016", cat: "Linguagens", sub: "Artes", txt: "A Arte Contemporânea caracteriza-se pela:", opt: ["Liberdade de materiais e interação", "Rigidez", "Cópia do real", "Uso só de tinta"], cor: 0 },
            { id: "LIN-ART-017", cat: "Linguagens", sub: "Artes", txt: "Pop Art criticava:", opt: ["O consumismo e a cultura de massa", "A religião", "A política antiga", "A natureza"], cor: 0 },
            { id: "LIN-ART-018", cat: "Linguagens", sub: "Artes", txt: "Andy Warhol pintou:", opt: ["Latas de Sopa Campbell e Marilyn Monroe", "Monalisa", "Abaporu", "Céu estrelado"], cor: 0 },
            { id: "LIN-ART-019", cat: "Linguagens", sub: "Artes", txt: "O Dadaísmo era um movimento:", opt: ["De negação da arte e do sentido", "De beleza pura", "De regras estritas", "Religioso"], cor: 0 },
            { id: "LIN-ART-020", cat: "Linguagens", sub: "Artes", txt: "Duchamp criou o 'Urinol', que é um:", opt: ["Ready-made", "Afresco", "Mosaico", "Retrato"], cor: 0 },
            { id: "LIN-ART-021", cat: "Linguagens", sub: "Artes", txt: "A Arte Gótica é famosa pelos:", opt: ["Vitrais e Catedrais altas", "Templos baixos", "Pirâmides", "Cavernas"], cor: 0 },
            { id: "LIN-ART-022", cat: "Linguagens", sub: "Artes", txt: "Performance Art envolve:", opt: ["O corpo do artista e ação ao vivo", "Apenas pintura", "Escultura em mármore", "Desenho técnico"], cor: 0 },
            { id: "LIN-ART-023", cat: "Linguagens", sub: "Artes", txt: "Instalação artística é:", opt: ["Ocupação de um espaço com elementos", "Um quadro na parede", "Um livro", "Uma música"], cor: 0 },
            { id: "LIN-ART-024", cat: "Linguagens", sub: "Artes", txt: "Expressionismo (O Grito) foca na:", opt: ["Deformação da realidade pela emoção", "Cópia da natureza", "Luz solar", "Geometria"], cor: 0 },
            { id: "LIN-ART-025", cat: "Linguagens", sub: "Artes", txt: "Arte Rupestre é:", opt: ["Feita em cavernas na pré-história", "Feita em computadores", "Feita em telas", "Feita em igrejas"], cor: 0 },
            { id: "LIN-ART-026", cat: "Linguagens", sub: "Artes", txt: "O Mosaico era muito usado na arte:", opt: ["Bizantina", "Moderna", "Rupestre", "Egípcia"], cor: 0 },
            { id: "LIN-ART-027", cat: "Linguagens", sub: "Artes", txt: "Michelangelo pintou o teto da:", opt: ["Capela Sistina", "Catedral de Notre Dame", "Igreja da Pampulha", "Sagrada Família"], cor: 0 },
            { id: "LIN-ART-028", cat: "Linguagens", sub: "Artes", txt: "O Chiaroscuro (luz e sombra) é técnica do:", opt: ["Barroco", "Gótico", "Cubismo", "Abstracionismo"], cor: 0 },
            { id: "LIN-ART-029", cat: "Linguagens", sub: "Artes", txt: "O Rococó é um estilo:", opt: ["Decorativo, leve e elegante", "Sombrio", "Pesado", "Geométrico"], cor: 0 },
            { id: "LIN-ART-030", cat: "Linguagens", sub: "Artes", txt: "O Neoclassicismo retomou valores da:", opt: ["Grécia e Roma Antigas", "Idade Média", "Pré-História", "África"], cor: 0 },
            { id: "LIN-ART-031", cat: "Linguagens", sub: "Artes", txt: "Monet é o principal nome do:", opt: ["Impressionismo", "Expressionismo", "Surrealismo", "Futurismo"], cor: 0 },
            { id: "LIN-ART-032", cat: "Linguagens", sub: "Artes", txt: "O Pontilhismo usa:", opt: ["Pontos de cor pura", "Linhas retas", "Manchas pretas", "Colagem"], cor: 0 },
            { id: "LIN-ART-033", cat: "Linguagens", sub: "Artes", txt: "O Fauvismo usava cores:", opt: ["Puras, vibrantes e arbitrárias", "Tons pastéis", "Preto e branco", "Cinzas"], cor: 0 },
            { id: "LIN-ART-034", cat: "Linguagens", sub: "Artes", txt: "Kandinsky é o pai do:", opt: ["Abstracionismo", "Realismo", "Dadaísmo", "Pop Art"], cor: 0 },
            { id: "LIN-ART-035", cat: "Linguagens", sub: "Artes", txt: "A Bauhaus foi uma escola de:", opt: ["Design e Arquitetura", "Música", "Dança", "Culinária"], cor: 0 },
            { id: "LIN-ART-036", cat: "Linguagens", sub: "Artes", txt: "Lygia Clark criou os:", opt: ["Bichos (esculturas interativas)", "Retirantes", "Relógios derretidos", "Girassóis"], cor: 0 },
            { id: "LIN-ART-037", cat: "Linguagens", sub: "Artes", txt: "Vik Muniz faz arte com:", opt: ["Lixo e materiais inusitados", "Ouro", "Mármore", "Bronze"], cor: 0 },
            { id: "LIN-ART-038", cat: "Linguagens", sub: "Artes", txt: "Hélio Oiticica criou o:", opt: ["Parangolé", "Abaporu", "Cristo Redentor", "Masp"], cor: 0 },
            { id: "LIN-ART-039", cat: "Linguagens", sub: "Artes", txt: "A Arte Naïf é caracterizada por:", opt: ["Espontaneidade e autodidatismo", "Regras acadêmicas", "Uso de computador", "Falta de cor"], cor: 0 },
            { id: "LIN-ART-040", cat: "Linguagens", sub: "Artes", txt: "Banksy é famoso por seu:", opt: ["Grafite com crítica social", "Trabalho em museus", "Filme de ação", "Livro de romance"], cor: 0 },
            { id: "LIN-ART-041", cat: "Linguagens", sub: "Artes", txt: "O Samba originou-se no:", opt: ["Rio de Janeiro (com raízes africanas)", "São Paulo", "Bahia", "Minas Gerais"], cor: 0 },
            { id: "LIN-ART-042", cat: "Linguagens", sub: "Artes", txt: "A Bossa Nova misturou:", opt: ["Samba e Jazz", "Rock e Forró", "Funk e Soul", "Sertanejo e Pop"], cor: 0 },
            { id: "LIN-ART-043", cat: "Linguagens", sub: "Artes", txt: "Tom Jobim e João Gilberto são ícones da:", opt: ["Bossa Nova", "Jovem Guarda", "Tropicália", "Axé"], cor: 0 },
            { id: "LIN-ART-044", cat: "Linguagens", sub: "Artes", txt: "O Cinema Novo (Glauber Rocha) tinha o lema:", opt: ["Uma câmera na mão e uma ideia na cabeça", "Luz, câmera, ação", "Cinema é diversão", "Hollywood brasileira"], cor: 0 },
            { id: "LIN-ART-045", cat: "Linguagens", sub: "Artes", txt: "A Commedia dell'arte usava:", opt: ["Máscaras e improviso", "Textos rígidos", "Orquestras", "Animais"], cor: 0 },
            { id: "LIN-ART-046", cat: "Linguagens", sub: "Artes", txt: "O Teatro de Revista no Brasil focava em:", opt: ["Humor, música e crítica política", "Tragédia", "Religião", "História antiga"], cor: 0 },
            { id: "LIN-ART-047", cat: "Linguagens", sub: "Artes", txt: "Augusto Boal criou o:", opt: ["Teatro do Oprimido", "Teatro Mágico", "Teatro Oficina", "Teatro de Sombras"], cor: 0 },
            { id: "LIN-ART-048", cat: "Linguagens", sub: "Artes", txt: "O Ballet Clássico surgiu nas cortes da:", opt: ["Itália e França", "Rússia e China", "Brasil e EUA", "Grécia"], cor: 0 },
            { id: "LIN-ART-049", cat: "Linguagens", sub: "Artes", txt: "A Dança Contemporânea valoriza:", opt: ["Liberdade de movimento e expressão", "Passos rígidos", "Uso de sapatilhas", "Roupas iguais"], cor: 0 },
            { id: "LIN-ART-050", cat: "Linguagens", sub: "Artes", txt: "As Cores Primárias (pigmento) são:", opt: ["Azul (Ciano), Vermelho (Magenta), Amarelo", "Verde, Laranja, Roxo", "Preto e Branco", "Azul e Verde"], cor: 0 },
            { id: "LIN-ART-051", cat: "Linguagens", sub: "Artes", txt: "Cores Secundárias surgem da:", opt: ["Mistura de duas primárias", "Mistura com branco", "Mistura com preto", "Natureza"], cor: 0 },
            { id: "LIN-ART-052", cat: "Linguagens", sub: "Artes", txt: "Perspectiva serve para dar ilusão de:", opt: ["Profundidade (3D)", "Cor", "Movimento", "Som"], cor: 0 },
            { id: "LIN-ART-053", cat: "Linguagens", sub: "Artes", txt: "Xilogravura é a técnica de:", opt: ["Gravura em madeira", "Pintura a óleo", "Escultura em pedra", "Foto"], cor: 0 },
            { id: "LIN-ART-054", cat: "Linguagens", sub: "Artes", txt: "O Carnaval brasileiro tem origem:", opt: ["Europeia (Entrudo) e Africana", "Indígena", "Asiática", "Americana"], cor: 0 },
            { id: "LIN-ART-055", cat: "Linguagens", sub: "Artes", txt: "Heitor Villa-Lobos foi um:", opt: ["Compositor erudito brasileiro", "Pintor", "Escritor", "Ator"], cor: 0 },
            { id: "LIN-ART-056", cat: "Linguagens", sub: "Artes", txt: "A 'Semana de 22' ocorreu no:", opt: ["Theatro Municipal de SP", "Museu do Ipiranga", "Copacabana Palace", "Masp"], cor: 0 },
            { id: "LIN-ART-057", cat: "Linguagens", sub: "Artes", txt: "O Maracatu é uma manifestação de:", opt: ["Pernambuco", "Rio de Janeiro", "São Paulo", "Goiás"], cor: 0 },
            { id: "LIN-ART-058", cat: "Linguagens", sub: "Artes", txt: "Capoeira é mistura de:", opt: ["Dança, luta e jogo", "Futebol e vôlei", "Teatro e música", "Religião"], cor: 0 },
            { id: "LIN-ART-059", cat: "Linguagens", sub: "Artes", txt: "O Frevo é uma dança típica de:", opt: ["Pernambuco (com sombrinha)", "Bahia", "Rio", "Amazonas"], cor: 0 },
            { id: "LIN-ART-060", cat: "Linguagens", sub: "Artes", txt: "Aleijadinho esculpia em:", opt: ["Pedra-sabão", "Mármore", "Gelo", "Ferro"], cor: 0 },
            { id: "LIN-ART-061", cat: "Linguagens", sub: "Artes", txt: "O Samba-Enredo é a música das:", opt: ["Escolas de Samba", "Festas Juninas", "Igrejas", "Raves"], cor: 0 },
            { id: "LIN-ART-062", cat: "Linguagens", sub: "Artes", txt: "Hélio Oiticica é um dos pais da:", opt: ["Tropicália e Arte Ambiental", "Bossa Nova", "Pintura a óleo", "Arquitetura"], cor: 0 },
            { id: "LIN-ART-063", cat: "Linguagens", sub: "Artes", txt: "Arte Cinética é aquela que:", opt: ["Tem movimento (ou ilusão de)", "É parada", "É digital", "É sonora"], cor: 0 },
            { id: "LIN-ART-064", cat: "Linguagens", sub: "Artes", txt: "Land Art utiliza:", opt: ["A própria natureza como suporte", "Telas", "Computadores", "Prédios"], cor: 0 },
            { id: "LIN-ART-065", cat: "Linguagens", sub: "Artes", txt: "Op Art cria ilusões de:", opt: ["Ótica/Vibração", "Som", "Tato", "Olfato"], cor: 0 },
            { id: "LIN-ART-066", cat: "Linguagens", sub: "Artes", txt: "A Perspectiva Linear foi dominada no:", opt: ["Renascimento", "Gótico", "Egito Antigo", "Barroco"], cor: 0 },
            { id: "LIN-ART-067", cat: "Linguagens", sub: "Artes", txt: "O Barroco valoriza a:", opt: ["Emoção e Dramatismo", "Razão", "Calma", "Linha reta"], cor: 0 },
            { id: "LIN-ART-068", cat: "Linguagens", sub: "Artes", txt: "O Rococó é conhecido por:", opt: ["Conchas, tons pastéis e leveza", "Escuridão", "Formas quadradas", "Violência"], cor: 0 },
            { id: "LIN-ART-069", cat: "Linguagens", sub: "Artes", txt: "O Neoclassicismo inspira-se na:", opt: ["Razão e antiguidade clássica", "Fé", "Emoção descontrolada", "Natureza selvagem"], cor: 0 },
            { id: "LIN-ART-070", cat: "Linguagens", sub: "Artes", txt: "Goya foi um pintor do:", opt: ["Romantismo (fase negra)", "Renascimento", "Pop Art", "Futurismo"], cor: 0 },
            { id: "LIN-ART-071", cat: "Linguagens", sub: "Artes", txt: "Courbet (Realismo) pintava:", opt: ["Trabalhadores e o cotidiano real", "Anjos", "Reis", "Deuses"], cor: 0 },
            { id: "LIN-ART-072", cat: "Linguagens", sub: "Artes", txt: "Monet pintava ao ar livre para captar a:", opt: ["Luz natural", "História", "Alma", "Geometria"], cor: 0 },
            { id: "LIN-ART-073", cat: "Linguagens", sub: "Artes", txt: "Van Gogh cortou a própria:", opt: ["Orelha", "Mão", "Perna", "Nariz"], cor: 0 },
            { id: "LIN-ART-074", cat: "Linguagens", sub: "Artes", txt: "Munch pintou 'O Grito' expressando:", opt: ["Angústia existencial", "Alegria", "Fome", "Sono"], cor: 0 },
            { id: "LIN-ART-075", cat: "Linguagens", sub: "Artes", txt: "Picasso e Braque criaram o:", opt: ["Cubismo", "Fauvismo", "Dadaísmo", "Surrealismo"], cor: 0 },
            { id: "LIN-ART-076", cat: "Linguagens", sub: "Artes", txt: "O Futurismo adorava a:", opt: ["Velocidade e a máquina", "Calma", "Natureza", "Mulher"], cor: 0 },
            { id: "LIN-ART-077", cat: "Linguagens", sub: "Artes", txt: "Dadaísmo significa:", opt: ["Nada (Nonsense)", "Tudo", "Pai", "Arte"], cor: 0 },
            { id: "LIN-ART-078", cat: "Linguagens", sub: "Artes", txt: "Surrealismo foi influenciado pela:", opt: ["Psicanálise (Freud/Sonhos)", "Matemática", "Biologia", "Política"], cor: 0 },
            { id: "LIN-ART-079", cat: "Linguagens", sub: "Artes", txt: "Roy Lichtenstein (Pop Art) imitava:", opt: ["Histórias em Quadrinhos (HQ)", "Fotos", "Jornais", "TV"], cor: 0 },
            { id: "LIN-ART-080", cat: "Linguagens", sub: "Artes", txt: "Arte Conceitual diz que a ideia é:", opt: ["Mais importante que a obra física", "Menos importante", "Irrelevante", "Vendível"], cor: 0 },
            { id: "LIN-ART-081", cat: "Linguagens", sub: "Artes", txt: "Di Cavalcanti pintava:", opt: ["Mulheres mestiças e o samba", "Paisagens europeias", "Abstrato", "Guerra"], cor: 0 },
            { id: "LIN-ART-082", cat: "Linguagens", sub: "Artes", txt: "Portinari pintou a série:", opt: ["Os Retirantes", "Os Girassóis", "As Meninas", "Os Relógios"], cor: 0 },
            { id: "LIN-ART-083", cat: "Linguagens", sub: "Artes", txt: "O MAM e o MASP são:", opt: ["Museus de Arte", "Escolas", "Hospitais", "Lojas"], cor: 0 },
            { id: "LIN-ART-084", cat: "Linguagens", sub: "Artes", txt: "Sebastião Salgado é famoso pela:", opt: ["Fotografia social (preto e branco)", "Pintura", "Escultura", "Dança"], cor: 0 },
            { id: "LIN-ART-085", cat: "Linguagens", sub: "Artes", txt: "O Funk Carioca deriva do:", opt: ["Miami Bass", "Jazz", "Rock", "Samba"], cor: 0 },
            { id: "LIN-ART-086", cat: "Linguagens", sub: "Artes", txt: "Hip Hop inclui 4 elementos: DJ, MC, Break e:", opt: ["Grafite", "Skate", "Samba", "Violão"], cor: 0 },
            { id: "LIN-ART-087", cat: "Linguagens", sub: "Artes", txt: "A Pixaçao é diferente do Grafite pois:", opt: ["Foca na tipografia/risco e é ilegal", "É desenho colorido", "É feita em tela", "É autorizada"], cor: 0 },
            { id: "LIN-ART-088", cat: "Linguagens", sub: "Artes", txt: "O Bumba-meu-boi é festa do:", opt: ["Maranhão/Nordeste", "Sul", "Sudeste", "Acre"], cor: 0 },
            { id: "LIN-ART-089", cat: "Linguagens", sub: "Artes", txt: "O Festival de Parintins disputa:", opt: ["Boi Caprichoso e Garantido", "Fla x Flu", "Samba x Pagode", "Norte x Sul"], cor: 0 },
            { id: "LIN-ART-090", cat: "Linguagens", sub: "Artes", txt: "A cerâmica Marajoara é arte:", opt: ["Indígena", "Europeia", "Africana", "Moderna"], cor: 0 },
            { id: "LIN-ART-091", cat: "Linguagens", sub: "Artes", txt: "O Mestre Vitalino fazia:", opt: ["Bonecos de barro (Nordeste)", "Pinturas a óleo", "Jóias", "Roupas"], cor: 0 },
            { id: "LIN-ART-092", cat: "Linguagens", sub: "Artes", txt: "A sigla MPB significa:", opt: ["Música Popular Brasileira", "Música Para Bailar", "Muito Povo Bom", "Música Pretas Brasil"], cor: 0 },
            { id: "LIN-ART-093", cat: "Linguagens", sub: "Artes", txt: "Chico Buarque é famoso pelas letras de:", opt: ["Protesto e poéticas", "Humor", "Religiosas", "Infantis"], cor: 0 },
            { id: "LIN-ART-094", cat: "Linguagens", sub: "Artes", txt: "A Jovem Guarda foi liderada por:", opt: ["Roberto Carlos", "Gilberto Gil", "Caetano", "Chico"], cor: 0 },
            { id: "LIN-ART-095", cat: "Linguagens", sub: "Artes", txt: "O Rock in Rio começou em:", opt: ["1985", "1990", "2000", "1970"], cor: 0 },
            { id: "LIN-ART-096", cat: "Linguagens", sub: "Artes", txt: "Frida Kahlo nasceu no:", opt: ["México", "Espanha", "Brasil", "Peru"], cor: 0 },
            { id: "LIN-ART-097", cat: "Linguagens", sub: "Artes", txt: "Diego Rivera fazia:", opt: ["Muralismo", "Miniaturas", "Joias", "Origami"], cor: 0 },
            { id: "LIN-ART-098", cat: "Linguagens", sub: "Artes", txt: "Botero (Colômbia) pinta figuras:", opt: ["Volumosas/Gordas", "Magras", "Abstratas", "Invisíveis"], cor: 0 },
            { id: "LIN-ART-099", cat: "Linguagens", sub: "Artes", txt: "O 'Abaporu' significa em tupi:", opt: ["Homem que come gente", "Pé grande", "Sol forte", "Cacto"], cor: 0 },
            { id: "LIN-ART-100", cat: "Linguagens", sub: "Artes", txt: "A 7ª Arte é o:", opt: ["Cinema", "Teatro", "Dança", "Circo"], cor: 0 },


];
