export const questoes = [

            // --- SUB: ESPANHOL ---
            { id: "LIN-ESP-001", cat: "Linguagens", sub: "Espanhol", txt: "'Apellido' em espanhol significa:", opt: ["Apelido", "Sobrenome", "Nome", "Rua"], cor: 1 },
            { id: "LIN-ESP-002", cat: "Linguagens", sub: "Espanhol", txt: "'Rojo' em espanhol é a cor:", opt: ["Roxo", "Rosa", "Vermelho", "Laranja"], cor: 2 },
            { id: "LIN-ESP-003", cat: "Linguagens", sub: "Espanhol", txt: "'Coche' significa:", opt: ["Cocheiro", "Carro", "Colher", "Cachorro"], cor: 1 },
            { id: "LIN-ESP-004", cat: "Linguagens", sub: "Espanhol", txt: "'Embarazada' significa:", opt: ["Grávida", "Envergonhada", "Presa", "Barata"], cor: 0 },
            { id: "LIN-ESP-005", cat: "Linguagens", sub: "Espanhol", txt: "'Exquisito' geralmente significa:", opt: ["Delicioso/Saboroso", "Esquisito", "Feio", "Estranho"], cor: 0 },
            { id: "LIN-ESP-006", cat: "Linguagens", sub: "Espanhol", txt: "'Vaso' significa:", opt: ["Copo", "Vaso de flor", "Privada", "Barco"], cor: 0 },
            { id: "LIN-ESP-007", cat: "Linguagens", sub: "Espanhol", txt: "'Taller' significa:", opt: ["Oficina", "Talher", "Alto", "Tela"], cor: 0 },
            { id: "LIN-ESP-008", cat: "Linguagens", sub: "Espanhol", txt: "'Pelado' em muitos países é:", opt: ["Careca", "Nu", "Pele", "Peixe"], cor: 0 },
            { id: "LIN-ESP-009", cat: "Linguagens", sub: "Espanhol", txt: "'Zurdo' é quem usa a mão:", opt: ["Esquerda (Canhoto)", "Direita", "Surdo", "Dura"], cor: 0 },
            { id: "LIN-ESP-010", cat: "Linguagens", sub: "Espanhol", txt: "'Desayuno' é:", opt: ["Café da manhã", "Desanimo", "Jantar", "Almoço"], cor: 0 },
            { id: "LIN-ESP-011", cat: "Linguagens", sub: "Espanhol", txt: "'Cena' significa:", opt: ["Jantar", "Cena de filme", "Sinal", "Cinza"], cor: 0 },
            { id: "LIN-ESP-012", cat: "Linguagens", sub: "Espanhol", txt: "'Basura' é:", opt: ["Lixo", "Vassoura", "Base", "Bacia"], cor: 0 },
            { id: "LIN-ESP-013", cat: "Linguagens", sub: "Espanhol", txt: "'Oficina' em espanhol significa:", opt: ["Escritório", "Oficina mecânica", "Cozinha", "Loja"], cor: 0 },
            { id: "LIN-ESP-014", cat: "Linguagens", sub: "Espanhol", txt: "'Largo' em espanhol significa:", opt: ["Comprido", "Largo (amplo)", "Grande", "Grosso"], cor: 0 },
            { id: "LIN-ESP-015", cat: "Linguagens", sub: "Espanhol", txt: "'Saco' em espanhol pode ser:", opt: ["Paletó", "Sacola", "Soco", "Sapato"], cor: 0 },
            { id: "LIN-ESP-016", cat: "Linguagens", sub: "Espanhol", txt: "'Polvo' significa:", opt: ["Pó", "Polvo (animal)", "Povo", "Pobre"], cor: 0 },
            { id: "LIN-ESP-017", cat: "Linguagens", sub: "Espanhol", txt: "'Cachorro' significa:", opt: ["Filhote", "Cão adulto", "Porco", "Gato"], cor: 0 },
            { id: "LIN-ESP-018", cat: "Linguagens", sub: "Espanhol", txt: "'Rato' significa:", opt: ["Momento/Instante", "Rato (animal)", "Ratoeira", "Roubo"], cor: 0 },
            { id: "LIN-ESP-019", cat: "Linguagens", sub: "Espanhol", txt: "'Borracha' significa:", opt: ["Bêbada", "Borracha de apagar", "Pneu", "Bota"], cor: 0 },
            { id: "LIN-ESP-020", cat: "Linguagens", sub: "Espanhol", txt: "'Vassoura' em espanhol é:", opt: ["Escoba", "Basura", "Vaso", "Copa"], cor: 0 },
            { id: "LIN-ESP-021", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Taza' significa:", opt: ["Xícara", "Taça", "Tese", "Taxa"], cor: 0 },
            { id: "LIN-ESP-022", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Copa' significa:", opt: ["Taça (de vinho)", "Copa (cozinha)", "Copo", "Capa"], cor: 0 },
            { id: "LIN-ESP-023", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Pastel' significa:", opt: ["Bolo", "Pastel frito", "Pasta", "Pato"], cor: 0 },
            { id: "LIN-ESP-024", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Salsa' significa:", opt: ["Molho", "Salsinha", "Sal", "Salsa (dança)"], cor: 0 },
            { id: "LIN-ESP-025", cat: "Linguagens", sub: "Espanhol", txt: "'Sitio' significa:", opt: ["Lugar", "Sítio (fazenda)", "Site", "Sede"], cor: 0 },
            { id: "LIN-ESP-026", cat: "Linguagens", sub: "Espanhol", txt: "'Propina' significa:", opt: ["Gorjeta", "Propina (crime)", "Própria", "Proposta"], cor: 0 },
            { id: "LIN-ESP-027", cat: "Linguagens", sub: "Espanhol", txt: "'Firma' significa:", opt: ["Assinatura", "Firmeza", "Empresa", "Filme"], cor: 0 },
            { id: "LIN-ESP-028", cat: "Linguagens", sub: "Espanhol", txt: "'Goma' significa:", opt: ["Borracha/Chiclete", "Goma de tapioca", "Cola", "Gomo"], cor: 0 },
            { id: "LIN-ESP-029", cat: "Linguagens", sub: "Espanhol", txt: "'Oso' significa:", opt: ["Urso", "Osso", "Ousado", "Olho"], cor: 0 },
            { id: "LIN-ESP-030", cat: "Linguagens", sub: "Espanhol", txt: "'Lunes' é:", opt: ["Segunda-feira", "Lua", "Luz", "Sábado"], cor: 0 },
            { id: "LIN-ESP-031", cat: "Linguagens", sub: "Espanhol", txt: "'Película' significa:", opt: ["Filme", "Pele", "Perigo", "Pelo"], cor: 0 },
            { id: "LIN-ESP-032", cat: "Linguagens", sub: "Espanhol", txt: "'Ordenador' ou 'Computadora' é:", opt: ["Computador", "Organizador", "Chefe", "Ordem"], cor: 0 },
            { id: "LIN-ESP-033", cat: "Linguagens", sub: "Espanhol", txt: "'Enero' é:", opt: ["Janeiro", "Dinheiro", "Erro", "Inteiro"], cor: 0 },
            { id: "LIN-ESP-034", cat: "Linguagens", sub: "Espanhol", txt: "'Amarillo' é a cor:", opt: ["Amarelo", "Amarrotado", "Vermelho", "Azul"], cor: 0 },
            { id: "LIN-ESP-035", cat: "Linguagens", sub: "Espanhol", txt: "'Salada' em espanhol é:", opt: ["Ensalada", "Salada", "Sal", "Salgada"], cor: 0 },
            { id: "LIN-ESP-036", cat: "Linguagens", sub: "Espanhol", txt: "'Pollo' significa:", opt: ["Frango", "Polo", "Bolo", "Pulo"], cor: 0 },
            { id: "LIN-ESP-037", cat: "Linguagens", sub: "Espanhol", txt: "'Pavo' significa:", opt: ["Peru", "Pavão", "Povo", "Bravo"], cor: 0 },
            { id: "LIN-ESP-038", cat: "Linguagens", sub: "Espanhol", txt: "'Arroz' é:", opt: ["Arroz", "Vermelho", "Raiz", "Raso"], cor: 0 },
            { id: "LIN-ESP-039", cat: "Linguagens", sub: "Espanhol", txt: "'Leche' é:", opt: ["Leite", "Lanche", "Leste", "Lichia"], cor: 0 },
            { id: "LIN-ESP-040", cat: "Linguagens", sub: "Espanhol", txt: "'Queso' é:", opt: ["Queijo", "Queixo", "Caso", "Querido"], cor: 0 },
            { id: "LIN-ESP-041", cat: "Linguagens", sub: "Espanhol", txt: "'Pan' é:", opt: ["Pão", "Panela", "Pano", "Pai"], cor: 0 },
            { id: "LIN-ESP-042", cat: "Linguagens", sub: "Espanhol", txt: "'Despacio' significa:", opt: ["Devagar", "Espaço", "Despedida", "Rápido"], cor: 0 },
            { id: "LIN-ESP-043", cat: "Linguagens", sub: "Espanhol", txt: "'Pronto' significa:", opt: ["Logo/Cedo/Rápido", "Pronto (terminado)", "Perto", "Ponto"], cor: 0 },
            { id: "LIN-ESP-044", cat: "Linguagens", sub: "Espanhol", txt: "'Todavía' significa:", opt: ["Ainda", "Todavia", "Tudo", "Toda via"], cor: 0 },
            { id: "LIN-ESP-045", cat: "Linguagens", sub: "Espanhol", txt: "'Gafas' são:", opt: ["Óculos", "Garras", "Garfos", "Garrafas"], cor: 0 },
            { id: "LIN-ESP-046", cat: "Linguagens", sub: "Espanhol", txt: "'Pantalones' são:", opt: ["Calças", "Pantufas", "Panos", "Pântanos"], cor: 0 },
            { id: "LIN-ESP-047", cat: "Linguagens", sub: "Espanhol", txt: "'Camisa' é:", opt: ["Camisa", "Cama", "Comida", "Caminho"], cor: 0 },
            { id: "LIN-ESP-048", cat: "Linguagens", sub: "Espanhol", txt: "'Zapatos' são:", opt: ["Sapatos", "Patos", "Sapos", "Zapas"], cor: 0 },
            { id: "LIN-ESP-049", cat: "Linguagens", sub: "Espanhol", txt: "'Negro' (cor) é:", opt: ["Preto", "Negativo", "Nuvem", "Neve"], cor: 0 },
            { id: "LIN-ESP-050", cat: "Linguagens", sub: "Espanhol", txt: "'Blanco' é:", opt: ["Branco", "Banco", "Balanço", "Braço"], cor: 0 },
            { id: "LIN-ESP-051", cat: "Linguagens", sub: "Espanhol", txt: "'Verde' é:", opt: ["Verde", "Verdade", "Vento", "Verão"], cor: 0 },
            { id: "LIN-ESP-052", cat: "Linguagens", sub: "Espanhol", txt: "'Azul' é:", opt: ["Azul", "Azeite", "Asa", "Alto"], cor: 0 },
            { id: "LIN-ESP-053", cat: "Linguagens", sub: "Espanhol", txt: "'Cabeza' é:", opt: ["Cabeça", "Cabelo", "Cabo", "Cabana"], cor: 0 },
            { id: "LIN-ESP-054", cat: "Linguagens", sub: "Espanhol", txt: "'Mano' é:", opt: ["Mão", "Irmão", "Manhã", "Menino"], cor: 0 },
            { id: "LIN-ESP-055", cat: "Linguagens", sub: "Espanhol", txt: "'Rodilla' é:", opt: ["Joelho", "Roda", "Rodela", "Rodo"], cor: 0 },
            { id: "LIN-ESP-056", cat: "Linguagens", sub: "Espanhol", txt: "'Nariz' é:", opt: ["Nariz", "Laranja", "Raiz", "Nada"], cor: 0 },
            { id: "LIN-ESP-057", cat: "Linguagens", sub: "Espanhol", txt: "'Calle' é:", opt: ["Rua", "Cale-se", "Calo", "Calor"], cor: 0 },
            { id: "LIN-ESP-058", cat: "Linguagens", sub: "Espanhol", txt: "'Playa' é:", opt: ["Praia", "Planalto", "Prata", "Prato"], cor: 0 },
            { id: "LIN-ESP-059", cat: "Linguagens", sub: "Espanhol", txt: "'Ciudad' é:", opt: ["Cidade", "Cidadão", "Cuidado", "Idade"], cor: 0 },
            { id: "LIN-ESP-060", cat: "Linguagens", sub: "Espanhol", txt: "'Hola' significa:", opt: ["Olá", "Onda", "Hora", "Rola"], cor: 0 },
            { id: "LIN-ESP-061", cat: "Linguagens", sub: "Espanhol", txt: "'Uno' é:", opt: ["1", "10", "11", "União"], cor: 0 },
            { id: "LIN-ESP-062", cat: "Linguagens", sub: "Espanhol", txt: "'Dos' é:", opt: ["2", "12", "Dorso", "Doce"], cor: 0 },
            { id: "LIN-ESP-063", cat: "Linguagens", sub: "Espanhol", txt: "'Tres' é:", opt: ["3", "13", "Trens", "Três"], cor: 0 },
            { id: "LIN-ESP-064", cat: "Linguagens", sub: "Espanhol", txt: "'Cuatro' é:", opt: ["4", "Quadro", "Quarto", "Custo"], cor: 0 },
            { id: "LIN-ESP-065", cat: "Linguagens", sub: "Espanhol", txt: "'Cinco' é:", opt: ["5", "Cinto", "Cinza", "Soco"], cor: 0 },
            { id: "LIN-ESP-066", cat: "Linguagens", sub: "Espanhol", txt: "'Seis' é:", opt: ["6", "Sede", "Sim", "Sei"], cor: 0 },
            { id: "LIN-ESP-067", cat: "Linguagens", sub: "Espanhol", txt: "'Siete' é:", opt: ["7", "Sede", "Site", "Sente"], cor: 0 },
            { id: "LIN-ESP-068", cat: "Linguagens", sub: "Espanhol", txt: "'Ocho' é:", opt: ["8", "Olho", "Osso", "Oco"], cor: 0 },
            { id: "LIN-ESP-069", cat: "Linguagens", sub: "Espanhol", txt: "'Nueve' é:", opt: ["9", "Neve", "Novo", "Nuvem"], cor: 0 },
            { id: "LIN-ESP-070", cat: "Linguagens", sub: "Espanhol", txt: "'Diez' é:", opt: ["10", "Dia", "Deus", "Diz"], cor: 0 },
            { id: "LIN-ESP-071", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Roxo' (Rojo) é:", opt: ["Vermelho", "Roxo", "Rosa", "Rouco"], cor: 0 },
            { id: "LIN-ESP-072", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Largo' é:", opt: ["Comprido", "Largo", "Lugar", "Lago"], cor: 0 },
            { id: "LIN-ESP-073", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Borracha' é:", opt: ["Bêbada", "Apagador", "Pneu", "Bota"], cor: 0 },
            { id: "LIN-ESP-074", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Embarazada' é:", opt: ["Grávida", "Embaraçada", "Presa", "Barata"], cor: 0 },
            { id: "LIN-ESP-075", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Exquisito' é:", opt: ["Delicioso", "Esquisito", "Feio", "Ruim"], cor: 0 },
            { id: "LIN-ESP-076", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Vaso' é:", opt: ["Copo", "Vaso", "Sanitário", "Veia"], cor: 0 },
            { id: "LIN-ESP-077", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Cena' é:", opt: ["Jantar", "Cena", "Sinal", "Cinza"], cor: 0 },
            { id: "LIN-ESP-078", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Oficina' é:", opt: ["Escritório", "Oficina mecânica", "Loja", "Cozinha"], cor: 0 },
            { id: "LIN-ESP-079", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Zurdo' é:", opt: ["Canhoto", "Surdo", "Mudo", "Cego"], cor: 0 },
            { id: "LIN-ESP-080", cat: "Linguagens", sub: "Espanhol", txt: "Falso amigo 'Ratón' é:", opt: ["Rato (e Mouse)", "Ratão", "Ratoeira", "Rápido"], cor: 0 },
            { id: "LIN-ESP-081", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Hablar':", opt: ["Falar", "Abrir", "Habilitar", "Habitar"], cor: 0 },
            { id: "LIN-ESP-082", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Comer':", opt: ["Comer", "Correr", "Começar", "Comerciar"], cor: 0 },
            { id: "LIN-ESP-083", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Vivir':", opt: ["Viver/Morar", "Vir", "Ver", "Voar"], cor: 0 },
            { id: "LIN-ESP-084", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Tener':", opt: ["Ter", "Temer", "Tender", "Tentar"], cor: 0 },
            { id: "LIN-ESP-085", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Hacer':", opt: ["Fazer", "Haver", "Nascer", "Achar"], cor: 0 },
            { id: "LIN-ESP-086", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Ir':", opt: ["Ir", "Vir", "Ver", "Ouvir"], cor: 0 },
            { id: "LIN-ESP-087", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Ser':", opt: ["Ser", "Ver", "Saber", "Sair"], cor: 0 },
            { id: "LIN-ESP-088", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Estar':", opt: ["Estar", "Ser", "Entrar", "Esperar"], cor: 0 },
            { id: "LIN-ESP-089", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Ver':", opt: ["Ver", "Vir", "Ir", "Ter"], cor: 0 },
            { id: "LIN-ESP-090", cat: "Linguagens", sub: "Espanhol", txt: "Verbo 'Oír':", opt: ["Ouvir", "Olhar", "Odiar", "Oirar"], cor: 0 },
            { id: "LIN-ESP-091", cat: "Linguagens", sub: "Espanhol", txt: "'Buenos días' significa:", opt: ["Bom dia", "Boa tarde", "Boa noite", "Bons dias"], cor: 0 },
            { id: "LIN-ESP-092", cat: "Linguagens", sub: "Espanhol", txt: "'Buenas noches' significa:", opt: ["Boa noite", "Boa tarde", "Bom dia", "Boas nozes"], cor: 0 },
            { id: "LIN-ESP-093", cat: "Linguagens", sub: "Espanhol", txt: "'Gracias' significa:", opt: ["Obrigado", "Graça", "Grátis", "Engraçado"], cor: 0 },
            { id: "LIN-ESP-094", cat: "Linguagens", sub: "Espanhol", txt: "'Por favor' significa:", opt: ["Por favor", "Por força", "Por fim", "Por fazer"], cor: 0 },
            { id: "LIN-ESP-095", cat: "Linguagens", sub: "Espanhol", txt: "'Lo siento' significa:", opt: ["Sinto muito/Desculpe", "Eu sento", "O assento", "Eu sinto"], cor: 0 },
            { id: "LIN-ESP-096", cat: "Linguagens", sub: "Espanhol", txt: "'Mucho gusto' significa:", opt: ["Prazer em conhecer", "Muito gosto", "Muito gasto", "Muito justo"], cor: 0 },
            { id: "LIN-ESP-097", cat: "Linguagens", sub: "Espanhol", txt: "'Hasta luego' significa:", opt: ["Até logo", "Até agora", "Até lugar", "Até longe"], cor: 0 },
            { id: "LIN-ESP-098", cat: "Linguagens", sub: "Espanhol", txt: "'¿Cómo estás?' significa:", opt: ["Como você está?", "Como é isso?", "Onde você está?", "Quem é você?"], cor: 0 },
            { id: "LIN-ESP-099", cat: "Linguagens", sub: "Espanhol", txt: "'Te quiero' significa:", opt: ["Eu te amo/quero", "Eu te espero", "Eu te quebro", "Eu te chamo"], cor: 0 },
            { id: "LIN-ESP-100", cat: "Linguagens", sub: "Espanhol", txt: "'Adiós' significa:", opt: ["Adeus", "A Deus", "A dois", "Adiem"], cor: 0 }
        ];

