export const questoes = [ 

            // --- SUB: GRAMÁTICA ---
            { id: "LIN-GRA-001", cat: "Linguagens", sub: "Gramática", txt: "Antônimo de 'efêmero':", opt: ["Rápido", "Passageiro", "Duradouro", "Breve"], cor: 2 },
            { id: "LIN-GRA-002", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra tem hífen corretamente?", opt: ["Anti-social", "Micro-ondas", "Auto-escola", "Dia-a-dia"], cor: 1 },
            { id: "LIN-GRA-003", cat: "Linguagens", sub: "Gramática", txt: "Em 'Fui à praia', a crase indica:", opt: ["Preposição + Artigo", "Apenas artigo", "Verbo", "Advérbio"], cor: 0 },
            { id: "LIN-GRA-004", cat: "Linguagens", sub: "Gramática", txt: "Qual é o sujeito de: 'Choveu muito'?", opt: ["Simples", "Oculto", "Inexistente", "Composto"], cor: 2 },
            { id: "LIN-GRA-005", cat: "Linguagens", sub: "Gramática", txt: "Qual o plural de 'guarda-chuva'?", opt: ["Guardas-chuva", "Guarda-chuvas", "Guardas-chuvas", "Guarda-chuves"], cor: 1 },
            { id: "LIN-GRA-006", cat: "Linguagens", sub: "Gramática", txt: "Identifique a figura de linguagem: 'Chorei rios de lágrimas'.", opt: ["Metáfora", "Hipérbole", "Eufemismo", "Antítese"], cor: 1 },
            { id: "LIN-GRA-007", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'exceção' se escreve com:", opt: ["X e Ç", "S e SS", "X e SS", "S e Ç"], cor: 0 },
            { id: "LIN-GRA-008", cat: "Linguagens", sub: "Gramática", txt: "'Ele correu, mas caiu'. A conjunção 'mas' indica:", opt: ["Adição", "Oposição/Adversidade", "Conclusão", "Explicação"], cor: 1 },
            { id: "LIN-GRA-009", cat: "Linguagens", sub: "Gramática", txt: "O que é um hiato?", opt: ["Encontro de duas vogais em sílabas diferentes", "Encontro de consoantes", "Encontro de vogais na mesma sílaba", "Som nasal"], cor: 0 },
            { id: "LIN-GRA-010", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra é paroxítona?", opt: ["Caju", "Lápis", "Árvore", "Sofá"], cor: 1 },
            { id: "LIN-GRA-011", cat: "Linguagens", sub: "Gramática", txt: "O uso de 'porque' junto e sem acento serve para:", opt: ["Perguntas", "Respostas/Explicação", "Substantivo", "Final de frase"], cor: 1 },
            { id: "LIN-GRA-012", cat: "Linguagens", sub: "Gramática", txt: "Em 'Vende-se casas', o sujeito é:", opt: ["Indeterminado", "Simples (casas)", "Oculto", "Inexistente"], cor: 1 },
            { id: "LIN-GRA-013", cat: "Linguagens", sub: "Gramática", txt: "Eufemismo é a figura que:", opt: ["Exagera", "Suaviza uma ideia desagradável", "Compara", "Opoe ideias"], cor: 1 },
            { id: "LIN-GRA-014", cat: "Linguagens", sub: "Gramática", txt: "Qual frase tem erro de concordância?", opt: ["A gente fomos", "Nós fomos", "A gente foi", "Eles foram"], cor: 0 },
            { id: "LIN-GRA-015", cat: "Linguagens", sub: "Gramática", txt: "Onde ocorre próclise (pronome antes do verbo)?", opt: ["Me dá um copo", "Não me diga", "Dê-me um copo", "Falou-me a verdade"], cor: 1 },
            { id: "LIN-GRA-016", cat: "Linguagens", sub: "Gramática", txt: "Antítese consiste em:", opt: ["Ideias opostas (amor e ódio)", "Sons repetidos", "Omissão de palavras", "Troca de nomes"], cor: 0 },
            { id: "LIN-GRA-017", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'imprescindível' significa:", opt: ["Dispensável", "Indispensável/Necessário", "Duvidoso", "Rápido"], cor: 1 },
            { id: "LIN-GRA-018", cat: "Linguagens", sub: "Gramática", txt: "Qual é o advérbio na frase: 'Ela canta muito bem'?", opt: ["Ela", "Canta", "Muito", "Bem"], cor: 3 },
            { id: "LIN-GRA-019", cat: "Linguagens", sub: "Gramática", txt: "Pleonasmo vicioso é:", opt: ["Repetição desnecessária (ex: subir pra cima)", "Figura de estilo", "Erro de grafia", "Gíria"], cor: 0 },
            { id: "LIN-GRA-020", cat: "Linguagens", sub: "Gramática", txt: "Voz passiva de 'O menino quebrou o vaso':", opt: ["O vaso quebrou o menino", "O vaso foi quebrado pelo menino", "O menino se quebrou", "Quebraram o vaso"], cor: 1 },
            { id: "LIN-GRA-021", cat: "Linguagens", sub: "Gramática", txt: "Qual a classe gramatical de 'fomos'?", opt: ["Substantivo", "Adjetivo", "Verbo", "Pronome"], cor: 2 },
            { id: "LIN-GRA-022", cat: "Linguagens", sub: "Gramática", txt: "Em 'Casa de ferreiro, espeto de pau', temos um:", opt: ["Provérbio", "Poema", "Conto", "Crônica"], cor: 0 },
            { id: "LIN-GRA-023", cat: "Linguagens", sub: "Gramática", txt: "A função fática da linguagem foca no:", opt: ["Canal/Contato (Ex: Alô?)", "Emissor", "Receptor", "Código"], cor: 0 },
            { id: "LIN-GRA-024", cat: "Linguagens", sub: "Gramática", txt: "A função poética foca na:", opt: ["Mensagem/Estética", "Informação", "Ordem", "Emoção"], cor: 0 },
            { id: "LIN-GRA-025", cat: "Linguagens", sub: "Gramática", txt: "Intertextualidade é:", opt: ["Diálogo entre textos", "Texto sem sentido", "Erro de digitação", "Texto na internet"], cor: 0 },
            { id: "LIN-GRA-026", cat: "Linguagens", sub: "Gramática", txt: "Qual o plural correto de 'degrau'?", opt: ["Degraus", "Degrais", "Degraues", "Degraus's"], cor: 0 },
            { id: "LIN-GRA-027", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'gratuito' é pronunciada como:", opt: ["Gratuíto (hiato)", "Gratuito (ditongo ui)", "Gratu-ito", "Grá-tuito"], cor: 1 },
            { id: "LIN-GRA-028", cat: "Linguagens", sub: "Gramática", txt: "O uso de 'há' (verbo haver) indica:", opt: ["Tempo futuro", "Tempo passado ou existência", "Lugar", "Modo"], cor: 1 },
            { id: "LIN-GRA-029", cat: "Linguagens", sub: "Gramática", txt: "Qual frase está correta?", opt: ["Houveram muitos problemas", "Houve muitos problemas", "Houveram problemas", "Haviam problemas"], cor: 1 },
            { id: "LIN-GRA-030", cat: "Linguagens", sub: "Gramática", txt: "Cacofonia é:", opt: ["Som desagradável na união de palavras", "Som bonito", "Música clássica", "Erro de acento"], cor: 0 },
            { id: "LIN-GRA-031", cat: "Linguagens", sub: "Gramática", txt: "Em 'Falar é prata, calar é ouro', temos:", opt: ["Metáfora", "Paralelismo", "Eufemismo", "Pleonasmo"], cor: 0 },
            { id: "LIN-GRA-032", cat: "Linguagens", sub: "Gramática", txt: "Oração subordinada que funciona como adjetivo é:", opt: ["Adjetiva", "Substantiva", "Adverbial", "Coordenada"], cor: 0 },
            { id: "LIN-GRA-033", cat: "Linguagens", sub: "Gramática", txt: "Qual a função sintática de 'Pedro' em: 'Pedro, venha cá!'?", opt: ["Sujeito", "Vocativo", "Aposto", "Objeto Direto"], cor: 1 },
            { id: "LIN-GRA-034", cat: "Linguagens", sub: "Gramática", txt: "Aposto serve para:", opt: ["Chamar alguém", "Explicar um termo anterior", "Indicar ação", "Ligar frases"], cor: 1 },
            { id: "LIN-GRA-035", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra deve ter acento?", opt: ["Ruim", "Nobel", "Heroico", "Heroi (Herói)"], cor: 3 },
            { id: "LIN-GRA-036", cat: "Linguagens", sub: "Gramática", txt: "A crase é obrigatória em:", opt: ["À vista", "A prazo", "A pé", "A cavalo"], cor: 0 },
            { id: "LIN-GRA-037", cat: "Linguagens", sub: "Gramática", txt: "Sinônimo de 'efêmero':", opt: ["Eterno", "Passageiro", "Duro", "Longo"], cor: 1 },
            { id: "LIN-GRA-038", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'mal' com L opõe-se a:", opt: ["Bom", "Bem", "Belo", "Mau"], cor: 1 },
            { id: "LIN-GRA-039", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'mau' com U opõe-se a:", opt: ["Bom", "Bem", "Belo", "Mal"], cor: 0 },
            { id: "LIN-GRA-040", cat: "Linguagens", sub: "Gramática", txt: "Regência do verbo 'Assistir' (ver):", opt: ["Assistir o filme", "Assistir ao filme", "Assistir do filme", "Assistir no filme"], cor: 1 },
            { id: "LIN-GRA-041", cat: "Linguagens", sub: "Gramática", txt: "Onde há derivação prefixal?", opt: ["Infeliz", "Felizmente", "Pedreira", "Amor"], cor: 0 },
            { id: "LIN-GRA-042", cat: "Linguagens", sub: "Gramática", txt: "Onde há derivação sufixal?", opt: ["Refazer", "Lealdade", "Desleal", "Inapto"], cor: 1 },
            { id: "LIN-GRA-043", cat: "Linguagens", sub: "Gramática", txt: "Qual é o superlativo de 'bom'?", opt: ["Boníssimo", "Ótimo", "Melhor", "Mais bom"], cor: 1 },
            { id: "LIN-GRA-044", cat: "Linguagens", sub: "Gramática", txt: "Verbos no imperativo indicam:", opt: ["Dúvida", "Ordem/Pedido", "Certeza", "Passado"], cor: 1 },
            { id: "LIN-GRA-045", cat: "Linguagens", sub: "Gramática", txt: "Prosopopeia (Personificação) é:", opt: ["Dar vida a seres inanimados", "Exagerar", "Comparar", "Suavizar"], cor: 0 },
            { id: "LIN-GRA-046", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra é oxítona?", opt: ["Café", "Mesa", "Lâmpada", "Cadeira"], cor: 0 },
            { id: "LIN-GRA-047", cat: "Linguagens", sub: "Gramática", txt: "Um ditongo é o encontro de:", opt: ["Uma vogal e uma semivogal na mesma sílaba", "Duas consoantes", "Vogais em sílabas separadas", "Três vogais"], cor: 0 },
            { id: "LIN-GRA-048", cat: "Linguagens", sub: "Gramática", txt: "Dígrafo ocorre quando:", opt: ["Duas letras representam um único som (ex: Ch)", "Há encontro de vogais", "A sílaba é tônica", "Há acento"], cor: 0 },
            { id: "LIN-GRA-049", cat: "Linguagens", sub: "Gramática", txt: "Substantivo coletivo de 'Lobos':", opt: ["Alcateia", "Matilha", "Bando", "Manada"], cor: 0 },
            { id: "LIN-GRA-050", cat: "Linguagens", sub: "Gramática", txt: "Substantivo coletivo de 'Peixes':", opt: ["Cardume", "Bando", "Enxame", "Rebanho"], cor: 0 },
            { id: "LIN-GRA-051", cat: "Linguagens", sub: "Gramática", txt: "Adjetivo pátrio de quem nasce no Espírito Santo:", opt: ["Capixaba", "Espirito-santense", "Santo", "Carioca"], cor: 0 },
            { id: "LIN-GRA-052", cat: "Linguagens", sub: "Gramática", txt: "Adjetivo pátrio de quem nasce no Rio de Janeiro (Cidade):", opt: ["Carioca", "Fluminense", "Baiano", "Paulista"], cor: 0 },
            { id: "LIN-GRA-053", cat: "Linguagens", sub: "Gramática", txt: "Pronome de tratamento para o Papa:", opt: ["Vossa Santidade", "Vossa Excelência", "Vossa Alteza", "Vossa Senhoria"], cor: 0 },
            { id: "LIN-GRA-054", cat: "Linguagens", sub: "Gramática", txt: "Em 'Vende-se casa', a partícula 'se' é:", opt: ["Partícula apassivadora", "Índice de indeterminação do sujeito", "Pronome reflexivo", "Conjunção"], cor: 0 },
            { id: "LIN-GRA-055", cat: "Linguagens", sub: "Gramática", txt: "Em 'Precisa-se de operários', o sujeito é:", opt: ["Indeterminado", "Simples", "Oculto", "Composto"], cor: 0 },
            { id: "LIN-GRA-056", cat: "Linguagens", sub: "Gramática", txt: "Uso dos porquês: '___ você não foi?' (início):", opt: ["Por que", "Porque", "Porquê", "Por quê"], cor: 0 },
            { id: "LIN-GRA-057", cat: "Linguagens", sub: "Gramática", txt: "Uso dos porquês: 'Eu não fui ___ estava doente'.", opt: ["Porque", "Por que", "Porquê", "Por quê"], cor: 0 },
            { id: "LIN-GRA-058", cat: "Linguagens", sub: "Gramática", txt: "Parônimos: 'Comprimento' refere-se a:", opt: ["Tamanho/Extensão", "Saudação", "Preço", "Peso"], cor: 0 },
            { id: "LIN-GRA-059", cat: "Linguagens", sub: "Gramática", txt: "Parônimos: 'Cumprimento' refere-se a:", opt: ["Saudação/Ato de cumprir", "Tamanho", "Distância", "Altura"], cor: 0 },
            { id: "LIN-GRA-060", cat: "Linguagens", sub: "Gramática", txt: "Homônimos: 'Cessão' com C significa:", opt: ["Ato de ceder/doar", "Reunião", "Departamento", "Corte"], cor: 0 },
            { id: "LIN-GRA-061", cat: "Linguagens", sub: "Gramática", txt: "Homônimos: 'Sessão' com S significa:", opt: ["Reunião/Tempo de cinema", "Doação", "Departamento", "Corte"], cor: 0 },
            { id: "LIN-GRA-062", cat: "Linguagens", sub: "Gramática", txt: "Onomatopeia é:", opt: ["Imitação de sons (Ex: Tic-tac)", "Repetição de vogais", "Exagero", "Comparação"], cor: 0 },
            { id: "LIN-GRA-063", cat: "Linguagens", sub: "Gramática", txt: "Paradoxo é:", opt: ["Ideias contraditórias que parecem absurdas", "Ideias iguais", "Elogio falso", "Pergunta retórica"], cor: 0 },
            { id: "LIN-GRA-064", cat: "Linguagens", sub: "Gramática", txt: "Neologismo é:", opt: ["Criação de novas palavras", "Palavra antiga", "Gíria de jovem", "Erro gramatical"], cor: 0 },
            { id: "LIN-GRA-065", cat: "Linguagens", sub: "Gramática", txt: "Variação linguística regional chama-se:", opt: ["Dialeto", "Gíria", "Jargão", "Norma culta"], cor: 0 },
            { id: "LIN-GRA-066", cat: "Linguagens", sub: "Gramática", txt: "O uso da vírgula é OBRIGATÓRIO para isolar:", opt: ["O sujeito", "O vocativo", "O objeto direto", "O adjetivo"], cor: 1 },
            { id: "LIN-GRA-067", cat: "Linguagens", sub: "Gramática", txt: "A palavra 'meio' concorda em gênero quando significa:", opt: ["Metade (ex: meia maça)", "Um pouco (ex: meio cansada)", "Instrumento", "Lugar"], cor: 0 },
            { id: "LIN-GRA-068", cat: "Linguagens", sub: "Gramática", txt: "Ela estava ___ cansada. O correto é:", opt: ["Meio", "Meia", "Metade", "Média"], cor: 0 },
            { id: "LIN-GRA-069", cat: "Linguagens", sub: "Gramática", txt: "Diferença entre 'Mas' e 'Mais':", opt: ["Mas=Oposição / Mais=Quantidade", "Mas=Quantidade / Mais=Oposição", "São iguais", "Mas é verbo"], cor: 0 },
            { id: "LIN-GRA-070", cat: "Linguagens", sub: "Gramática", txt: "'Aonde' indica:", opt: ["Movimento/Destino", "Lugar fixo", "Tempo", "Modo"], cor: 0 },
            { id: "LIN-GRA-071", cat: "Linguagens", sub: "Gramática", txt: "'Onde' indica:", opt: ["Lugar fixo/Permanência", "Movimento", "Tempo", "Causa"], cor: 0 },
            { id: "LIN-GRA-072", cat: "Linguagens", sub: "Gramática", txt: "O plural de 'Cidadão' é:", opt: ["Cidadãos", "Cidadões", "Cidadães", "Cidadãoes"], cor: 0 },
            { id: "LIN-GRA-073", cat: "Linguagens", sub: "Gramática", txt: "Concordância verbal: 'Fazem' ou 'Faz'?", opt: ["Faz 10 anos (tempo decorrido é singular)", "Fazem 10 anos", "Fizeram 10 anos", "Faria 10 anos"], cor: 0 },
            { id: "LIN-GRA-074", cat: "Linguagens", sub: "Gramática", txt: "Qual frase tem erro de regência?", opt: ["Eu namoro com ela", "Eu namoro ela", "Vou ao banheiro", "Gosto de sorvete"], cor: 0 },
            { id: "LIN-GRA-075", cat: "Linguagens", sub: "Gramática", txt: "O verbo 'Haver' no sentido de existir:", opt: ["Fica sempre no singular", "Vai para o plural", "Concorda com o sujeito", "Varia sempre"], cor: 0 },
            { id: "LIN-GRA-076", cat: "Linguagens", sub: "Gramática", txt: "O correto é: 'Ao invés de' ou 'Em vez de' para escolhas simples?", opt: ["Em vez de (lugar de)", "Ao invés de (contrário)", "Tanto faz", "Nenhum"], cor: 0 },
            { id: "LIN-GRA-077", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra está escrita corretamente?", opt: ["Exceção", "Excessão", "Ezceção", "Ecceção"], cor: 0 },
            { id: "LIN-GRA-078", cat: "Linguagens", sub: "Gramática", txt: "Qual palavra está escrita incorretamente?", opt: ["Beneficiente", "Beneficente", "Cansado", "Xícara"], cor: 0 },
            { id: "LIN-GRA-079", cat: "Linguagens", sub: "Gramática", txt: "O 'Hífen' caiu em palavras com vogais:", opt: ["Diferentes (ex: autoescola)", "Iguais (ex: micro-ondas)", "Consoantes", "Sempre"], cor: 0 },
            { id: "LIN-GRA-080", cat: "Linguagens", sub: "Gramática", txt: "Qual o sujeito de 'Havia muitas pessoas'?", opt: ["Inexistente", "Muitas pessoas", "Oculto", "Indeterminado"], cor: 0 },
            { id: "LIN-GRA-081", cat: "Linguagens", sub: "Gramática", txt: "Pronome oblíquo inicia frase? (Ex: 'Te amo')", opt: ["Na norma culta, não", "Sim, sempre", "Depende do dia", "Sim, se for poesia"], cor: 0 },
            { id: "LIN-GRA-082", cat: "Linguagens", sub: "Gramática", txt: "Sinestesia é a figura que:", opt: ["Mistura sentidos (ex: cheiro doce)", "Exagera", "Repete sons", "Omite termos"], cor: 0 },
            { id: "LIN-GRA-083", cat: "Linguagens", sub: "Gramática", txt: "Catacrese é a figura que:", opt: ["Usa termo emprestado (ex: pé da mesa)", "Suaviza", "Contradiz", "Ironiza"], cor: 0 },
            { id: "LIN-GRA-084", cat: "Linguagens", sub: "Gramática", txt: "Ironia consiste em:", opt: ["Dizer o contrário do que se pensa", "Xingar", "Mentir", "Gritar"], cor: 0 },
            { id: "LIN-GRA-085", cat: "Linguagens", sub: "Gramática", txt: "Qual frase usa 'Mau' corretamente?", opt: ["Ele é um mau aluno", "Ele está mau humorado", "Mau fui lá", "Estou mau"], cor: 0 },
            { id: "LIN-GRA-086", cat: "Linguagens", sub: "Gramática", txt: "A crase é PROIBIDA antes de:", opt: ["Verbos e palavras masculinas", "Palavras femininas", "Horas", "Locuções adverbiais"], cor: 0 },
            { id: "LIN-GRA-087", cat: "Linguagens", sub: "Gramática", txt: "Qual o plural de 'Troféu'?", opt: ["Troféus", "Troféis", "Troféues", "Trofels"], cor: 0 },
            { id: "LIN-GRA-088", cat: "Linguagens", sub: "Gramática", txt: "Concordância Nominal: 'Seguem ___ as fotos'.", opt: ["Anexas", "Anexo", "Em anexo", "Anexadas"], cor: 0 },
            { id: "LIN-GRA-089", cat: "Linguagens", sub: "Gramática", txt: "Qual frase está correta?", opt: ["Haja vista os problemas", "Haja visto os problemas", "Hajam vista os problemas", "Haja vistas"], cor: 0 },
            { id: "LIN-GRA-090", cat: "Linguagens", sub: "Gramática", txt: "Hipérbato é a figura de:", opt: ["Inversão da ordem da frase", "Exagero", "Repetição", "Suavização"], cor: 0 },
            { id: "LIN-GRA-091", cat: "Linguagens", sub: "Gramática", txt: "Metonímia é:", opt: ["Substituição lógica (ex: ler Machado)", "Comparação", "Grito", "Mentira"], cor: 0 },
            { id: "LIN-GRA-092", cat: "Linguagens", sub: "Gramática", txt: "A função Referencial foca na:", opt: ["Informação/Notícia", "Emoção", "Beleza", "Persuasão"], cor: 0 },
            { id: "LIN-GRA-093", cat: "Linguagens", sub: "Gramática", txt: "A função Conativa/Apelativa foca no:", opt: ["Convencimento do receptor (Propaganda)", "Emissor", "Código", "Canal"], cor: 0 },
            { id: "LIN-GRA-094", cat: "Linguagens", sub: "Gramática", txt: "Oração Coordenada Adversativa usa:", opt: ["Mas, porém, todavia", "E, nem", "Logo, portanto", "Ou, ora"], cor: 0 },
            { id: "LIN-GRA-095", cat: "Linguagens", sub: "Gramática", txt: "Oração Coordenada Conclusiva usa:", opt: ["Logo, portanto, assim", "Mas, porém", "Porque, pois", "Ou, ora"], cor: 0 },
            { id: "LIN-GRA-096", cat: "Linguagens", sub: "Gramática", txt: "'Bem-vindo' tem hífen?", opt: ["Sim, sempre", "Não", "Depende", "Só no plural"], cor: 0 },
            { id: "LIN-GRA-097", cat: "Linguagens", sub: "Gramática", txt: "'Micro-ondas' tem hífen porque:", opt: ["Vogais iguais se separam", "Vogais diferentes se juntam", "É lei", "É nome próprio"], cor: 0 },
            { id: "LIN-GRA-098", cat: "Linguagens", sub: "Gramática", txt: "Qual o diminutivo de 'Cão'?", opt: ["Cãozinho", "Cãozito", "Cãoto", "Cãoninho"], cor: 0 },
            { id: "LIN-GRA-099", cat: "Linguagens", sub: "Gramática", txt: "Qual a classe gramatical de 'Não'?", opt: ["Advérbio de negação", "Verbo", "Substantivo", "Adjetivo"], cor: 0 },
            { id: "LIN-GRA-100", cat: "Linguagens", sub: "Gramática", txt: "Qual frase está na Voz Passiva?", opt: ["A carta foi escrita por Ana", "Ana escreveu a carta", "Ana escreve bem", "Ana correu"], cor: 0 },
            
];
