export const questoes = [

  
            // --- SUB: INGLÊS ---
            { id: "LIN-ING-001", cat: "Linguagens", sub: "Inglês", txt: "O passado de 'Go' é:", opt: ["Goed", "Gone", "Went", "Going"], cor: 2 },
            { id: "LIN-ING-002", cat: "Linguagens", sub: "Inglês", txt: "Tradução de 'Book':", opt: ["Mesa", "Livro", "Caneta", "Cadeira"], cor: 1 },
            { id: "LIN-ING-003", cat: "Linguagens", sub: "Inglês", txt: "Complete: She ___ happy.", opt: ["Am", "Are", "Is", "Be"], cor: 2 },
            { id: "LIN-ING-004", cat: "Linguagens", sub: "Inglês", txt: "O falso cognato 'Push' significa:", opt: ["Empurrar", "Puxar", "Pular", "Pegar"], cor: 0 },
            { id: "LIN-ING-005", cat: "Linguagens", sub: "Inglês", txt: "O falso cognato 'Pull' significa:", opt: ["Puxar", "Pular", "Empurrar", "Colocar"], cor: 0 },
            { id: "LIN-ING-006", cat: "Linguagens", sub: "Inglês", txt: "'Parents' significa:", opt: ["Pais", "Parentes", "Primos", "Papéis"], cor: 0 },
            { id: "LIN-ING-007", cat: "Linguagens", sub: "Inglês", txt: "'Lunch' significa:", opt: ["Almoço", "Lanche", "Jantar", "Luz"], cor: 0 },
            { id: "LIN-ING-008", cat: "Linguagens", sub: "Inglês", txt: "Passado de 'Do':", opt: ["Did", "Done", "Does", "Doing"], cor: 0 },
            { id: "LIN-ING-009", cat: "Linguagens", sub: "Inglês", txt: "'I have been' é um tempo:", opt: ["Present Perfect", "Simple Past", "Future", "Present Continuous"], cor: 0 },
            { id: "LIN-ING-010", cat: "Linguagens", sub: "Inglês", txt: "'Bread' é:", opt: ["Pão", "Briga", "Vermelho", "Cama"], cor: 0 },
            { id: "LIN-ING-011", cat: "Linguagens", sub: "Inglês", txt: "Tradução de 'Red':", opt: ["Vermelho", "Rede", "Roda", "Rato"], cor: 0 },
            { id: "LIN-ING-012", cat: "Linguagens", sub: "Inglês", txt: "'Data' geralmente significa:", opt: ["Dados (informação)", "Data do calendário", "Dívida", "Dedo"], cor: 0 },
            { id: "LIN-ING-013", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Actually' significa:", opt: ["Na verdade", "Atualmente", "Agora", "Ação"], cor: 0 },
            { id: "LIN-ING-014", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Pretend' significa:", opt: ["Fingir", "Pretender", "Entender", "Estender"], cor: 0 },
            { id: "LIN-ING-015", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Fabric' significa:", opt: ["Tecido", "Fábrica", "Fabricar", "Feito"], cor: 0 },
            { id: "LIN-ING-016", cat: "Linguagens", sub: "Inglês", txt: "'Library' significa:", opt: ["Biblioteca", "Livraria", "Liberdade", "Livro"], cor: 0 },
            { id: "LIN-ING-017", cat: "Linguagens", sub: "Inglês", txt: "'Shoot' significa:", opt: ["Atirar/Chutar", "Gritar", "Chorar", "Pular"], cor: 0 },
            { id: "LIN-ING-018", cat: "Linguagens", sub: "Inglês", txt: "'Watch' pode ser:", opt: ["Assistir ou Relógio", "Ver ou Água", "Lavar ou Assistir", "Mão ou Relógio"], cor: 0 },
            { id: "LIN-ING-019", cat: "Linguagens", sub: "Inglês", txt: "Gerúndio em inglês termina em:", opt: ["-ing", "-ed", "-s", "-ly"], cor: 0 },
            { id: "LIN-ING-020", cat: "Linguagens", sub: "Inglês", txt: "O verbo 'To Be' no passado é:", opt: ["Was/Were", "Am/Is/Are", "Been", "Be"], cor: 0 },
            { id: "LIN-ING-021", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Costume' significa:", opt: ["Fantasia/Traje", "Costume", "Hábito", "Costura"], cor: 0 },
            { id: "LIN-ING-022", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Tax' significa:", opt: ["Imposto", "Táxi", "Taxa", "Teto"], cor: 0 },
            { id: "LIN-ING-023", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Assist' significa:", opt: ["Ajudar", "Assistir TV", "Assinar", "Insistir"], cor: 0 },
            { id: "LIN-ING-024", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Exit' significa:", opt: ["Saída", "Êxito", "Existir", "Hesitar"], cor: 0 },
            { id: "LIN-ING-025", cat: "Linguagens", sub: "Inglês", txt: "O verbo 'Will' indica:", opt: ["Futuro", "Passado", "Presente", "Ordem"], cor: 0 },
            { id: "LIN-ING-026", cat: "Linguagens", sub: "Inglês", txt: "'Going to' é usado para:", opt: ["Futuro planejado", "Passado", "Hábito", "Dúvida"], cor: 0 },
            { id: "LIN-ING-027", cat: "Linguagens", sub: "Inglês", txt: "Comparativo de 'Good':", opt: ["Better", "Gooder", "Best", "More good"], cor: 0 },
            { id: "LIN-ING-028", cat: "Linguagens", sub: "Inglês", txt: "Superlativo de 'Good':", opt: ["Best", "Better", "Goodest", "Most good"], cor: 0 },
            { id: "LIN-ING-029", cat: "Linguagens", sub: "Inglês", txt: "Pronome 'Him' refere-se a:", opt: ["Ele (objeto)", "Ela", "Nós", "Eles"], cor: 0 },
            { id: "LIN-ING-030", cat: "Linguagens", sub: "Inglês", txt: "'Vegetables' são:", opt: ["Legumes/Verduras", "Vegetais apenas", "Frutas", "Doces"], cor: 0 },
            { id: "LIN-ING-031", cat: "Linguagens", sub: "Inglês", txt: "'Meat' significa:", opt: ["Carne", "Encontrar", "Menta", "Mito"], cor: 0 },
            { id: "LIN-ING-032", cat: "Linguagens", sub: "Inglês", txt: "'Sunday' é:", opt: ["Domingo", "Sábado", "Segunda", "Sol"], cor: 0 },
            { id: "LIN-ING-033", cat: "Linguagens", sub: "Inglês", txt: "'January' é:", opt: ["Janeiro", "Junho", "Julho", "Jantar"], cor: 0 },
            { id: "LIN-ING-034", cat: "Linguagens", sub: "Inglês", txt: "Number 'Twelve' is:", opt: ["12", "20", "11", "2"], cor: 0 },
            { id: "LIN-ING-035", cat: "Linguagens", sub: "Inglês", txt: "Number 'Twenty' is:", opt: ["20", "12", "30", "10"], cor: 0 },
            { id: "LIN-ING-036", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Push' é:", opt: ["Empurrar", "Puxar", "Pular", "Pegar"], cor: 0 },
            { id: "LIN-ING-037", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Support' é:", opt: ["Apoiar", "Suportar (tolerar)", "Supor", "Suprir"], cor: 0 },
            { id: "LIN-ING-038", cat: "Linguagens", sub: "Inglês", txt: "'Relatives' significa:", opt: ["Parentes", "Relativos", "Relatórios", "Amigos"], cor: 0 },
            { id: "LIN-ING-039", cat: "Linguagens", sub: "Inglês", txt: "'Application' pode ser:", opt: ["Inscrição/Formulário ou App", "Aplicação financeira", "Aplique de cabelo", "Explicação"], cor: 0 },
            { id: "LIN-ING-040", cat: "Linguagens", sub: "Inglês", txt: "Cor 'Blue' é:", opt: ["Azul", "Amarelo", "Verde", "Branco"], cor: 0 },
            { id: "LIN-ING-041", cat: "Linguagens", sub: "Inglês", txt: "Cor 'Green' é:", opt: ["Verde", "Cinza", "Preto", "Rosa"], cor: 0 },
            { id: "LIN-ING-042", cat: "Linguagens", sub: "Inglês", txt: "Cor 'Yellow' é:", opt: ["Amarelo", "Gelo", "Laranja", "Roxo"], cor: 0 },
            { id: "LIN-ING-043", cat: "Linguagens", sub: "Inglês", txt: "Cor 'Black' é:", opt: ["Preto", "Branco", "Bege", "Azul"], cor: 0 },
            { id: "LIN-ING-044", cat: "Linguagens", sub: "Inglês", txt: "Cor 'White' é:", opt: ["Branco", "Vermelho", "Vinho", "Violeta"], cor: 0 },
            { id: "LIN-ING-045", cat: "Linguagens", sub: "Inglês", txt: "'Monday' é:", opt: ["Segunda-feira", "Domingo", "Manhã", "Mundo"], cor: 0 },
            { id: "LIN-ING-046", cat: "Linguagens", sub: "Inglês", txt: "'Friday' é:", opt: ["Sexta-feira", "Feriado", "Frio", "Frito"], cor: 0 },
            { id: "LIN-ING-047", cat: "Linguagens", sub: "Inglês", txt: "'Happy Birthday' significa:", opt: ["Feliz Aniversário", "Feliz Natal", "Bom dia", "Boa viagem"], cor: 0 },
            { id: "LIN-ING-048", cat: "Linguagens", sub: "Inglês", txt: "'How old are you?' pergunta:", opt: ["Sua idade", "Como você está", "Onde você está", "Quem é você"], cor: 0 },
            { id: "LIN-ING-049", cat: "Linguagens", sub: "Inglês", txt: "'Apple' é:", opt: ["Maçã", "Pera", "Abacaxi", "Uva"], cor: 0 },
            { id: "LIN-ING-050", cat: "Linguagens", sub: "Inglês", txt: "'Water' é:", opt: ["Água", "Garçom", " banheiro", "Inverno"], cor: 0 },
            { id: "LIN-ING-051", cat: "Linguagens", sub: "Inglês", txt: "Phrasal Verb 'Give up' significa:", opt: ["Desistir", "Dar cima", "Levantar", "Ganhar"], cor: 0 },
            { id: "LIN-ING-052", cat: "Linguagens", sub: "Inglês", txt: "Phrasal Verb 'Look for' significa:", opt: ["Procurar", "Olhar para", "Cuidar", "Parecer"], cor: 0 },
            { id: "LIN-ING-053", cat: "Linguagens", sub: "Inglês", txt: "'If I were you' (Condicional) significa:", opt: ["Se eu fosse você", "Se eu sou você", "Quando eu for", "Se eu vou"], cor: 0 },
            { id: "LIN-ING-054", cat: "Linguagens", sub: "Inglês", txt: "'Dog' e 'Cat' são:", opt: ["Cachorro e Gato", "Pato e Galinha", "Dia e Noite", "Frio e Quente"], cor: 0 },
            { id: "LIN-ING-055", cat: "Linguagens", sub: "Inglês", txt: "'Teacher' é:", opt: ["Professor(a)", "Aluno", "Escola", "Teste"], cor: 0 },
            { id: "LIN-ING-056", cat: "Linguagens", sub: "Inglês", txt: "'Nurse' é:", opt: ["Enfermeiro(a)", "Nuvem", "Nariz", "Nunca"], cor: 0 },
            { id: "LIN-ING-057", cat: "Linguagens", sub: "Inglês", txt: "'Lawyer' é:", opt: ["Advogado", "Lei", "Longe", "Leal"], cor: 0 },
            { id: "LIN-ING-058", cat: "Linguagens", sub: "Inglês", txt: "Plural de 'Man' (homem) é:", opt: ["Men", "Mans", "Manes", "Mens"], cor: 0 },
            { id: "LIN-ING-059", cat: "Linguagens", sub: "Inglês", txt: "Plural de 'Woman' (mulher) é:", opt: ["Women", "Womans", "Womens", "Girls"], cor: 0 },
            { id: "LIN-ING-060", cat: "Linguagens", sub: "Inglês", txt: "Plural de 'Child' (criança) é:", opt: ["Children", "Childs", "Childes", "Kids"], cor: 0 },
            { id: "LIN-ING-061", cat: "Linguagens", sub: "Inglês", txt: "'Book' como verbo significa:", opt: ["Reservar/Agendar", "Ler", "Escrever", "Estudar"], cor: 0 },
            { id: "LIN-ING-062", cat: "Linguagens", sub: "Inglês", txt: "'Train' como verbo significa:", opt: ["Treinar", "Viajar", "Trilhar", "Tentar"], cor: 0 },
            { id: "LIN-ING-063", cat: "Linguagens", sub: "Inglês", txt: "'Fly' pode ser voar ou:", opt: ["Mosca", "Avião", "Céu", "Fluir"], cor: 0 },
            { id: "LIN-ING-064", cat: "Linguagens", sub: "Inglês", txt: "'Left' pode ser esquerda ou:", opt: ["Partiu/Deixou (passado de leave)", "Levantou", "Direita", "Leve"], cor: 0 },
            { id: "LIN-ING-065", cat: "Linguagens", sub: "Inglês", txt: "'Hard' pode ser difícil ou:", opt: ["Duro", "Fácil", "Mole", "Alto"], cor: 0 },
            { id: "LIN-ING-066", cat: "Linguagens", sub: "Inglês", txt: "'Face' como verbo significa:", opt: ["Encarar", "Fazer", "Falar", "Fugir"], cor: 0 },
            { id: "LIN-ING-067", cat: "Linguagens", sub: "Inglês", txt: "'Head' é cabeça ou:", opt: ["Chefe/Líder", "Mão", "Pé", "Coração"], cor: 0 },
            { id: "LIN-ING-068", cat: "Linguagens", sub: "Inglês", txt: "'Back' pode ser costas ou:", opt: ["Voltar/Atrás", "Frente", "Baixo", "Beco"], cor: 0 },
            { id: "LIN-ING-069", cat: "Linguagens", sub: "Inglês", txt: "'Light' pode ser luz ou:", opt: ["Leve/Claro", "Pesado", "Escuro", "Noite"], cor: 0 },
            { id: "LIN-ING-070", cat: "Linguagens", sub: "Inglês", txt: "'Park' como verbo significa:", opt: ["Estacionar", "Passear", "Parar", "Pagar"], cor: 0 },
            { id: "LIN-ING-071", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Eat':", opt: ["Comer", "Beber", "Dormir", "Correr"], cor: 0 },
            { id: "LIN-ING-072", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Drink':", opt: ["Beber", "Comer", "Dirigir", "Desenhar"], cor: 0 },
            { id: "LIN-ING-073", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Sleep':", opt: ["Dormir", "Sonhar", "Sair", "Saltar"], cor: 0 },
            { id: "LIN-ING-074", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Run':", opt: ["Correr", "Rir", "Roubar", "Rolar"], cor: 0 },
            { id: "LIN-ING-075", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Walk':", opt: ["Andar/Caminhar", "Trabalhar", "Acordar", "Escrever"], cor: 0 },
            { id: "LIN-ING-076", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Talk':", opt: ["Falar/Conversar", "Tomar", "Tocar", "Tentar"], cor: 0 },
            { id: "LIN-ING-077", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Listen':", opt: ["Escutar", "Listar", "Limpar", "Lutar"], cor: 0 },
            { id: "LIN-ING-078", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Write':", opt: ["Escrever", "Ler", "Gritar", "Direita"], cor: 0 },
            { id: "LIN-ING-079", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Read':", opt: ["Ler", "Vermelho", "Rodar", "Rir"], cor: 0 },
            { id: "LIN-ING-080", cat: "Linguagens", sub: "Inglês", txt: "Verbo 'Sing':", opt: ["Cantar", "Sinal", "Simples", "Sentar"], cor: 0 },
            { id: "LIN-ING-081", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Journal' é:", opt: ["Diário/Revista acadêmica", "Jornal de notícias", "Jornada", "Jovem"], cor: 0 },
            { id: "LIN-ING-082", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Legend' é:", opt: ["Lenda", "Legenda", "Legal", "Legião"], cor: 0 },
            { id: "LIN-ING-083", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Notice' é:", opt: ["Notar/Aviso", "Notícia", "Noite", "Noiva"], cor: 0 },
            { id: "LIN-ING-084", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'Parents' é:", opt: ["Pais", "Parentes", "Partes", "Paredes"], cor: 0 },
            { id: "LIN-ING-085", cat: "Linguagens", sub: "Inglês", txt: "Falso cognato 'College' é:", opt: ["Faculdade", "Colégio", "Colega", "Colar"], cor: 0 },
            { id: "LIN-ING-086", cat: "Linguagens", sub: "Inglês", txt: "'Piece of cake' significa:", opt: ["Muito fácil", "Pedaço de bolo", "Comida", "Festa"], cor: 0 },
            { id: "LIN-ING-087", cat: "Linguagens", sub: "Inglês", txt: "'Break a leg' significa:", opt: ["Boa sorte", "Quebre a perna", "Vá ao médico", "Pare"], cor: 0 },
            { id: "LIN-ING-088", cat: "Linguagens", sub: "Inglês", txt: "'Under the weather' significa:", opt: ["Doente/Indisposto", "Embaixo do tempo", "Chovendo", "Sol"], cor: 0 },
            { id: "LIN-ING-089", cat: "Linguagens", sub: "Inglês", txt: "'Better late than never' significa:", opt: ["Antes tarde do que nunca", "Tarde demais", "Melhor não ir", "Nunca diga nunca"], cor: 0 },
            { id: "LIN-ING-090", cat: "Linguagens", sub: "Inglês", txt: "'I'm broke' significa:", opt: ["Estou sem dinheiro", "Estou quebrado (osso)", "Estou feliz", "Estou bravo"], cor: 0 },
            { id: "LIN-ING-091", cat: "Linguagens", sub: "Inglês", txt: "'Hold on' significa:", opt: ["Espere", "Segure firme", "Vá embora", "Ligue"], cor: 0 },
            { id: "LIN-ING-092", cat: "Linguagens", sub: "Inglês", txt: "'Give me a hand' significa:", opt: ["Me ajude", "Me dê sua mão", "Bata palma", "Tchau"], cor: 0 },
            { id: "LIN-ING-093", cat: "Linguagens", sub: "Inglês", txt: "'It's raining cats and dogs' significa:", opt: ["Chovendo muito", "Animais caindo", "Barulho", "Briga"], cor: 0 },
            { id: "LIN-ING-094", cat: "Linguagens", sub: "Inglês", txt: "'See you later' significa:", opt: ["Até logo", "Vi você antes", "Não te vejo", "Olhe lá"], cor: 0 },
            { id: "LIN-ING-095", cat: "Linguagens", sub: "Inglês", txt: "'Good job' significa:", opt: ["Bom trabalho", "Emprego bom", "Deus te ajude", "Trabalho chato"], cor: 0 },
            { id: "LIN-ING-096", cat: "Linguagens", sub: "Inglês", txt: "'I don't care' significa:", opt: ["Eu não me importo", "Eu não carrego", "Eu não caio", "Eu não sei"], cor: 0 },
            { id: "LIN-ING-097", cat: "Linguagens", sub: "Inglês", txt: "'Never mind' significa:", opt: ["Deixa pra lá", "Nunca mente", "Minha mente", "Nunca mais"], cor: 0 },
            { id: "LIN-ING-098", cat: "Linguagens", sub: "Inglês", txt: "'Excuse me' significa:", opt: ["Com licença", "Me acuse", "Desculpe-me", "Saia"], cor: 0 },
            { id: "LIN-ING-099", cat: "Linguagens", sub: "Inglês", txt: "'Bless you' (após espirro) significa:", opt: ["Saúde", "Deus te abençoe", "Pare com isso", "Adeus"], cor: 0 },
            { id: "LIN-ING-100", cat: "Linguagens", sub: "Inglês", txt: "'The book is on the table' é:", opt: ["O livro está sobre a mesa", "O livro é da mesa", "A mesa está no livro", "Clássico"], cor: 0 },
           
];
