export const questoes = [

 
            // --- SUB: LITERATURA ---
            { id: "LIN-LIT-001", cat: "Linguagens", sub: "Literatura", txt: "Autor de 'Vidas Secas':", opt: ["Jorge Amado", "Graciliano Ramos", "Guimarães Rosa", "Clarice"], cor: 1 },
            { id: "LIN-LIT-002", cat: "Linguagens", sub: "Literatura", txt: "Movimento literário de Gregório de Matos:", opt: ["Barroco", "Arcadismo", "Romantismo", "Realismo"], cor: 0 },
            { id: "LIN-LIT-003", cat: "Linguagens", sub: "Literatura", txt: "Capitu é personagem de qual obra?", opt: ["Memórias Póstumas", "Dom Casmurro", "Quincas Borba", "O Cortiço"], cor: 1 },
            { id: "LIN-LIT-004", cat: "Linguagens", sub: "Literatura", txt: "Monteiro Lobato é famoso por criar:", opt: ["O Menino Maluquinho", "Sítio do Picapau Amarelo", "Turma da Mônica", "Capitães da Areia"], cor: 1 },
            { id: "LIN-LIT-005", cat: "Linguagens", sub: "Literatura", txt: "O Romantismo valorizava:", opt: ["A razão", "A emoção, o eu e a nacionalidade", "A objetividade", "A ciência"], cor: 1 },
            { id: "LIN-LIT-006", cat: "Linguagens", sub: "Literatura", txt: "Autor de 'Grande Sertão: Veredas':", opt: ["Jorge Amado", "Guimarães Rosa", "Érico Veríssimo", "Carlos Drummond"], cor: 1 },
            { id: "LIN-LIT-007", cat: "Linguagens", sub: "Literatura", txt: "O Cortiço, de Aluísio Azevedo, é obra do:", opt: ["Romantismo", "Naturalismo", "Modernismo", "Simbolismo"], cor: 1 },
            { id: "LIN-LIT-008", cat: "Linguagens", sub: "Literatura", txt: "A Semana de Arte Moderna ocorreu em:", opt: ["1922", "1900", "1945", "1822"], cor: 0 },
            { id: "LIN-LIT-009", cat: "Linguagens", sub: "Literatura", txt: "Carlos Drummond de Andrade escreveu o poema:", opt: ["No meio do caminho", "Navio Negreiro", "I-Juca Pirama", "Canção do Exílio"], cor: 0 },
            { id: "LIN-LIT-010", cat: "Linguagens", sub: "Literatura", txt: "Iracema é uma obra de:", opt: ["José de Alencar", "Machado de Assis", "Lima Barreto", "Castro Alves"], cor: 0 },
            { id: "LIN-LIT-011", cat: "Linguagens", sub: "Literatura", txt: "O Parnasianismo buscava:", opt: ["Arte pela arte (perfeição formal)", "Crítica social", "Liberdade total", "Sonho"], cor: 0 },
            { id: "LIN-LIT-012", cat: "Linguagens", sub: "Literatura", txt: "Castro Alves é conhecido como:", opt: ["O Poeta dos Escravos", "O Poeta das Flores", "O Poeta Maldito", "O Poeta da Vila"], cor: 0 },
            { id: "LIN-LIT-013", cat: "Linguagens", sub: "Literatura", txt: "Quem escreveu 'A Hora da Estrela'?", opt: ["Clarice Lispector", "Cecília Meireles", "Raquel de Queiroz", "Lygia Fagundes"], cor: 0 },
            { id: "LIN-LIT-014", cat: "Linguagens", sub: "Literatura", txt: "Macunaíma é o herói:", opt: ["Sem nenhum caráter", "De mil faces", "Da pátria", "Do sertão"], cor: 0 },
            { id: "LIN-LIT-015", cat: "Linguagens", sub: "Literatura", txt: "O Quinhentismo refere-se a:", opt: ["Literatura feita no Brasil em 1500 (cartas)", "Ano de 500 d.C.", "500 poemas", "Século V"], cor: 0 },
            { id: "LIN-LIT-016", cat: "Linguagens", sub: "Literatura", txt: "O Arcadismo também é chamado de:", opt: ["Neoclassicismo", "Barroco Mineiro", "Trovadorismo", "Futurismo"], cor: 0 },
            { id: "LIN-LIT-017", cat: "Linguagens", sub: "Literatura", txt: "Fernando Pessoa é um poeta:", opt: ["Brasileiro", "Português", "Angolano", "Espanhol"], cor: 1 },
            { id: "LIN-LIT-018", cat: "Linguagens", sub: "Literatura", txt: "Os heterônimos (Alberto Caeiro, etc) são de:", opt: ["Fernando Pessoa", "Saramago", "Camões", "Eça de Queirós"], cor: 0 },
            { id: "LIN-LIT-019", cat: "Linguagens", sub: "Literatura", txt: "Os Lusíadas conta as viagens de:", opt: ["Vasco da Gama", "Colombo", "Cabral", "Ulisses"], cor: 0 },
            { id: "LIN-LIT-020", cat: "Linguagens", sub: "Literatura", txt: "Ariano Suassuna escreveu:", opt: ["O Auto da Compadecida", "Sítio do Picapau", "Turma da Mônica", "Gabriela"], cor: 0 },
            { id: "LIN-LIT-021", cat: "Linguagens", sub: "Literatura", txt: "Lima Barreto criticava:", opt: ["O preconceito racial e social na República Velha", "A monarquia", "Os índios", "A tecnologia"], cor: 0 },
            { id: "LIN-LIT-022", cat: "Linguagens", sub: "Literatura", txt: "O Barroco é caracterizado pelo:", opt: ["Conflito entre fé e razão (Dilema)", "Otimismo", "Simplicidade", "Ateísmo"], cor: 0 },
            { id: "LIN-LIT-023", cat: "Linguagens", sub: "Literatura", txt: "Cecília Meireles faz parte do:", opt: ["Modernismo", "Romantismo", "Arcadismo", "Concretismo"], cor: 0 },
            { id: "LIN-LIT-024", cat: "Linguagens", sub: "Literatura", txt: "A 'Geração de 45' buscava:", opt: ["Retorno à forma e disciplina na poesia", "Piada e anarquia", "Destruição da língua", "Copiar a Europa"], cor: 0 },
            { id: "LIN-LIT-025", cat: "Linguagens", sub: "Literatura", txt: "Capitães da Areia narra a vida de:", opt: ["Meninos de rua em Salvador", "Piratas", "Soldados", "Pescadores"], cor: 0 },
            { id: "LIN-LIT-026", cat: "Linguagens", sub: "Literatura", txt: "Autor de 'Memórias de um Sargento de Milícias':", opt: ["Manuel Antônio de Almeida", "Machado de Assis", "Alencar", "Bilac"], cor: 0 },
            { id: "LIN-LIT-027", cat: "Linguagens", sub: "Literatura", txt: "O Naturalismo foca no homem como:", opt: ["Produto do meio, raça e momento", "Ser divino", "Livre", "Romântico"], cor: 0 },
            { id: "LIN-LIT-028", cat: "Linguagens", sub: "Literatura", txt: "Augusto dos Anjos é conhecido como o poeta:", opt: ["Da morte e da ciência (Pré-Modernismo)", "Do amor", "Da natureza", "Da religião"], cor: 0 },
            { id: "LIN-LIT-029", cat: "Linguagens", sub: "Literatura", txt: "Euclides da Cunha escreveu:", opt: ["Os Sertões", "O Guarani", "Iracema", "Dom Casmurro"], cor: 0 },
            { id: "LIN-LIT-030", cat: "Linguagens", sub: "Literatura", txt: "O Concretismo valorizava:", opt: ["A forma visual do poema", "A rima perfeita", "O soneto", "O sentimentalismo"], cor: 0 },
            { id: "LIN-LIT-031", cat: "Linguagens", sub: "Literatura", txt: "João Cabral de Melo Neto escreveu:", opt: ["Morte e Vida Severina", "O Cortiço", "Memórias Póstumas", "Lira dos Vinte Anos"], cor: 0 },
            { id: "LIN-LIT-032", cat: "Linguagens", sub: "Literatura", txt: "Clarice Lispector pertence à:", opt: ["3ª Geração Modernista (Geração de 45)", "1ª Geração", "Romantismo", "Barroco"], cor: 0 },
            { id: "LIN-LIT-033", cat: "Linguagens", sub: "Literatura", txt: "O livro 'Quarto de Despejo' é de:", opt: ["Carolina Maria de Jesus", "Clarice Lispector", "Cecília Meireles", "Rachel de Queiroz"], cor: 0 },
            { id: "LIN-LIT-034", cat: "Linguagens", sub: "Literatura", txt: "Gregório de Matos tinha o apelido de:", opt: ["Boca do Inferno", "Boca de Ouro", "Poeta Santo", "O Grande"], cor: 0 },
            { id: "LIN-LIT-035", cat: "Linguagens", sub: "Literatura", txt: "O Trovadorismo surgiu na:", opt: ["Idade Média", "Idade Moderna", "Grécia Antiga", "Revolução Francesa"], cor: 0 },
            { id: "LIN-LIT-036", cat: "Linguagens", sub: "Literatura", txt: "Cantigas de Amigo têm eu-lírico:", opt: ["Feminino", "Masculino", "Neutro", "Plural"], cor: 0 },
            { id: "LIN-LIT-037", cat: "Linguagens", sub: "Literatura", txt: "Cantigas de Amor têm eu-lírico:", opt: ["Masculino (vassalagem amorosa)", "Feminino", "De Deus", "Da Natureza"], cor: 0 },
            { id: "LIN-LIT-038", cat: "Linguagens", sub: "Literatura", txt: "O Humanismo é a transição entre:", opt: ["Trovadorismo e Classicismo", "Barroco e Arcadismo", "Romantismo e Realismo", "Nada"], cor: 0 },
            { id: "LIN-LIT-039", cat: "Linguagens", sub: "Literatura", txt: "Gil Vicente escreveu:", opt: ["Auto da Barca do Inferno", "Os Lusíadas", "O Cortiço", "A Moreninha"], cor: 0 },
            { id: "LIN-LIT-040", cat: "Linguagens", sub: "Literatura", txt: "Padre Antônio Vieira é mestre dos:", opt: ["Sermões (Barroco)", "Sonetos", "Romances", "Contos"], cor: 0 },
            { id: "LIN-LIT-041", cat: "Linguagens", sub: "Literatura", txt: "O Simbolismo valoriza:", opt: ["A sugestão, musicalidade e mistério", "A descrição clara", "A ciência", "A política"], cor: 0 },
            { id: "LIN-LIT-042", cat: "Linguagens", sub: "Literatura", txt: "Cruz e Sousa é o principal poeta do:", opt: ["Simbolismo no Brasil", "Parnasianismo", "Romantismo", "Modernismo"], cor: 0 },
            { id: "LIN-LIT-043", cat: "Linguagens", sub: "Literatura", txt: "Oswald de Andrade defendia a:", opt: ["Antropofagia (devorar cultura estrangeira)", "Cópia da Europa", "Recusa do moderno", "Volta ao passado"], cor: 0 },
            { id: "LIN-LIT-044", cat: "Linguagens", sub: "Literatura", txt: "Mário de Andrade escreveu:", opt: ["Macunaíma", "Iracema", "O Guarani", "Dom Casmurro"], cor: 0 },
            { id: "LIN-LIT-045", cat: "Linguagens", sub: "Literatura", txt: "Ferreira Gullar escreveu o:", opt: ["Poema Sujo", "Poema Limpo", "Navio Negreiro", "I-Juca Pirama"], cor: 0 },
            { id: "LIN-LIT-046", cat: "Linguagens", sub: "Literatura", txt: "Cantigas de Maldizer (Trovadorismo) eram:", opt: ["Sátiras diretas com nomes", "Sátiras indiretas", "Poemas de amor", "Rezas"], cor: 0 },
            { id: "LIN-LIT-047", cat: "Linguagens", sub: "Literatura", txt: "Camões escreveu a epopeia:", opt: ["Os Lusíadas", "A Divina Comédia", "Ilíada", "Odisseia"], cor: 0 },
            { id: "LIN-LIT-048", cat: "Linguagens", sub: "Literatura", txt: "O Arcadismo usava pseudônimos de:", opt: ["Pastores gregos/latinos", "Reis", "Animais", "Deuses"], cor: 0 },
            { id: "LIN-LIT-049", cat: "Linguagens", sub: "Literatura", txt: "Gonçalves Dias escreveu:", opt: ["Canção do Exílio", "Navio Negreiro", "Iracema", "O Cortiço"], cor: 0 },
            { id: "LIN-LIT-050", cat: "Linguagens", sub: "Literatura", txt: "A 2ª Geração Romântica (Mal do Século) falava de:", opt: ["Morte, tédio e amor impossível", "Natureza e índio", "Questões sociais", "Alegria"], cor: 0 },
            { id: "LIN-LIT-051", cat: "Linguagens", sub: "Literatura", txt: "Machado de Assis fundou a:", opt: ["Academia Brasileira de Letras", "Semana de Arte Moderna", "Escola de Belas Artes", "Biblioteca Nacional"], cor: 0 },
            { id: "LIN-LIT-052", cat: "Linguagens", sub: "Literatura", txt: "O Realismo critica:", opt: ["A burguesia, o casamento e o clero", "Os pobres", "A monarquia", "A natureza"], cor: 0 },
            { id: "LIN-LIT-053", cat: "Linguagens", sub: "Literatura", txt: "O Ateneu (Raul Pompeia) é uma obra:", opt: ["Naturalista/Impressionista", "Romântica", "Barroca", "Simbolista"], cor: 0 },
            { id: "LIN-LIT-054", cat: "Linguagens", sub: "Literatura", txt: "Monteiro Lobato criticou a pintora:", opt: ["Anita Malfatti", "Tarsila do Amaral", "Frida Kahlo", "Lygia Clark"], cor: 0 },
            { id: "LIN-LIT-055", cat: "Linguagens", sub: "Literatura", txt: "Manuel Bandeira escreveu o poema:", opt: ["Vou-me embora pra Pasárgada", "No meio do caminho", "Rosa de Hiroshima", "Aquarela"], cor: 0 },
            { id: "LIN-LIT-056", cat: "Linguagens", sub: "Literatura", txt: "A 2ª Fase do Modernismo (1930) focou no:", opt: ["Romance regionalista e social", "Poema piada", "Soneto clássico", "Astronomia"], cor: 0 },
            { id: "LIN-LIT-057", cat: "Linguagens", sub: "Literatura", txt: "A cachorra Baleia aparece no livro:", opt: ["Vidas Secas", "Sagarana", "O Quinze", "Menino de Engenho"], cor: 0 },
            { id: "LIN-LIT-058", cat: "Linguagens", sub: "Literatura", txt: "Jorge Amado escreveu sobre:", opt: ["A cultura da Bahia e o ciclo do cacau", "O Rio Grande do Sul", "A Amazônia", "São Paulo"], cor: 0 },
            { id: "LIN-LIT-059", cat: "Linguagens", sub: "Literatura", txt: "Gabriela, Cravo e Canela é de:", opt: ["Jorge Amado", "Érico Veríssimo", "Graciliano Ramos", "Machado de Assis"], cor: 0 },
            { id: "LIN-LIT-060", cat: "Linguagens", sub: "Literatura", txt: "Guimarães Rosa revolucionou a literatura com:", opt: ["Neologismos e linguagem do sertão", "Poemas curtos", "Críticas políticas", "Histórias urbanas"], cor: 0 },
            { id: "LIN-LIT-061", cat: "Linguagens", sub: "Literatura", txt: "Vinicius de Moraes é conhecido como:", opt: ["O Poetinha", "O Boca do Inferno", "O Cisne Negro", "O Solitário"], cor: 0 },
            { id: "LIN-LIT-062", cat: "Linguagens", sub: "Literatura", txt: "A Literatura de Cordel é típica do:", opt: ["Nordeste", "Sul", "Sudeste", "Norte"], cor: 0 },
            { id: "LIN-LIT-063", cat: "Linguagens", sub: "Literatura", txt: "Ariano Suassuna criou o movimento:", opt: ["Armorial", "Antropofágico", "Concretista", "Tropicalista"], cor: 0 },
            { id: "LIN-LIT-064", cat: "Linguagens", sub: "Literatura", txt: "Rubem Fonseca é famoso por seus:", opt: ["Contos policiais e urbanos", "Poemas de amor", "Romances históricos", "Fábulas"], cor: 0 },
            { id: "LIN-LIT-065", cat: "Linguagens", sub: "Literatura", txt: "Paulo Coelho escreveu:", opt: ["O Alquimista", "Dom Casmurro", "A Moreninha", "O Príncipe"], cor: 0 },
            { id: "LIN-LIT-066", cat: "Linguagens", sub: "Literatura", txt: "José Saramago (Nobel de Literatura) é:", opt: ["Português", "Brasileiro", "Angolano", "Moçambicano"], cor: 0 },
            { id: "LIN-LIT-067", cat: "Linguagens", sub: "Literatura", txt: "O Ensaio sobre a Cegueira é de:", opt: ["José Saramago", "Pessoa", "Machado", "Veríssimo"], cor: 0 },
            { id: "LIN-LIT-068", cat: "Linguagens", sub: "Literatura", txt: "Mia Couto é um escritor de:", opt: ["Moçambique", "Portugal", "Brasil", "Cabo Verde"], cor: 0 },
            { id: "LIN-LIT-069", cat: "Linguagens", sub: "Literatura", txt: "O Tropicalismo teve influência na:", opt: ["Música e Cultura (anos 60)", "Pintura apenas", "Arquitetura", "Dança"], cor: 0 },
            { id: "LIN-LIT-070", cat: "Linguagens", sub: "Literatura", txt: "Caetano Veloso e Gilberto Gil são do:", opt: ["Tropicalismo", "Modernismo", "Parnasianismo", "Barroco"], cor: 0 },
            { id: "LIN-LIT-071", cat: "Linguagens", sub: "Literatura", txt: "Lygia Fagundes Telles é famosa por:", opt: ["Contos e Romances (Ciranda de Pedra)", "Poesia Concreta", "Cordel", "Teatro"], cor: 0 },
            { id: "LIN-LIT-072", cat: "Linguagens", sub: "Literatura", txt: "O 'Poema Piada' é característica do:", opt: ["Modernismo (1ª Fase)", "Barroco", "Arcadismo", "Realismo"], cor: 0 },
            { id: "LIN-LIT-073", cat: "Linguagens", sub: "Literatura", txt: "Augusto de Campos é do movimento:", opt: ["Poesia Concreta", "Romantismo", "Simbolismo", "Parnasianismo"], cor: 0 },
            { id: "LIN-LIT-074", cat: "Linguagens", sub: "Literatura", txt: "Paulo Leminski é conhecido pelos:", opt: ["Haikais e poemas curtos", "Romances longos", "Sermões", "Dramas"], cor: 0 },
            { id: "LIN-LIT-075", cat: "Linguagens", sub: "Literatura", txt: "Adélia Prado destaca-se pela:", opt: ["Poesia feminina e religiosa/cotidiana", "Crítica política", "Ficção científica", "Terror"], cor: 0 },
            { id: "LIN-LIT-076", cat: "Linguagens", sub: "Literatura", txt: "O Auto da Compadecida é uma peça de:", opt: ["Teatro", "Romance", "Conto", "Crônica"], cor: 0 },
            { id: "LIN-LIT-077", cat: "Linguagens", sub: "Literatura", txt: "Nelson Rodrigues revolucionou o:", opt: ["Teatro Brasileiro (Moderno)", "Cinema", "Rádio", "Jornal"], cor: 0 },
            { id: "LIN-LIT-078", cat: "Linguagens", sub: "Literatura", txt: "Carolina Maria de Jesus narrou a favela em:", opt: ["Diário", "Poesia", "Música", "Pintura"], cor: 0 },
            { id: "LIN-LIT-079", cat: "Linguagens", sub: "Literatura", txt: "Conceição Evaristo criou o conceito de:", opt: ["Escrevivência", "Negritude", "Antropofagia", "Sertanejo"], cor: 0 },
            { id: "LIN-LIT-080", cat: "Linguagens", sub: "Literatura", txt: "O Sítio do Picapau Amarelo mistura:", opt: ["Folclore e Fantasia", "Terror e Suspense", "História Real", "Ficção Científica"], cor: 0 },
            { id: "LIN-LIT-081", cat: "Linguagens", sub: "Literatura", txt: "Hilda Hilst escreveu obras de:", opt: ["Poesia, Prosa e Teatro (temas profundos)", "Infantil", "Humor", "Didático"], cor: 0 },
            { id: "LIN-LIT-082", cat: "Linguagens", sub: "Literatura", txt: "O livro 'Torto Arado' (atual) é de:", opt: ["Itamar Vieira Junior", "Paulo Coelho", "Jorge Amado", "Machado"], cor: 0 },
            { id: "LIN-LIT-083", cat: "Linguagens", sub: "Literatura", txt: "A literatura periférica/marginal surge nas:", opt: ["Favelas e periferias urbanas", "Universidades", "Igrejas", "Fazendas"], cor: 0 },
            { id: "LIN-LIT-084", cat: "Linguagens", sub: "Literatura", txt: "O Slam é uma competição de:", opt: ["Poesia falada", "Dança", "Pintura", "Culinária"], cor: 0 },
            { id: "LIN-LIT-085", cat: "Linguagens", sub: "Literatura", txt: "Machado de Assis é frequentemente chamado de:", opt: ["O Bruxo do Cosme Velho", "O Poeta dos Escravos", "O Boca do Inferno", "O Príncipe"], cor: 0 },
            { id: "LIN-LIT-086", cat: "Linguagens", sub: "Literatura", txt: "O Tempo e o Vento é a obra máxima de:", opt: ["Érico Veríssimo", "Jorge Amado", "Graciliano Ramos", "Machado"], cor: 0 },
            { id: "LIN-LIT-087", cat: "Linguagens", sub: "Literatura", txt: "Raul Pompeia escreveu:", opt: ["O Ateneu", "O Cortiço", "A Moreninha", "Iracema"], cor: 0 },
            { id: "LIN-LIT-088", cat: "Linguagens", sub: "Literatura", txt: "O Pré-Modernismo é uma fase de:", opt: ["Transição e denúncia social", "Cópia da Europa", "Volta ao clássico", "Fim da arte"], cor: 0 },
            { id: "LIN-LIT-089", cat: "Linguagens", sub: "Literatura", txt: "Chacal e Paulo Leminski são da:", opt: ["Poesia Marginal (anos 70)", "Geração de 45", "Semana de 22", "Academia"], cor: 0 },
            { id: "LIN-LIT-090", cat: "Linguagens", sub: "Literatura", txt: "Vestido de Noiva (Nelson Rodrigues) revolucionou:", opt: ["O teatro moderno", "O cinema", "A TV", "O rádio"], cor: 0 },
            { id: "LIN-LIT-091", cat: "Linguagens", sub: "Literatura", txt: "Leonardo é o primeiro 'malandro' em:", opt: ["Memórias de um Sargento de Milícias", "Macunaíma", "Dom Casmurro", "Senhora"], cor: 0 },
            { id: "LIN-LIT-092", cat: "Linguagens", sub: "Literatura", txt: "A grande dúvida de Dom Casmurro é:", opt: ["Se Capitu traiu Bentinho", "Se ele vai morrer", "Se Escobar é rico", "Se Capitu fugiu"], cor: 0 },
            { id: "LIN-LIT-093", cat: "Linguagens", sub: "Literatura", txt: "Iracema é um anagrama de:", opt: ["América", "Ceara", "Aricema", "Racismo"], cor: 0 },
            { id: "LIN-LIT-094", cat: "Linguagens", sub: "Literatura", txt: "A dualidade (céu x inferno) é típica do:", opt: ["Barroco", "Arcadismo", "Realismo", "Modernismo"], cor: 0 },
            { id: "LIN-LIT-095", cat: "Linguagens", sub: "Literatura", txt: "Carpe Diem (Aproveite o dia) é lema do:", opt: ["Arcadismo", "Barroco", "Simbolismo", "Romantismo"], cor: 0 },
            { id: "LIN-LIT-096", cat: "Linguagens", sub: "Literatura", txt: "O Indianismo romântico mostra o índio como:", opt: ["Herói nacional idealizado", "Vilão", "Vítima", "Escravo"], cor: 0 },
            { id: "LIN-LIT-097", cat: "Linguagens", sub: "Literatura", txt: "O Realismo foca na análise:", opt: ["Psicológica e social", "Dos sonhos", "Da natureza", "De Deus"], cor: 0 },
            { id: "LIN-LIT-098", cat: "Linguagens", sub: "Literatura", txt: "O Parnasianismo comparava o poema a um:", opt: ["Vaso grego (arte trabalhada)", "Rio", "Pássaro", "Grito"], cor: 0 },
            { id: "LIN-LIT-099", cat: "Linguagens", sub: "Literatura", txt: "Cruz e Sousa usava a cor branca para simbolizar:", opt: ["Espiritualidade/Morte", "Alegria", "Guerra", "Natureza"], cor: 0 },
            { id: "LIN-LIT-100", cat: "Linguagens", sub: "Literatura", txt: "Macunaíma comeu a:", opt: ["Cultura europeia (Antropofagia)", "Feijoada", "Maçã", "Cidade"], cor: 0 },


];
