export const questoes = [
            // --- SUB: ÁLGEBRA ---
            { id: "MAT-ALG-001", cat: "Matemática", sub: "Álgebra", txt: "Raiz de 2x - 4 = 0:", opt: ["1", "2", "4", "-2"], cor: 1 },
            { id: "MAT-ALG-002", cat: "Matemática", sub: "Álgebra", txt: "Bhaskara resolve equações de:", opt: ["1º Grau", "2º Grau", "3º Grau", "Exponencial"], cor: 1 },
            { id: "MAT-ALG-003", cat: "Matemática", sub: "Álgebra", txt: "O próximo termo da P.A. (2, 5, 8...) é:", opt: ["10", "11", "12", "13"], cor: 1 },
            { id: "MAT-ALG-004", cat: "Matemática", sub: "Álgebra", txt: "Logaritmo de 100 na base 10:", opt: ["1", "2", "10", "100"], cor: 1 },
            { id: "MAT-ALG-005", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = 2x + 1, qual o valor de f(3)?", opt: ["5", "6", "7", "8"], cor: 2 },
            { id: "MAT-ALG-006", cat: "Matemática", sub: "Álgebra", txt: "Qual é o valor de 3 fatorial (3!)?", opt: ["3", "6", "9", "1"], cor: 1 },
            { id: "MAT-ALG-007", cat: "Matemática", sub: "Álgebra", txt: "O resultado de (a + b)² é:", opt: ["a² + b²", "a² - b²", "a² + 2ab + b²", "2a + 2b"], cor: 2 },
            { id: "MAT-ALG-008", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de x em 3x + 1 = x + 11?", opt: ["2", "3", "4", "5"], cor: 3 },
            { id: "MAT-ALG-009", cat: "Matemática", sub: "Álgebra", txt: "Qualquer número elevado a zero é igual a:", opt: ["0", "1", "Ele mesmo", "Infinito"], cor: 1 },
            { id: "MAT-ALG-010", cat: "Matemática", sub: "Álgebra", txt: "A função f(x) = x² representa uma:", opt: ["Reta", "Hipérbole", "Parábola", "Elipse"], cor: 2 },
            { id: "MAT-ALG-011", cat: "Matemática", sub: "Álgebra", txt: "Se x = -2, quanto vale x²?", opt: ["-4", "4", "-2", "0"], cor: 1 },
            { id: "MAT-ALG-012", cat: "Matemática", sub: "Álgebra", txt: "O discriminante (Delta) de uma equação de 2º grau é:", opt: ["b² - 4ac", "-b / 2a", "c / a", "a + b + c"], cor: 0 },
            { id: "MAT-ALG-013", cat: "Matemática", sub: "Álgebra", txt: "Fatorando x² - 9, temos:", opt: ["(x-3)(x-3)", "(x+3)(x-3)", "(x+9)(x-9)", "x(x-9)"], cor: 1 },
            { id: "MAT-ALG-014", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 2³?", opt: ["6", "8", "9", "12"], cor: 1 },
            { id: "MAT-ALG-015", cat: "Matemática", sub: "Álgebra", txt: "Inequação: Se -x > 5, então:", opt: ["x > 5", "x < 5", "x > -5", "x < -5"], cor: 3 },
            { id: "MAT-ALG-016", cat: "Matemática", sub: "Álgebra", txt: "O coeficiente linear da reta y = 3x + 2 é:", opt: ["3", "2", "x", "y"], cor: 1 },
            { id: "MAT-ALG-017", cat: "Matemática", sub: "Álgebra", txt: "Resolva o sistema: x+y=10 e x-y=2.", opt: ["x=5, y=5", "x=6, y=4", "x=7, y=3", "x=8, y=2"], cor: 1 },
            { id: "MAT-ALG-018", cat: "Matemática", sub: "Álgebra", txt: "O produto (x+1)(x-1) resulta em:", opt: ["x² + 1", "x² - 1", "x² + 2x + 1", "x² - 2x + 1"], cor: 1 },
            { id: "MAT-ALG-019", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 5⁰?", opt: ["0", "1", "5", "Indefinido"], cor: 1 },
            { id: "MAT-ALG-020", cat: "Matemática", sub: "Álgebra", txt: "O vértice de uma parábola y=x² fica em:", opt: ["(0,0)", "(1,1)", "(0,1)", "(1,0)"], cor: 0 },
            { id: "MAT-ALG-021", cat: "Matemática", sub: "Álgebra", txt: "Se 2x = 1/2, então x vale:", opt: ["1", "0,5", "0,25", "2"], cor: 2 },
            { id: "MAT-ALG-022", cat: "Matemática", sub: "Álgebra", txt: "A expressão b² - 4ac < 0 indica que a equação:", opt: ["Tem 2 raízes reais", "Tem 1 raiz real", "Não tem raiz real", "É nula"], cor: 2 },
            { id: "MAT-ALG-023", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de x em √x = 9?", opt: ["3", "18", "81", "90"], cor: 2 },
            { id: "MAT-ALG-024", cat: "Matemática", sub: "Álgebra", txt: "A sequência (2, 4, 8, 16...) é uma:", opt: ["P.A.", "P.G.", "Fatorial", "Constante"], cor: 1 },
            { id: "MAT-ALG-025", cat: "Matemática", sub: "Álgebra", txt: "O inverso de 2/3 é:", opt: ["-2/3", "3/2", "1", "0"], cor: 1 },
            { id: "MAT-ALG-026", cat: "Matemática", sub: "Álgebra", txt: "Simplifique: (x³)/(x²)", opt: ["x", "x⁵", "1", "x⁻¹"], cor: 0 },
            { id: "MAT-ALG-027", cat: "Matemática", sub: "Álgebra", txt: "A equação x² + 1 = 0 tem solução em:", opt: ["Reais", "Inteiros", "Complexos", "Naturais"], cor: 2 },
            { id: "MAT-ALG-028", cat: "Matemática", sub: "Álgebra", txt: "Fatore: x² + 2x + 1", opt: ["(x+1)²", "(x-1)²", "x(x+2)", "(x+2)(x+1)"], cor: 0 },
            { id: "MAT-ALG-029", cat: "Matemática", sub: "Álgebra", txt: "Se 3x + 5 = 20, x é:", opt: ["3", "4", "5", "6"], cor: 2 },
            { id: "MAT-ALG-030", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de |-5| (módulo)?", opt: ["-5", "5", "0", "1"], cor: 1 },
            { id: "MAT-ALG-031", cat: "Matemática", sub: "Álgebra", txt: "Logaritmo de 1 em qualquer base é:", opt: ["0", "1", "A base", "Infinito"], cor: 0 },
            { id: "MAT-ALG-032", cat: "Matemática", sub: "Álgebra", txt: "O gráfico de uma função de 1º grau é uma:", opt: ["Curva", "Reta", "Onda", "Círculo"], cor: 1 },
            { id: "MAT-ALG-033", cat: "Matemática", sub: "Álgebra", txt: "Qual o M.M.C de 3 e 4?", opt: ["7", "12", "1", "34"], cor: 1 },
            { id: "MAT-ALG-034", cat: "Matemática", sub: "Álgebra", txt: "O valor de 4! (fatorial) é:", opt: ["4", "16", "24", "10"], cor: 2 },
            { id: "MAT-ALG-035", cat: "Matemática", sub: "Álgebra", txt: "Na equação y = ax + b, 'b' indica:", opt: ["Inclinação", "Interseção com eixo Y", "Raiz", "Vértice"], cor: 1 },
            { id: "MAT-ALG-036", cat: "Matemática", sub: "Álgebra", txt: "Se x/3 = 4, então x é:", opt: ["7", "1", "12", "0.75"], cor: 2 },
            { id: "MAT-ALG-037", cat: "Matemática", sub: "Álgebra", txt: "Qual destes é um número irracional?", opt: ["2", "0,5", "√2", "1/3"], cor: 2 },
            { id: "MAT-ALG-038", cat: "Matemática", sub: "Álgebra", txt: "Desenvolva (x - 2)²:", opt: ["x² - 4", "x² - 4x + 4", "x² + 4", "x² - 2x + 4"], cor: 1 },
            { id: "MAT-ALG-039", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = x², f(-3) é:", opt: ["-9", "9", "6", "-6"], cor: 1 },
            { id: "MAT-ALG-040", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 2 elevado a -1?", opt: ["-2", "0", "0.5", "1"], cor: 2 },
            { id: "MAT-ALG-041", cat: "Matemática", sub: "Álgebra", txt: "Se x + y = 7 e x - y = 1, qual o valor de x?", opt: ["3", "4", "5", "6"], cor: 1 },
            { id: "MAT-ALG-042", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 3 elevado a 3?", opt: ["6", "9", "27", "81"], cor: 2 },
            { id: "MAT-ALG-043", cat: "Matemática", sub: "Álgebra", txt: "A raiz quadrada de 144 é:", opt: ["10", "11", "12", "14"], cor: 2 },
            { id: "MAT-ALG-044", cat: "Matemática", sub: "Álgebra", txt: "O conjunto dos números Z representa os:", opt: ["Naturais", "Inteiros", "Racionais", "Reais"], cor: 1 },
            { id: "MAT-ALG-045", cat: "Matemática", sub: "Álgebra", txt: "Se 4x = 100, x vale:", opt: ["20", "25", "40", "10"], cor: 1 },
            { id: "MAT-ALG-046", cat: "Matemática", sub: "Álgebra", txt: "A expressão a² - b² é uma:", opt: ["Diferença de quadrados", "Soma de cubos", "Trinômio perfeito", "Fatoração simples"], cor: 0 },
            { id: "MAT-ALG-047", cat: "Matemática", sub: "Álgebra", txt: "Qual o MDC de 10 e 20?", opt: ["2", "5", "10", "20"], cor: 2 },
            { id: "MAT-ALG-048", cat: "Matemática", sub: "Álgebra", txt: "Se log₂ x = 3, então x é:", opt: ["6", "8", "9", "5"], cor: 1 },
            { id: "MAT-ALG-049", cat: "Matemática", sub: "Álgebra", txt: "O gráfico de f(x) = 2 é uma reta:", opt: ["Crescente", "Decrescente", "Horizontal", "Vertical"], cor: 2 },
            { id: "MAT-ALG-050", cat: "Matemática", sub: "Álgebra", txt: "Qual a soma das raízes de x² - 5x + 6 = 0?", opt: ["-5", "5", "6", "-6"], cor: 1 },
            { id: "MAT-ALG-051", cat: "Matemática", sub: "Álgebra", txt: "Qual o produto das raízes de x² - 5x + 6 = 0?", opt: ["5", "-5", "6", "-6"], cor: 2 },
            { id: "MAT-ALG-052", cat: "Matemática", sub: "Álgebra", txt: "A notação 5! significa:", opt: ["5+4+3+2+1", "5x4x3x2x1", "5^5", "5x5"], cor: 1 },
            { id: "MAT-ALG-053", cat: "Matemática", sub: "Álgebra", txt: "Em uma PA de razão 2, se a1=10, a2 é:", opt: ["8", "11", "12", "20"], cor: 2 },
            { id: "MAT-ALG-054", cat: "Matemática", sub: "Álgebra", txt: "Em uma PG de razão 3, se a1=2, a2 é:", opt: ["5", "6", "8", "9"], cor: 1 },
            { id: "MAT-ALG-055", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 100⁰ + 10¹?", opt: ["10", "11", "20", "101"], cor: 1 },
            { id: "MAT-ALG-056", cat: "Matemática", sub: "Álgebra", txt: "O determinante da matriz identidade é:", opt: ["0", "1", "-1", "Varia"], cor: 1 },
            { id: "MAT-ALG-057", cat: "Matemática", sub: "Álgebra", txt: "A desigualdade |x| < 3 significa:", opt: ["x < 3", "x > -3", "-3 < x < 3", "x > 3"], cor: 2 },
            { id: "MAT-ALG-058", cat: "Matemática", sub: "Álgebra", txt: "O número 'Pi' (π) é:", opt: ["Racional", "Inteiro", "Irracional", "Imaginário"], cor: 2 },
            { id: "MAT-ALG-059", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = 3x - 1, a raiz é:", opt: ["1", "3", "1/3", "-1/3"], cor: 2 },
            { id: "MAT-ALG-060", cat: "Matemática", sub: "Álgebra", txt: "Qual a representação de 'i' nos complexos?", opt: ["√-1", "-1", "1", "√1"], cor: 0 },
            { id: "MAT-ALG-061", cat: "Matemática", sub: "Álgebra", txt: "A fatoração de a² + 2ab + b² é:", opt: ["(a-b)²", "(a+b)²", "(a+b)(a-b)", "a²+b²"], cor: 1 },
            { id: "MAT-ALG-062", cat: "Matemática", sub: "Álgebra", txt: "Se x³ = 27, x vale:", opt: ["3", "9", "27", "6"], cor: 0 },
            { id: "MAT-ALG-063", cat: "Matemática", sub: "Álgebra", txt: "O domínio da função f(x) = 1/x exclui o:", opt: ["1", "0", "-1", "2"], cor: 1 },
            { id: "MAT-ALG-064", cat: "Matemática", sub: "Álgebra", txt: "Qual a lei da função constante?", opt: ["f(x) = x", "f(x) = k", "f(x) = x²", "f(x) = ax+b"], cor: 1 },
            { id: "MAT-ALG-065", cat: "Matemática", sub: "Álgebra", txt: "Raiz quadrada de 64 + Raiz de 36 é:", opt: ["100", "10", "14", "12"], cor: 2 },
            { id: "MAT-ALG-066", cat: "Matemática", sub: "Álgebra", txt: "Se 2^(x+1) = 8, x é:", opt: ["1", "2", "3", "4"], cor: 1 },
            { id: "MAT-ALG-067", cat: "Matemática", sub: "Álgebra", txt: "Logaritmo de produto log(a.b) vira:", opt: ["log a . log b", "log a + log b", "log a - log b", "b . log a"], cor: 1 },
            { id: "MAT-ALG-068", cat: "Matemática", sub: "Álgebra", txt: "O que é uma raiz dupla numa eq. de 2º grau?", opt: ["Delta < 0", "Delta > 0", "Delta = 0", "a = 0"], cor: 2 },
            { id: "MAT-ALG-069", cat: "Matemática", sub: "Álgebra", txt: "Na função afim f(x) = -x + 2, ela é:", opt: ["Crescente", "Decrescente", "Constante", "Quadrática"], cor: 1 },
            { id: "MAT-ALG-070", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de (-2)³?", opt: ["8", "-8", "6", "-6"], cor: 1 },
            { id: "MAT-ALG-071", cat: "Matemática", sub: "Álgebra", txt: "Se y = 5x e y = 10, x é:", opt: ["2", "5", "10", "50"], cor: 0 },
            { id: "MAT-ALG-072", cat: "Matemática", sub: "Álgebra", txt: "A soma de um número com seu inverso é x + 1/x. Se x=2:", opt: ["2.5", "1.5", "3", "4"], cor: 0 },
            { id: "MAT-ALG-073", cat: "Matemática", sub: "Álgebra", txt: "O grau do polinômio x³ + 2x² - 1 é:", opt: ["1", "2", "3", "4"], cor: 2 },
            { id: "MAT-ALG-074", cat: "Matemática", sub: "Álgebra", txt: "Se √x = 5, então x é:", opt: ["5", "10", "25", "50"], cor: 2 },
            { id: "MAT-ALG-075", cat: "Matemática", sub: "Álgebra", txt: "Matriz transposta troca:", opt: ["Sinal", "Linha por Coluna", "Zeros por Uns", "Apenas a diagonal"], cor: 1 },
            { id: "MAT-ALG-076", cat: "Matemática", sub: "Álgebra", txt: "Numa P.A. de razão 0, a sequência é:", opt: ["Crescente", "Decrescente", "Constante", "Nula"], cor: 2 },
            { id: "MAT-ALG-077", cat: "Matemática", sub: "Álgebra", txt: "O valor de (3²)³ é:", opt: ["3⁵", "3⁶", "3⁸", "3⁹"], cor: 1 },
            { id: "MAT-ALG-078", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = x + 3, a função inversa f⁻¹(x) é:", opt: ["x - 3", "3 - x", "3x", "x/3"], cor: 0 },
            { id: "MAT-ALG-079", cat: "Matemática", sub: "Álgebra", txt: "Qual o valor de 7! / 6! ?", opt: ["1", "6", "7", "42"], cor: 2 },
            { id: "MAT-ALG-080", cat: "Matemática", sub: "Álgebra", txt: "A equação de 2º grau incompleta ax² + c = 0 tem:", opt: ["Raízes opostas", "Uma raiz nula", "Nenhuma raiz", "Raízes iguais"], cor: 0 },
            { id: "MAT-ALG-081", cat: "Matemática", sub: "Álgebra", txt: "Logaritmo de produto vira:", opt: ["Produto de logs", "Soma de logs", "Divisão de logs", "Subtração"], cor: 1 },
            { id: "MAT-ALG-082", cat: "Matemática", sub: "Álgebra", txt: "Logaritmo de divisão vira:", opt: ["Soma", "Subtração", "Multiplicação", "Exponenciação"], cor: 1 },
            { id: "MAT-ALG-083", cat: "Matemática", sub: "Álgebra", txt: "Matriz transposta é:", opt: ["Trocar sinal", "Trocar linha por coluna", "Inverter ordem", "Matriz nula"], cor: 1 },
            { id: "MAT-ALG-084", cat: "Matemática", sub: "Álgebra", txt: "A soma dos termos de uma P.A. finita é:", opt: ["(a1+an).n/2", "a1.q^n", "n(n+1)", "a1+an"], cor: 0 },
            { id: "MAT-ALG-085", cat: "Matemática", sub: "Álgebra", txt: "Soma dos termos de uma P.G. infinita (0 < q < 1):", opt: ["a1/(1-q)", "a1.q", "Infinito", "Zero"], cor: 0 },
            { id: "MAT-ALG-086", cat: "Matemática", sub: "Álgebra", txt: "O conjugado de z = 2 + 3i é:", opt: ["2 - 3i", "-2 + 3i", "-2 - 3i", "3 + 2i"], cor: 0 },
            { id: "MAT-ALG-087", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = x³ - 1, f(2) vale:", opt: ["5", "6", "7", "8"], cor: 2 },
            { id: "MAT-ALG-088", cat: "Matemática", sub: "Álgebra", txt: "Qual o MDC de 8 e 12?", opt: ["2", "4", "8", "24"], cor: 1 },
            { id: "MAT-ALG-089", cat: "Matemática", sub: "Álgebra", txt: "O MMC de 5 e 7 (primos) é:", opt: ["12", "35", "1", "7"], cor: 1 },
            { id: "MAT-ALG-090", cat: "Matemática", sub: "Álgebra", txt: "Se |x-2| = 5, x pode ser:", opt: ["7 ou -3", "7 apenas", "-3 apenas", "3 ou -7"], cor: 0 },
            { id: "MAT-ALG-091", cat: "Matemática", sub: "Álgebra", txt: "Equação da reta que passa na origem:", opt: ["y = ax + b", "y = ax", "y = b", "x = a"], cor: 1 },
            { id: "MAT-ALG-092", cat: "Matemática", sub: "Álgebra", txt: "Se o determinante é zero, o sistema linear é:", opt: ["SPD", "SPI ou SI", "Sempre SI", "Sempre SPI"], cor: 1 },
            { id: "MAT-ALG-093", cat: "Matemática", sub: "Álgebra", txt: "Fatorial de 0 (0!) é:", opt: ["0", "1", "Indefinido", "-1"], cor: 1 },
            { id: "MAT-ALG-094", cat: "Matemática", sub: "Álgebra", txt: "Análise Combinatória: A ordem importa em:", opt: ["Combinação", "Arranjo", "Conjunto", "Soma"], cor: 1 },
            { id: "MAT-ALG-095", cat: "Matemática", sub: "Álgebra", txt: "Combinação C(5,2) resulta em:", opt: ["10", "20", "5", "60"], cor: 0 },
            { id: "MAT-ALG-096", cat: "Matemática", sub: "Álgebra", txt: "Binômio de Newton estuda potências de:", opt: ["(a+b)ⁿ", "a²+b²", "a.b", "log x"], cor: 0 },
            { id: "MAT-ALG-097", cat: "Matemática", sub: "Álgebra", txt: "O grau do polinômio nulo é:", opt: ["0", "1", "Indefinido", "-1"], cor: 2 },
            { id: "MAT-ALG-098", cat: "Matemática", sub: "Álgebra", txt: "Se 3x > 9, então:", opt: ["x > 3", "x > 2", "x < 3", "x = 3"], cor: 0 },
            { id: "MAT-ALG-099", cat: "Matemática", sub: "Álgebra", txt: "Raiz cúbica de -8 é:", opt: ["2", "-2", "Não existe em R", "4"], cor: 1 },
            { id: "MAT-ALG-100", cat: "Matemática", sub: "Álgebra", txt: "Se f(x) = k (constante), o gráfico é:", opt: ["Reta horizontal", "Reta vertical", "Parábola", "Ponto"], cor: 0 },
    
          ];
