export const questoes = [
            // --- SUB: ESTATÍSTICA ---
            { id: "MAT-EST-001", cat: "Matemática", sub: "Estatística", txt: "A média de 4, 6 e 8 é:", opt: ["5", "6", "7", "8"], cor: 1 },
            { id: "MAT-EST-002", cat: "Matemática", sub: "Estatística", txt: "A probabilidade de tirar 'Cara' numa moeda justa:", opt: ["25%", "50%", "75%", "100%"], cor: 1 },
            { id: "MAT-EST-003", cat: "Matemática", sub: "Estatística", txt: "O valor que mais se repete em um conjunto é a:", opt: ["Média", "Mediana", "Moda", "Variância"], cor: 2 },
            { id: "MAT-EST-004", cat: "Matemática", sub: "Estatística", txt: "Ao lançar um dado, chance de sair número 7:", opt: ["0%", "16%", "50%", "100%"], cor: 0 },
            { id: "MAT-EST-005", cat: "Matemática", sub: "Estatística", txt: "A mediana do conjunto {2, 5, 8, 10, 12} é:", opt: ["5", "8", "10", "7.5"], cor: 1 },
            { id: "MAT-EST-006", cat: "Matemática", sub: "Estatística", txt: "Num gráfico de setores, o círculo completo vale:", opt: ["90°", "100%", "360°", "180°"], cor: 2 },
            { id: "MAT-EST-007", cat: "Matemática", sub: "Estatística", txt: "Média Ponderada leva em conta:", opt: ["Apenas a soma", "Os pesos dos valores", "O maior valor", "O menor valor"], cor: 1 },
            { id: "MAT-EST-008", cat: "Matemática", sub: "Estatística", txt: "Amplitude de um conjunto é a diferença entre:", opt: ["Média e Moda", "Maior e Menor valor", "Primeiro e Último", "Positivos e Negativos"], cor: 1 },
            { id: "MAT-EST-009", cat: "Matemática", sub: "Estatística", txt: "Probabilidade de sair número par num dado de 6 lados:", opt: ["1/6", "1/2", "1/3", "2/3"], cor: 1 },
            { id: "MAT-EST-010", cat: "Matemática", sub: "Estatística", txt: "Se a frequência de um evento é 100%, ele é:", opt: ["Impossível", "Provável", "Certo", "Aleatório"], cor: 2 },
            { id: "MAT-EST-011", cat: "Matemática", sub: "Estatística", txt: "Num dado viciado, se o 6 sai 50% das vezes, a probabilidade é:", opt: ["1/6", "1/2", "1/3", "1/5"], cor: 1 },
            { id: "MAT-EST-012", cat: "Matemática", sub: "Estatística", txt: "Para calcular a média aritmética:", opt: ["Multiplica e divide", "Soma tudo e divide pela quantidade", "Pega o valor do meio", "Subtrai o menor do maior"], cor: 1 },
            { id: "MAT-EST-013", cat: "Matemática", sub: "Estatística", txt: "A chance de tirar 'coroa' em 2 moedas seguidas:", opt: ["50%", "25%", "10%", "100%"], cor: 1 },
            { id: "MAT-EST-014", cat: "Matemática", sub: "Estatística", txt: "O desvio padrão mede:", opt: ["A média", "O centro", "A dispersão dos dados", "A soma"], cor: 2 },
            { id: "MAT-EST-015", cat: "Matemática", sub: "Estatística", txt: "Qual gráfico usa 'fatias'?", opt: ["Barras", "Linhas", "Setores (Pizza)", "Dispersão"], cor: 2 },
            { id: "MAT-EST-016", cat: "Matemática", sub: "Estatística", txt: "Uma amostra representa:", opt: ["Toda a população", "Uma parte da população", "Um erro de cálculo", "O censo"], cor: 1 },
            { id: "MAT-EST-017", cat: "Matemática", sub: "Estatística", txt: "Se a média é 5 e a soma é 20, quantos elementos têm?", opt: ["4", "5", "10", "15"], cor: 0 },
            { id: "MAT-EST-018", cat: "Matemática", sub: "Estatística", txt: "Em probabilidade, o evento 'impossível' vale:", opt: ["1", "0,5", "0", "-1"], cor: 2 },
            { id: "MAT-EST-019", cat: "Matemática", sub: "Estatística", txt: "Histograma é um gráfico de:", opt: ["Barras coladas", "Linhas curvas", "Pontos", "Pizza"], cor: 0 },
            { id: "MAT-EST-020", cat: "Matemática", sub: "Estatística", txt: "Moda do conjunto {1, 2, 2, 3, 4}:", opt: ["1", "2", "3", "4"], cor: 1 },
            { id: "MAT-EST-021", cat: "Matemática", sub: "Estatística", txt: "A soma das probabilidades de todos eventos possíveis é:", opt: ["0", "0,5", "1", "100"], cor: 2 },
            { id: "MAT-EST-022", cat: "Matemática", sub: "Estatística", txt: "Qual a chance de tirar um Ás num baralho de 52 cartas?", opt: ["1/13", "1/52", "4/13", "1/2"], cor: 0 },
            { id: "MAT-EST-023", cat: "Matemática", sub: "Estatística", txt: "Variável 'Cor dos olhos' é:", opt: ["Quantitativa", "Qualitativa", "Numérica", "Discreta"], cor: 1 },
            { id: "MAT-EST-024", cat: "Matemática", sub: "Estatística", txt: "Variável 'Altura' é:", opt: ["Qualitativa", "Quantitativa Contínua", "Discreta", "Nominal"], cor: 1 },
            { id: "MAT-EST-025", cat: "Matemática", sub: "Estatística", txt: "O Rol é:", opt: ["Dados organizados em ordem", "Dados bagunçados", "A média", "O gráfico"], cor: 0 },
            { id: "MAT-EST-026", cat: "Matemática", sub: "Estatística", txt: "A Variância é o quadrado do:", opt: ["Desvio Padrão", "Erro Amostral", "Coeficiente", "Moda"], cor: 0 },
            { id: "MAT-EST-027", cat: "Matemática", sub: "Estatística", txt: "Qual a probabilidade de tirar soma 2 em dois dados?", opt: ["1/36", "1/6", "1/12", "1/18"], cor: 0 },
            { id: "MAT-EST-028", cat: "Matemática", sub: "Estatística", txt: "Numa urna com 3 bolas azuis e 2 vermelhas, chance de tirar azul:", opt: ["20%", "40%", "60%", "30%"], cor: 2 },
            { id: "MAT-EST-029", cat: "Matemática", sub: "Estatística", txt: "Se a média das notas é 7 e o aluno tirou 5 e 9, a terceira nota foi:", opt: ["6", "7", "8", "9"], cor: 1 },
            { id: "MAT-EST-030", cat: "Matemática", sub: "Estatística", txt: "O censo do IBGE é uma pesquisa:", opt: ["Amostral", "Censitária", "Parcial", "Aleatória"], cor: 1 },
            { id: "MAT-EST-031", cat: "Matemática", sub: "Estatística", txt: "A frequência relativa é dada em:", opt: ["Números absolutos", "Porcentagem", "Graus", "Metros"], cor: 1 },
            { id: "MAT-EST-032", cat: "Matemática", sub: "Estatística", txt: "Dados 'Outliers' são:", opt: ["Valores médios", "Valores muito distantes do padrão", "Erros de digitação", "A moda"], cor: 1 },
            { id: "MAT-EST-033", cat: "Matemática", sub: "Estatística", txt: "Para calcular a mediana de dados pares, fazemos:", opt: ["Média dos dois centrais", "Soma tudo", "Pega o maior", "Pega o menor"], cor: 0 },
            { id: "MAT-EST-034", cat: "Matemática", sub: "Estatística", txt: "Probabilidade de um evento A OU B ocorrer (união):", opt: ["P(A) + P(B)", "P(A) x P(B)", "P(A) - P(B)", "P(A)/P(B)"], cor: 0 },
            { id: "MAT-EST-035", cat: "Matemática", sub: "Estatística", txt: "Probabilidade de A E B (independentes):", opt: ["P(A) + P(B)", "P(A) x P(B)", "P(A) - P(B)", "P(A)/P(B)"], cor: 1 },
            { id: "MAT-EST-036", cat: "Matemática", sub: "Estatística", txt: "Em um gráfico de barras, a altura indica:", opt: ["A frequência", "O tempo", "A média", "A variância"], cor: 0 },
            { id: "MAT-EST-037", cat: "Matemática", sub: "Estatística", txt: "Qual medida separa os 50% menores dos 50% maiores?", opt: ["Média", "Moda", "Mediana", "Desvio"], cor: 2 },
            { id: "MAT-EST-038", cat: "Matemática", sub: "Estatística", txt: "Numa amostra viciada, os dados são:", opt: ["Confiáveis", "Tendenciosos", "Aleatórios", "Representativos"], cor: 1 },
            { id: "MAT-EST-039", cat: "Matemática", sub: "Estatística", txt: "A soma das frequências relativas deve dar:", opt: ["100", "1", "0", "Varia"], cor: 1 },
            { id: "MAT-EST-040", cat: "Matemática", sub: "Estatística", txt: "Se a probabilidade de chover é 30%, a de NÃO chover é:", opt: ["30%", "50%", "70%", "100%"], cor: 2 },
            { id: "MAT-EST-041", cat: "Matemática", sub: "Estatística", txt: "O espaço amostral de uma moeda é:", opt: ["{Cara}", "{Coroa}", "{Cara, Coroa}", "{1, 2}"], cor: 2 },
            { id: "MAT-EST-042", cat: "Matemática", sub: "Estatística", txt: "Média aritmética de {10, 10, 10}:", opt: ["10", "30", "1", "0"], cor: 0 },
            { id: "MAT-EST-043", cat: "Matemática", sub: "Estatística", txt: "População em estatística significa:", opt: ["Pessoas de um país", "Conjunto total de elementos pesquisados", "Amostra pequena", "Censo"], cor: 1 },
            { id: "MAT-EST-044", cat: "Matemática", sub: "Estatística", txt: "Probabilidade varia entre:", opt: ["-1 e 1", "0 e 1", "0 e 100", "1 e 100"], cor: 1 },
            { id: "MAT-EST-045", cat: "Matemática", sub: "Estatística", txt: "O gráfico de dispersão analisa:", opt: ["Evolução no tempo", "Relação entre duas variáveis", "Partes de um todo", "Hierarquia"], cor: 1 },
            { id: "MAT-EST-046", cat: "Matemática", sub: "Estatística", txt: "Probabilidade de tirar número maior que 4 num dado:", opt: ["1/6", "2/6", "3/6", "4/6"], cor: 1 },
            { id: "MAT-EST-047", cat: "Matemática", sub: "Estatística", txt: "Se a média de idade de 3 pessoas é 20, a soma das idades é:", opt: ["20", "40", "60", "80"], cor: 2 },
            { id: "MAT-EST-048", cat: "Matemática", sub: "Estatística", txt: "O 'Range' ou Amplitude Total é:", opt: ["Max - Min", "Max + Min", "Média", "Moda"], cor: 0 },
            { id: "MAT-EST-049", cat: "Matemática", sub: "Estatística", txt: "Diagrama de Venn é usado em:", opt: ["Geometria", "Conjuntos/Probabilidade", "Álgebra", "Física"], cor: 1 },
            { id: "MAT-EST-050", cat: "Matemática", sub: "Estatística", txt: "Se jogo uma moeda 3 vezes, total de resultados possíveis:", opt: ["3", "6", "8", "9"], cor: 2 },
            { id: "MAT-EST-051", cat: "Matemática", sub: "Estatística", txt: "A moda de {Vermelho, Azul, Azul, Verde} é:", opt: ["Vermelho", "Azul", "Verde", "Nenhuma"], cor: 1 },
            { id: "MAT-EST-052", cat: "Matemática", sub: "Estatística", txt: "Desvio médio calcula a distância dos dados até a:", opt: ["Moda", "Mediana", "Média", "Variância"], cor: 2 },
            { id: "MAT-EST-053", cat: "Matemática", sub: "Estatística", txt: "Uma urna tem 10 bolas. Tiro uma e NÃO reponho. O total agora é:", opt: ["10", "9", "0", "11"], cor: 1 },
            { id: "MAT-EST-054", cat: "Matemática", sub: "Estatística", txt: "Gráfico de linha é ideal para mostrar:", opt: ["Proporção", "Evolução temporal", "Comparação estática", "Dispersão"], cor: 1 },
            { id: "MAT-EST-055", cat: "Matemática", sub: "Estatística", txt: "Qual letra geralmente representa a Média na fórmula?", opt: ["X com barra", "M", "Mo", "Md"], cor: 0 },
            { id: "MAT-EST-056", cat: "Matemática", sub: "Estatística", txt: "Chance de ganhar na mega-sena com 1 jogo é:", opt: ["Alta", "Média", "Baixa", "Impossível"], cor: 2 },
            { id: "MAT-EST-057", cat: "Matemática", sub: "Estatística", txt: "Dois eventos que não podem ocorrer juntos são:", opt: ["Independentes", "Mutuamente exclusivos", "Complementares", " Iguais"], cor: 1 },
            { id: "MAT-EST-058", cat: "Matemática", sub: "Estatística", txt: "Probabilidade de tirar 7 em um dado comum:", opt: ["1/6", "1/7", "0", "1"], cor: 2 },
            { id: "MAT-EST-059", cat: "Matemática", sub: "Estatística", txt: "Se a variância é 4, o desvio padrão é:", opt: ["2", "4", "8", "16"], cor: 0 },
            { id: "MAT-EST-060", cat: "Matemática", sub: "Estatística", txt: "O 'Espaço Amostral' é representado pela letra grega:", opt: ["Alfa", "Beta", "Ômega (Ω)", "Pi"], cor: 2 },
            { id: "MAT-EST-061", cat: "Matemática", sub: "Estatística", txt: "Percentil 50 é o mesmo que:", opt: ["Média", "Mediana", "Moda", "Quartil 3"], cor: 1 },
            { id: "MAT-EST-062", cat: "Matemática", sub: "Estatística", txt: "Pesquisa qualitativa foca em:", opt: ["Números", "Significados/Opiniões", "Contagem", "Medição"], cor: 1 },
            { id: "MAT-EST-063", cat: "Matemática", sub: "Estatística", txt: "Frequência acumulada é:", opt: ["Soma das frequências anteriores", "Média das frequências", "Maior frequência", "Menor frequência"], cor: 0 },
            { id: "MAT-EST-064", cat: "Matemática", sub: "Estatística", txt: "Probabilidade condicional P(A|B) lê-se:", opt: ["A ou B", "A e B", "A dado B", "A menos B"], cor: 2 },
            { id: "MAT-EST-065", cat: "Matemática", sub: "Estatística", txt: "Num gráfico de pizza, 25% corresponde a:", opt: ["45°", "90°", "180°", "360°"], cor: 1 },
            { id: "MAT-EST-066", cat: "Matemática", sub: "Estatística", txt: "Qual gráfico é ideal para mostrar evolução temporal?", opt: ["Setores", "Linhas", "Barras", "Dispersão"], cor: 1 },
            { id: "MAT-EST-067", cat: "Matemática", sub: "Estatística", txt: "A soma dos desvios em relação à média é sempre:", opt: ["1", "0", "A variância", "Positiva"], cor: 1 },
            { id: "MAT-EST-068", cat: "Matemática", sub: "Estatística", txt: "Numa distribuição normal, a média, moda e mediana:", opt: ["São iguais (ou próximas)", "São opostas", "Não existem", "Valem 0"], cor: 0 },
            { id: "MAT-EST-069", cat: "Matemática", sub: "Estatística", txt: "Probabilidade condicional P(A|B) é:", opt: ["P(A e B) / P(B)", "P(A) / P(B)", "P(A) x P(B)", "P(B) / P(A)"], cor: 0 },
            { id: "MAT-EST-070", cat: "Matemática", sub: "Estatística", txt: "Se o dado caiu 6, qual a chance de ser par?", opt: ["100%", "50%", "33%", "0%"], cor: 0 },
            { id: "MAT-EST-071", cat: "Matemática", sub: "Estatística", txt: "Erro amostral diminui se:", opt: ["Aumentarmos a amostra", "Diminuirmos a amostra", "Chutarmos", "Usarmos moda"], cor: 0 },
            { id: "MAT-EST-072", cat: "Matemática", sub: "Estatística", txt: "A 'Frequência Relativa' pode ser expressa em:", opt: ["Metros", "Quilos", "Decimal ou %", "Litros"], cor: 2 },
            { id: "MAT-EST-073", cat: "Matemática", sub: "Estatística", txt: "Para dados qualitativos nominais, a melhor medida central é:", opt: ["Média", "Moda", "Mediana", "Variância"], cor: 1 },
            { id: "MAT-EST-074", cat: "Matemática", sub: "Estatística", txt: "O gráfico de Pareto combina:", opt: ["Barras e Linha", "Pizza e Rosca", "Dispersão e Área", "Cone e Cubo"], cor: 0 },
            { id: "MAT-EST-075", cat: "Matemática", sub: "Estatística", txt: "Coeficiente de variação serve para:", opt: ["Comparar variabilidade de grupos diferentes", "Somar médias", "Achar a moda", "Desenhar gráficos"], cor: 0 },
            { id: "MAT-EST-076", cat: "Matemática", sub: "Estatística", txt: "Em probabilidade, evento 'complementar' A^c é:", opt: ["O que falta para 100%", "O mesmo que A", "O dobro de A", "Metade de A"], cor: 0 },
            { id: "MAT-EST-077", cat: "Matemática", sub: "Estatística", txt: "Se tiro uma carta e NÃO devolvo, os eventos são:", opt: ["Independentes", "Dependentes", "Nulos", "Certos"], cor: 1 },
            { id: "MAT-EST-078", cat: "Matemática", sub: "Estatística", txt: "Amplitude Interquartil é:", opt: ["Q3 - Q1", "Q4 - Q1", "Média - Moda", "Max - Min"], cor: 0 },
            { id: "MAT-EST-079", cat: "Matemática", sub: "Estatística", txt: "A chance de ganhar na Mega-Sena com 1 jogo é:", opt: ["Alta", "Baixíssima", "50%", "10%"], cor: 1 },
            { id: "MAT-EST-080", cat: "Matemática", sub: "Estatística", txt: "Qual média é usada para taxas de crescimento?", opt: ["Aritmética", "Geométrica", "Ponderada", "Harmônica"], cor: 1 },
            { id: "MAT-EST-081", cat: "Matemática", sub: "Estatística", txt: "A média harmônica de 2 e 6 é:", opt: ["4", "3", "5", "2.5"], cor: 1 },
            { id: "MAT-EST-082", cat: "Matemática", sub: "Estatística", txt: "Uma variável 'Número de Filhos' é:", opt: ["Contínua", "Discreta", "Nominal", "Ordinal"], cor: 1 },
            { id: "MAT-EST-083", cat: "Matemática", sub: "Estatística", txt: "Uma variável 'Temperatura' é:", opt: ["Contínua", "Discreta", "Nominal", "Binária"], cor: 0 },
            { id: "MAT-EST-084", cat: "Matemática", sub: "Estatística", txt: "Se a correlação é +1, as variáveis:", opt: ["Sobem juntas perfeitamente", "Descem juntas", "Não têm relação", "São opostas"], cor: 0 },
            { id: "MAT-EST-085", cat: "Matemática", sub: "Estatística", txt: "Se a correlação é 0, as variáveis:", opt: ["São idênticas", "Não têm relação linear", "São inversas", "São constantes"], cor: 1 },
            { id: "MAT-EST-086", cat: "Matemática", sub: "Estatística", txt: "Correlação não implica necessariamente em:", opt: ["Causalidade", "Linearidade", "Dependência", "Variação"], cor: 0 },
            { id: "MAT-EST-087", cat: "Matemática", sub: "Estatística", txt: "Se a probabilidade de vitória é 0.8, a de derrota é:", opt: ["0.2", "0.8", "0.5", "0"], cor: 0 },
            { id: "MAT-EST-088", cat: "Matemática", sub: "Estatística", txt: "Num gráfico de pizza, 25% equivale a quantos graus?", opt: ["90°", "45°", "180°", "25°"], cor: 0 },
            { id: "MAT-EST-089", cat: "Matemática", sub: "Estatística", txt: "Variável 'Escolaridade' (Fundamental, Médio, Superior) é:", opt: ["Qualitativa Ordinal", "Qualitativa Nominal", "Quantitativa", "Contínua"], cor: 0 },
            { id: "MAT-EST-090", cat: "Matemática", sub: "Estatística", txt: "Se um conjunto tem duas modas, ele é:", opt: ["Bimodal", "Amodal", "Trimodal", "Normal"], cor: 0 },
            { id: "MAT-EST-091", cat: "Matemática", sub: "Estatística", txt: "Ao somar dois dados, qual resultado é mais provável?", opt: ["7", "2", "12", "1"], cor: 0 },
            { id: "MAT-EST-092", cat: "Matemática", sub: "Estatística", txt: "A diferença entre o maior e o menor valor é a:", opt: ["Amplitude Total", "Amplitude Interquartil", "Variância", "Média"], cor: 0 },
            { id: "MAT-EST-093", cat: "Matemática", sub: "Estatística", txt: "Para calcular a média de velocidades, usa-se preferencialmente a:", opt: ["Média Harmônica", "Média Aritmética", "Moda", "Mediana"], cor: 0 },
            { id: "MAT-EST-094", cat: "Matemática", sub: "Estatística", txt: "No Boxplot, a linha dentro da caixa representa a:", opt: ["Mediana", "Média", "Moda", "Máxima"], cor: 0 },
            { id: "MAT-EST-095", cat: "Matemática", sub: "Estatística", txt: "Viés de amostragem ocorre quando:", opt: ["A amostra não representa a população", "A amostra é muito grande", "O cálculo está certo", "Todos respondem"], cor: 0 },
            { id: "MAT-EST-096", cat: "Matemática", sub: "Estatística", txt: "Se P(A) = 0, o evento é:", opt: ["Impossível", "Certo", "Provável", "Aleatório"], cor: 0 },
            { id: "MAT-EST-097", cat: "Matemática", sub: "Estatística", txt: "A soma dos desvios quadráticos dividido por n-1 é a:", opt: ["Variância Amostral", "Média", "Moda", "Desvio Absoluto"], cor: 0 },
            { id: "MAT-EST-098", cat: "Matemática", sub: "Estatística", txt: "Decil divide os dados em quantas partes?", opt: ["10", "100", "4", "2"], cor: 0 },
            { id: "MAT-EST-099", cat: "Matemática", sub: "Estatística", txt: "Percentil 50 (P50) é o mesmo que:", opt: ["Mediana", "Média", "Moda", "Q1"], cor: 0 },
            { id: "MAT-EST-100", cat: "Matemática", sub: "Estatística", txt: "Margem de erro em pesquisas indica:", opt: ["A imprecisão esperada", "Que a pesquisa é falsa", "O número de entrevistados", "O custo"], cor: 0 },
        ;]
