export const questoes = [
 
            // --- NOVO TÓPICO: MATEMÁTICA FINANCEIRA (001 em diante) ---
            { id: "MAT-FIN-001", cat: "Matemática", sub: "Financeira", txt: "Juros compostos são conhecidos como:", opt: ["Juros sobre juros", "Juros fixos", "Desconto simples", "Amortização"], cor: 0 },
            { id: "MAT-FIN-002", cat: "Matemática", sub: "Financeira", txt: "50% de 50% é igual a:", opt: ["100%", "50%", "25%", "10%"], cor: 2 },
            { id: "MAT-FIN-003", cat: "Matemática", sub: "Financeira", txt: "Um aumento de 10% seguido de outro de 10% resulta em:", opt: ["20%", "21%", "100%", "121%"], cor: 1 },
            { id: "MAT-FIN-004", cat: "Matemática", sub: "Financeira", txt: "Montante é igual a:", opt: ["Capital - Juros", "Capital + Juros", "Juros / Tempo", "Capital x Taxa"], cor: 1 },
            { id: "MAT-FIN-005", cat: "Matemática", sub: "Financeira", txt: "A taxa Selic influencia principalmente:", opt: ["O clima", "A inflação e juros", "O PIB per capita", "A demografia"], cor: 1 },
            { id: "MAT-FIN-006", cat: "Matemática", sub: "Financeira", txt: "Se comprei por 100 e vendi por 150, o lucro foi de:", opt: ["30%", "40%", "50%", "100%"], cor: 2 },
            { id: "MAT-FIN-007", cat: "Matemática", sub: "Financeira", txt: "O que é 'Capital' em matemática financeira?", opt: ["Lucro total", "Valor inicial investido", "Tempo de aplicação", "Taxa de juros"], cor: 1 },
            { id: "MAT-FIN-008", cat: "Matemática", sub: "Financeira", txt: "Para transformar 20% em decimal, dividimos por:", opt: ["10", "100", "1000", "1"], cor: 1 },
            { id: "MAT-FIN-009", cat: "Matemática", sub: "Financeira", txt: "Se a inflação é 10%, o poder de compra:", opt: ["Aumenta", "Diminui", "Fica igual", "Dobra"], cor: 1 },
            { id: "MAT-FIN-010", cat: "Matemática", sub: "Financeira", txt: "1/4 em porcentagem é:", opt: ["20%", "25%", "40%", "50%"], cor: 1 },
            { id: "MAT-FIN-011", cat: "Matemática", sub: "Financeira", txt: "Lucro Líquido é:", opt: ["Receita Total", "Receita - Despesas", "Apenas as despesas", "O valor do imposto"], cor: 1 },
            { id: "MAT-FIN-012", cat: "Matemática", sub: "Financeira", txt: "O que é 'Amortização'?", opt: ["Pagar juros", "Reduzir a dívida original", "Aumentar o prazo", "Pegar empréstimo"], cor: 1 },
            { id: "MAT-FIN-013", cat: "Matemática", sub: "Financeira", txt: "30% de 300 é:", opt: ["30", "60", "90", "100"], cor: 2 },
            { id: "MAT-FIN-014", cat: "Matemática", sub: "Financeira", txt: "Se ganhei 10% e perdi 10% sobre o novo valor:", opt: ["Fiquei igual", "Perdi dinheiro", "Ganhei dinheiro", "Impossível saber"], cor: 1 },
            { id: "MAT-FIN-015", cat: "Matemática", sub: "Financeira", txt: "Fator de aumento de 20% é multiplicar por:", opt: ["0,2", "1,2", "2,0", "120"], cor: 1 },
            { id: "MAT-FIN-016", cat: "Matemática", sub: "Financeira", txt: "Fator de desconto de 30% é multiplicar por:", opt: ["0,3", "1,3", "0,7", "3,0"], cor: 2 },
            { id: "MAT-FIN-017", cat: "Matemática", sub: "Financeira", txt: "O que é superávit?", opt: ["Gastar mais que ganha", "Ganhar mais que gasta", "Empatar", "Dívida"], cor: 1 },
            { id: "MAT-FIN-018", cat: "Matemática", sub: "Financeira", txt: "Juros de 1% ao mês em juros simples, após 12 meses:", opt: ["12%", "Mais que 12%", "Menos que 12%", "1%"], cor: 0 },
            { id: "MAT-FIN-019", cat: "Matemática", sub: "Financeira", txt: "PIB significa:", opt: ["Produto Interno Bruto", "Preço Interno Base", "Plano Internacional Bancário", "Pagamento Imposto Bruto"], cor: 0 },
            { id: "MAT-FIN-020", cat: "Matemática", sub: "Financeira", txt: "Se o dólar sobe, as importações ficam:", opt: ["Mais baratas", "Mais caras", "Iguais", "Isentas"], cor: 1 },
            { id: "MAT-FIN-021", cat: "Matemática", sub: "Financeira", txt: "A fórmula M = C(1+i)^t é de:", opt: ["Juros Simples", "Juros Compostos", "Amortização", "Desconto"], cor: 1 },
            { id: "MAT-FIN-022", cat: "Matemática", sub: "Financeira", txt: "Se o preço triplicou, o aumento foi de:", opt: ["100%", "200%", "300%", "50%"], cor: 1 },
            { id: "MAT-FIN-023", cat: "Matemática", sub: "Financeira", txt: "O que é IOF?", opt: ["Imposto sobre Operações Financeiras", "Índice Oficial Financeiro", "Imposto Obrigatório Federal", "Instituição de Oferta"], cor: 0 },
            { id: "MAT-FIN-024", cat: "Matemática", sub: "Financeira", txt: "Qual o juro simples de R$100 a 10% por 2 meses?", opt: ["R$ 10", "R$ 20", "R$ 21", "R$ 12"], cor: 1 },
            { id: "MAT-FIN-025", cat: "Matemática", sub: "Financeira", txt: "Qual o juro composto de R$100 a 10% por 2 meses?", opt: ["R$ 20", "R$ 21", "R$ 22", "R$ 121"], cor: 1 },
            { id: "MAT-FIN-026", cat: "Matemática", sub: "Financeira", txt: "Deflação é:", opt: ["Aumento de preços", "Queda generalizada de preços", "Estabilidade", "Aumento do PIB"], cor: 1 },
            { id: "MAT-FIN-027", cat: "Matemática", sub: "Financeira", txt: "Spread bancário é:", opt: ["Lucro do banco", "Prejuízo do banco", "Diferença entre juros captados e cobrados", "Taxa do governo"], cor: 2 },
            { id: "MAT-FIN-028", cat: "Matemática", sub: "Financeira", txt: "Liquidez significa:", opt: ["Ter muita água", "Facilidade de transformar ativo em dinheiro", "Dívida alta", "Lucro baixo"], cor: 1 },
            { id: "MAT-FIN-029", cat: "Matemática", sub: "Financeira", txt: "Um boleto vencido geralmente cobra:", opt: ["Multa e Juros", "Desconto", "Apenas o original", "Taxa administrativa"], cor: 0 },
            { id: "MAT-FIN-030", cat: "Matemática", sub: "Financeira", txt: "Câmbio flutuante significa:", opt: ["Governo fixa o valor", "O mercado define o valor", "Valor nunca muda", "Valor muda uma vez por ano"], cor: 1 },
            { id: "MAT-FIN-031", cat: "Matemática", sub: "Financeira", txt: "Para triplicar um capital a juros simples de 100% a.a., leva:", opt: ["1 ano", "2 anos", "3 anos", "4 anos"], cor: 1 },
            { id: "MAT-FIN-032", cat: "Matemática", sub: "Financeira", txt: "Renda Fixa é considerada:", opt: ["Alto risco", "Baixo risco", "Sem retorno", "Ilegal"], cor: 1 },
            { id: "MAT-FIN-033", cat: "Matemática", sub: "Financeira", txt: "A Bolsa de Valores brasileira é a:", opt: ["NASDAQ", "B3", "Dow Jones", "Nikkei"], cor: 1 },
            { id: "MAT-FIN-034", cat: "Matemática", sub: "Financeira", txt: "Dividendo é:", opt: ["Dívida da empresa", "Parte do lucro pago ao acionista", "Imposto", "Multa"], cor: 1 },
            { id: "MAT-FIN-035", cat: "Matemática", sub: "Financeira", txt: "Se gastei 2/5 do salário, sobrou:", opt: ["20%", "40%", "60%", "80%"], cor: 2 },
            { id: "MAT-FIN-036", cat: "Matemática", sub: "Financeira", txt: "O 'nome sujo' fica registrado no:", opt: ["SPC/Serasa", "IBGE", "MEC", "SUS"], cor: 0 },
            { id: "MAT-FIN-037", cat: "Matemática", sub: "Financeira", txt: "Cartão de crédito cobra juros se:", opt: ["Pagar a fatura total", "Pagar o mínimo ou atrasar", "Nunca usar", "Usar no débito"], cor: 1 },
            { id: "MAT-FIN-038", cat: "Matemática", sub: "Financeira", txt: "Um trimestre tem:", opt: ["2 meses", "3 meses", "4 meses", "6 meses"], cor: 1 },
            { id: "MAT-FIN-039", cat: "Matemática", sub: "Financeira", txt: "O salário mínimo é reajustado com base na:", opt: ["Inflação", "Dólar", "Bolsa", "Vontade do patrão"], cor: 0 },
            { id: "MAT-FIN-040", cat: "Matemática", sub: "Financeira", txt: "Desconto à vista serve para:", opt: ["Pagar mais caro", "Evitar taxas de cartão/prazo", "Parcelar", "Aumentar juros"], cor: 1 },
            { id: "MAT-FIN-041", cat: "Matemática", sub: "Financeira", txt: "Para dobrar um valor, o aumento deve ser de:", opt: ["50%", "100%", "200%", "10%"], cor: 1 },
            { id: "MAT-FIN-042", cat: "Matemática", sub: "Financeira", txt: "A sigla IPCA mede a:", opt: ["Inflação oficial", "Taxa de juros", "Dólar", "Desemprego"], cor: 0 },
            { id: "MAT-FIN-043", cat: "Matemática", sub: "Financeira", txt: "O que é 'Ativo' em finanças?", opt: ["Dívidas", "Bens e direitos", "Prejuízos", "Impostos"], cor: 1 },
            { id: "MAT-FIN-044", cat: "Matemática", sub: "Financeira", txt: "O que é 'Passivo' em finanças?", opt: ["Lucro", "Dívidas e obrigações", "Investimentos", "Dinheiro em caixa"], cor: 1 },
            { id: "MAT-FIN-045", cat: "Matemática", sub: "Financeira", txt: "Taxa CDI costuma seguir de perto a taxa:", opt: ["Selic", "Poupança", "Dólar", "Inflação"], cor: 0 },
            { id: "MAT-FIN-046", cat: "Matemática", sub: "Financeira", txt: "Se o produto custa 100 e vendo com lucro de 20% sobre o CUSTO:", opt: ["Vendo a 120", "Vendo a 125", "Vendo a 80", "Vendo a 100"], cor: 0 },
            { id: "MAT-FIN-047", cat: "Matemática", sub: "Financeira", txt: "Criptomoedas são ativos:", opt: ["Centralizados", "Descentralizados", "Físicos", "Estatais"], cor: 1 },
            { id: "MAT-FIN-048", cat: "Matemática", sub: "Financeira", txt: "Fundo de Garantia (FGTS) é direito de:", opt: ["Autônomos", "Trabalhador CLT", "Empresários", "Estagiários"], cor: 1 },
            { id: "MAT-FIN-049", cat: "Matemática", sub: "Financeira", txt: "O 13º salário equivale a:", opt: ["Meio salário", "Um salário extra", "Dois salários", "Uma cesta básica"], cor: 1 },
            { id: "MAT-FIN-050", cat: "Matemática", sub: "Financeira", txt: "Se 1 dólar = 5 reais, 10 dólares são:", opt: ["2 reais", "20 reais", "50 reais", "100 reais"], cor: 2 },
            { id: "MAT-FIN-051", cat: "Matemática", sub: "Financeira", txt: "Receita - Despesa = ?", opt: ["Patrimônio", "Lucro ou Prejuízo", "Faturamento", "Investimento"], cor: 1 },
            { id: "MAT-FIN-052", cat: "Matemática", sub: "Financeira", txt: "Um semestre tem:", opt: ["3 meses", "6 meses", "9 meses", "12 meses"], cor: 1 },
            { id: "MAT-FIN-053", cat: "Matemática", sub: "Financeira", txt: "Se divido o valor em 12x sem juros, o total pago é:", opt: ["Maior", "Menor", "Igual ao à vista", "O dobro"], cor: 2 },
            { id: "MAT-FIN-054", cat: "Matemática", sub: "Financeira", txt: "Poupança rende juros:", opt: ["Diários", "Mensais (Aniversário)", "Anuais", "Semanais"], cor: 1 },
            { id: "MAT-FIN-055", cat: "Matemática", sub: "Financeira", txt: "O 't' na fórmula de juros representa:", opt: ["Taxa", "Total", "Tempo", "Trabalho"], cor: 2 },
            { id: "MAT-FIN-056", cat: "Matemática", sub: "Financeira", txt: "O 'i' na fórmula de juros representa:", opt: ["Investimento", "Inflação", "Taxa (Interest)", "Imposto"], cor: 2 },
            { id: "MAT-FIN-057", cat: "Matemática", sub: "Financeira", txt: "ROI significa:", opt: ["Retorno sobre Investimento", "Risco de Operação Interna", "Renda Oficial", "Risco Original"], cor: 0 },
            { id: "MAT-FIN-058", cat: "Matemática", sub: "Financeira", txt: "Um biênio tem:", opt: ["1 ano", "2 anos", "3 anos", "4 anos"], cor: 1 },
            { id: "MAT-FIN-059", cat: "Matemática", sub: "Financeira", txt: "Balança Comercial favorável é quando:", opt: ["Exportação > Importação", "Importação > Exportação", "São iguais", "Não há comércio"], cor: 0 },
            { id: "MAT-FIN-060", cat: "Matemática", sub: "Financeira", txt: "Cheque especial é um tipo de:", opt: ["Investimento", "Empréstimo automático caro", "Prêmio", "Desconto"], cor: 1 },
            { id: "MAT-FIN-061", cat: "Matemática", sub: "Financeira", txt: "Empréstimo 'Price' tem parcelas:", opt: ["Crescentes", "Decrescentes", "Fixas", "Aleatórias"], cor: 2 },
            { id: "MAT-FIN-062", cat: "Matemática", sub: "Financeira", txt: "Empréstimo 'SAC' tem parcelas:", opt: ["Crescentes", "Decrescentes", "Fixas", "Nulas"], cor: 1 },
            { id: "MAT-FIN-063", cat: "Matemática", sub: "Financeira", txt: "Taxa Nominal vs Taxa Real: A real desconta a:", opt: ["Inflação", "Preguiça", "Distância", "Corrupção"], cor: 0 },
            { id: "MAT-FIN-064", cat: "Matemática", sub: "Financeira", txt: "CET significa:", opt: ["Custo Efetivo Total", "Crédito Especial Total", "Conta em Transito", "Caixa Eletrônico"], cor: 0 },
            { id: "MAT-FIN-065", cat: "Matemática", sub: "Financeira", txt: "Se o rendimento é 100% do CDI e o CDI é 13%:", opt: ["Rende 13%", "Rende 100%", "Rende 1%", "Rende 26%"], cor: 0 },
            { id: "MAT-FIN-066", cat: "Matemática", sub: "Financeira", txt: "Um ativo de 'Risco Soberano' refere-se a:", opt: ["Títulos do Governo", "Ações de Tech", "Bitcoin", "Imóveis"], cor: 0 },
            { id: "MAT-FIN-067", cat: "Matemática", sub: "Financeira", txt: "FGC garante até quanto por CPF/Instituição?", opt: ["50 mil", "250 mil", "1 milhão", "Sem limite"], cor: 1 },
            { id: "MAT-FIN-068", cat: "Matemática", sub: "Financeira", txt: "Day Trade é:", opt: ["Investir para aposentadoria", "Comprar e vender no mesmo dia", "Comprar à noite", "Vender semana que vem"], cor: 1 },
            { id: "MAT-FIN-069", cat: "Matemática", sub: "Financeira", txt: "O 'colchão de liquidez' serve para:", opt: ["Dormir", "Cobrir imprevistos", "Comprar luxos", "Pagar dividendos"], cor: 1 },
            { id: "MAT-FIN-070", cat: "Matemática", sub: "Financeira", txt: "LCI e LCA são isentos de:", opt: ["Imposto de Renda (PF)", "IOF", "Taxa de custódia", "Risco"], cor: 0 },
            { id: "MAT-FIN-071", cat: "Matemática", sub: "Financeira", txt: "Taxa de corretagem é cobrada por:", opt: ["Bancos Centrais", "Corretoras", "Shoppings", "Padarias"], cor: 1 },
            { id: "MAT-FIN-072", cat: "Matemática", sub: "Financeira", txt: "IPCA mede:", opt: ["Inflação oficial", "Desemprego", "Dólar", "Exportação"], cor: 0 },
            { id: "MAT-FIN-073", cat: "Matemática", sub: "Financeira", txt: "IGP-M é conhecido como inflação do:", opt: ["Aluguel", "Supermercado", "Carro", "Computador"], cor: 0 },
            { id: "MAT-FIN-074", cat: "Matemática", sub: "Financeira", txt: "Previdência PGBL permite:", opt: ["Abater no IR (completo)", "Isenção total", "Saque imediato", "Risco zero"], cor: 0 },
            { id: "MAT-FIN-075", cat: "Matemática", sub: "Financeira", txt: "Previdência VGBL é indicada para:", opt: ["Quem faz declaração simplificada", "Quem faz completa", "Quem não paga imposto", "Empresas"], cor: 0 },
            { id: "MAT-FIN-076", cat: "Matemática", sub: "Financeira", txt: "Bear Market significa mercado em:", opt: ["Alta", "Baixa", "Lateral", "Fechado"], cor: 1 },
            { id: "MAT-FIN-077", cat: "Matemática", sub: "Financeira", txt: "Bull Market significa mercado em:", opt: ["Alta", "Baixa", "Quebra", "Feriado"], cor: 0 },
            { id: "MAT-FIN-078", cat: "Matemática", sub: "Financeira", txt: "IPO é:", opt: ["Oferta Pública Inicial (Bolsa)", "Imposto Predial", "Índice de Preço", "Instituto de Pesquisa"], cor: 0 },
            { id: "MAT-FIN-079", cat: "Matemática", sub: "Financeira", txt: "Debênture é dívida de:", opt: ["Empresas", "Governo", "Pessoas", "ONGs"], cor: 0 },
            { id: "MAT-FIN-080", cat: "Matemática", sub: "Financeira", txt: "Tesouro Direto é título de dívida do:", opt: ["Governo Federal", "Banco do Brasil", "Itaú", "Prefeitura"], cor: 0 },
            { id: "MAT-FIN-081", cat: "Matemática", sub: "Financeira", txt: "ROI significa:", opt: ["Retorno sobre Investimento", "Risco de Operação", "Receita Original", "Renda Ocasional"], cor: 0 },
            { id: "MAT-FIN-082", cat: "Matemática", sub: "Financeira", txt: "Fórmula J = C.i.n é de:", opt: ["Juros Simples", "Juros Compostos", "Desconto", "Amortização"], cor: 0 },
            { id: "MAT-FIN-083", cat: "Matemática", sub: "Financeira", txt: "Juros compostos crescem de forma:", opt: ["Exponencial", "Linear", "Constante", "Decrescente"], cor: 0 },
            { id: "MAT-FIN-084", cat: "Matemática", sub: "Financeira", txt: "Ganho Real é:", opt: ["Ganho acima da inflação", "Ganho bruto", "Ganho líquido", "Ganho nominal"], cor: 0 },
            { id: "MAT-FIN-085", cat: "Matemática", sub: "Financeira", txt: "Diversificação serve para:", opt: ["Reduzir riscos", "Aumentar taxas", "Pagar mais imposto", "Perder dinheiro"], cor: 0 },
            { id: "MAT-FIN-086", cat: "Matemática", sub: "Financeira", txt: "Geralmente, maior risco implica em:", opt: ["Maior potencial de retorno", "Menor retorno", "Segurança total", "Garantia FGC"], cor: 0 },
            { id: "MAT-FIN-087", cat: "Matemática", sub: "Financeira", txt: "Reserva de Emergência deve cobrir:", opt: ["6 a 12 meses de custo de vida", "1 mês de salário", "Apenas o aluguel", "Viagens"], cor: 0 },
            { id: "MAT-FIN-088", cat: "Matemática", sub: "Financeira", txt: "Score de Crédito baixo dificulta:", opt: ["Conseguir empréstimos/cartões", "Pagar à vista", "Usar débito", "Votar"], cor: 0 },
            { id: "MAT-FIN-089", cat: "Matemática", sub: "Financeira", txt: "Volatilidade mede:", opt: ["A oscilação de preço", "O lucro fixo", "O imposto", "A certeza"], cor: 0 },
            { id: "MAT-FIN-090", cat: "Matemática", sub: "Financeira", txt: "No sistema Price, a amortização é:", opt: ["Crescente", "Decrescente", "Fixa", "Nula"], cor: 0 },
            { id: "MAT-FIN-091", cat: "Matemática", sub: "Financeira", txt: "Poder de compra cai quando:", opt: ["A inflação sobe", "O salário aumenta", "Os preços caem", "Há deflação"], cor: 0 },
            { id: "MAT-FIN-092", cat: "Matemática", sub: "Financeira", txt: "Blue Chips são:", opt: ["Ações de empresas grandes e sólidas", "Empresas falidas", "Startups arriscadas", "Fichas de poker"], cor: 0 },
            { id: "MAT-FIN-093", cat: "Matemática", sub: "Financeira", txt: "ETF é um fundo que:", opt: ["Replica um índice (ex: Ibovespa)", "Só compra ouro", "Não tem taxas", "É ilegal"], cor: 0 },
            { id: "MAT-FIN-094", cat: "Matemática", sub: "Financeira", txt: "Dividend Yield mede:", opt: ["Dividendo pago em relação ao preço da ação", "O lucro total", "A dívida", "O crescimento"], cor: 0 },
            { id: "MAT-FIN-095", cat: "Matemática", sub: "Financeira", txt: "Salário Bruto menos descontos é:", opt: ["Salário Líquido", "Salário Real", "Bônus", "FGTS"], cor: 0 },
            { id: "MAT-FIN-096", cat: "Matemática", sub: "Financeira", txt: "Ponto de Equilíbrio (Break-even) é quando:", opt: ["Receitas igualam Despesas", "Há lucro máximo", "Há prejuízo", "A empresa fecha"], cor: 0 },
            { id: "MAT-FIN-097", cat: "Matemática", sub: "Financeira", txt: "Valorização de um imóvel é:", opt: ["Aumento do preço de mercado", "Depreciação", "Aluguel", "Reforma"], cor: 0 },
            { id: "MAT-FIN-098", cat: "Matemática", sub: "Financeira", txt: "Juros de mora são cobrados por:", opt: ["Atraso no pagamento", "Antecipação", "Fidelidade", "Erro do banco"], cor: 0 },
            { id: "MAT-FIN-099", cat: "Matemática", sub: "Financeira", txt: "Commodities são:", opt: ["Matérias-primas (soja, ferro, petróleo)", "Carros de luxo", "Serviços de TI", "Softwares"], cor: 0 },
            { id: "MAT-FIN-100", cat: "Matemática", sub: "Financeira", txt: "O fator mais poderoso nos juros compostos é:", opt: ["O tempo", "A taxa", "O aporte", "O banco"], cor: 0 },
];
