export const questoes = [
            { id: "MAT-GEO-001", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um triângulo é:", opt: ["180°", "360°", "90°", "270°"], cor: 0 },
            { id: "MAT-GEO-002", cat: "Matemática", sub: "Geometria", txt: "Volume do cubo de aresta 2cm:", opt: ["4cm³", "8cm³", "6cm³", "12cm³"], cor: 1 },
            { id: "MAT-GEO-003", cat: "Matemática", sub: "Geometria", txt: "Área do círculo de raio 3cm (use π=3):", opt: ["18cm²", "27cm²", "9cm²", "30cm²"], cor: 1 },
            { id: "MAT-GEO-004", cat: "Matemática", sub: "Geometria", txt: "Qual sólido geométrico é estudado como 'corpo redondo'?", opt: ["Cubo", "Prisma", "Cilindro", "Pirâmide"], cor: 2 },
            { id: "MAT-GEO-005", cat: "Matemática", sub: "Geometria", txt: "Um triângulo com lados 3, 4 e 5 é:", opt: ["Equilátero", "Isósceles", "Retângulo", "Obtusângulo"], cor: 2 },
            { id: "MAT-GEO-006", cat: "Matemática", sub: "Geometria", txt: "A fórmula da área do trapézio é:", opt: ["(B+b).h/2", "b.h", "l²", "π.r²"], cor: 0 },
            { id: "MAT-GEO-007", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos externos de qualquer polígono convexo é:", opt: ["180°", "360°", "540°", "90°"], cor: 1 },
            { id: "MAT-GEO-008", cat: "Matemática", sub: "Geometria", txt: "Quantas diagonais tem um quadrado?", opt: ["1", "2", "4", "0"], cor: 1 },
            { id: "MAT-GEO-009", cat: "Matemática", sub: "Geometria", txt: "O Teorema de Tales trata de:", opt: ["Triângulos Retângulos", "Retas paralelas cortadas por transversais", "Círculos", "Áreas de polígonos"], cor: 1 },
            { id: "MAT-GEO-010", cat: "Matemática", sub: "Geometria", txt: "Qual a fórmula do volume de um cilindro?", opt: ["π.r²", "π.r².h", "2.π.r", "4/3.π.r³"], cor: 1 },
            { id: "MAT-GEO-011", cat: "Matemática", sub: "Geometria", txt: "Um ângulo maior que 90° e menor que 180° é:", opt: ["Agudo", "Reto", "Obtuso", "Raso"], cor: 2 },
            { id: "MAT-GEO-012", cat: "Matemática", sub: "Geometria", txt: "O perímetro de um quadrado de lado 5cm é:", opt: ["10cm", "15cm", "20cm", "25cm"], cor: 2 },
            { id: "MAT-GEO-013", cat: "Matemática", sub: "Geometria", txt: "Dois ângulos cuja soma é 90° são chamados de:", opt: ["Suplementares", "Complementares", "Opostos", "Alternos"], cor: 1 },
            { id: "MAT-GEO-014", cat: "Matemática", sub: "Geometria", txt: "Qual polígono tem 5 lados?", opt: ["Hexágono", "Heptágono", "Pentágono", "Octógono"], cor: 2 },
            { id: "MAT-GEO-015", cat: "Matemática", sub: "Geometria", txt: "O ponto central de uma circunferência até a borda chama-se:", opt: ["Diâmetro", "Raio", "Corda", "Tangente"], cor: 1 },
            { id: "MAT-GEO-016", cat: "Matemática", sub: "Geometria", txt: "A área de um retângulo de base 10 e altura 5 é:", opt: ["15", "50", "25", "100"], cor: 1 },
            { id: "MAT-GEO-017", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos externos de um triângulo é:", opt: ["180°", "360°", "270°", "90°"], cor: 1 },
            { id: "MAT-GEO-018", cat: "Matemática", sub: "Geometria", txt: "Qual triângulo tem os 3 lados diferentes?", opt: ["Equilátero", "Isósceles", "Escaleno", "Retângulo"], cor: 2 },
            { id: "MAT-GEO-019", cat: "Matemática", sub: "Geometria", txt: "A fórmula 4/3.π.r³ calcula o volume de:", opt: ["Esfera", "Cilindro", "Cone", "Cubo"], cor: 0 },
            { id: "MAT-GEO-020", cat: "Matemática", sub: "Geometria", txt: "Um ângulo de 180° é chamado de:", opt: ["Reto", "Agudo", "Raso", "Completo"], cor: 2 },
            { id: "MAT-GEO-021", cat: "Matemática", sub: "Geometria", txt: "Quantos graus tem uma volta completa?", opt: ["180°", "270°", "360°", "100°"], cor: 2 },
            { id: "MAT-GEO-022", cat: "Matemática", sub: "Geometria", txt: "A área de um quadrado de lado 10m é:", opt: ["40m²", "100m²", "20m²", "10m²"], cor: 1 },
            { id: "MAT-GEO-023", cat: "Matemática", sub: "Geometria", txt: "O que é uma corda na circunferência?", opt: ["Segmento que liga dois pontos da borda", "O raio", "O centro", "A tangente"], cor: 0 },
            { id: "MAT-GEO-024", cat: "Matemática", sub: "Geometria", txt: "Quantos lados tem um decágono?", opt: ["8", "10", "12", "20"], cor: 1 },
            { id: "MAT-GEO-025", cat: "Matemática", sub: "Geometria", txt: "Dois triângulos são semelhantes se tiverem:", opt: ["Mesma área", "Lados iguais", "Ângulos iguais", "Mesmo perímetro"], cor: 2 },
            { id: "MAT-GEO-026", cat: "Matemática", sub: "Geometria", txt: "Volume de um paralelepípedo de dimensões 2, 3 e 4:", opt: ["9", "24", "12", "48"], cor: 1 },
            { id: "MAT-GEO-027", cat: "Matemática", sub: "Geometria", txt: "Num triângulo retângulo, o lado oposto ao ângulo reto é a:", opt: ["Cateto", "Altura", "Hipotenusa", "Mediana"], cor: 2 },
            { id: "MAT-GEO-028", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um quadrado é:", opt: ["180°", "360°", "540°", "720°"], cor: 1 },
            { id: "MAT-GEO-029", cat: "Matemática", sub: "Geometria", txt: "Qual figura tem 4 lados iguais, mas ângulos não retos?", opt: ["Quadrado", "Retângulo", "Losango", "Trapézio"], cor: 2 },
            { id: "MAT-GEO-030", cat: "Matemática", sub: "Geometria", txt: "Se o raio é 5, o diâmetro é:", opt: ["2,5", "5", "10", "15"], cor: 2 },
            { id: "MAT-GEO-031", cat: "Matemática", sub: "Geometria", txt: "Área do triângulo de base 8 e altura 4:", opt: ["32", "16", "12", "64"], cor: 1 },
            { id: "MAT-GEO-032", cat: "Matemática", sub: "Geometria", txt: "Quantas arestas tem um cubo?", opt: ["6", "8", "12", "16"], cor: 2 },
            { id: "MAT-GEO-033", cat: "Matemática", sub: "Geometria", txt: "Planificação de um cilindro gera:", opt: ["2 Círculos e 1 Retângulo", "1 Círculo e 1 Triângulo", "6 Quadrados", "1 Círculo e 1 Setor"], cor: 0 },
            { id: "MAT-GEO-034", cat: "Matemática", sub: "Geometria", txt: "O ponto de encontro das medianas de um triângulo é o:", opt: ["Baricentro", "Ortocentro", "Incentro", "Circuncentro"], cor: 0 },
            { id: "MAT-GEO-035", cat: "Matemática", sub: "Geometria", txt: "A reta que toca a circunferência em um único ponto é:", opt: ["Secante", "Tangente", "Externa", "Diâmetro"], cor: 1 },
            { id: "MAT-GEO-036", cat: "Matemática", sub: "Geometria", txt: "Qual polígono não possui diagonais?", opt: ["Quadrado", "Pentágono", "Triângulo", "Hexágono"], cor: 2 },
            { id: "MAT-GEO-037", cat: "Matemática", sub: "Geometria", txt: "Um ângulo de 90° graus também é chamado de:", opt: ["Ângulo Raso", "Ângulo Reto", "Ângulo Agudo", "Ângulo Obtuso"], cor: 1 },
            { id: "MAT-GEO-038", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um pentágono é:", opt: ["180°", "360°", "540°", "720°"], cor: 2 },
            { id: "MAT-GEO-039", cat: "Matemática", sub: "Geometria", txt: "Qual é o valor do perímetro de um círculo de raio 1? (Use π=3,14)", opt: ["3,14", "6,28", "9,42", "12,56"], cor: 1 },
            { id: "MAT-GEO-040", cat: "Matemática", sub: "Geometria", txt: "Qual sólido é formado por 4 triângulos equiláteros?", opt: ["Cubo", "Tetraedro", "Octaedro", "Dodecaedro"], cor: 1 },
            { id: "MAT-GEO-041", cat: "Matemática", sub: "Geometria", txt: "A área de um losango de diagonais 10 e 6 é:", opt: ["60", "30", "16", "100"], cor: 1 },
            { id: "MAT-GEO-042", cat: "Matemática", sub: "Geometria", txt: "Quantos graus tem cada ângulo interno de um triângulo equilátero?", opt: ["45°", "60°", "90°", "30°"], cor: 1 },
            { id: "MAT-GEO-043", cat: "Matemática", sub: "Geometria", txt: "O volume de uma esfera de raio R é:", opt: ["4.π.R²", "4/3.π.R³", "π.R²", "2.π.R"], cor: 1 },
            { id: "MAT-GEO-044", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um hexágono é:", opt: ["360°", "540°", "720°", "900°"], cor: 2 },
            { id: "MAT-GEO-045", cat: "Matemática", sub: "Geometria", txt: "Se o diâmetro é 12cm, o raio mede:", opt: ["24cm", "12cm", "6cm", "3cm"], cor: 2 },
            { id: "MAT-GEO-046", cat: "Matemática", sub: "Geometria", txt: "Qual destes não é um quadrilátero?", opt: ["Trapézio", "Losango", "Pentágono", "Retângulo"], cor: 2 },
            { id: "MAT-GEO-047", cat: "Matemática", sub: "Geometria", txt: "A geratriz, altura e raio formam triângulo retângulo em qual sólido?", opt: ["Cubo", "Esfera", "Cone", "Prisma"], cor: 2 },
            { id: "MAT-GEO-048", cat: "Matemática", sub: "Geometria", txt: "Um ângulo de 45° é a bissetriz de um ângulo de:", opt: ["30°", "60°", "90°", "180°"], cor: 2 },
            { id: "MAT-GEO-049", cat: "Matemática", sub: "Geometria", txt: "Seno de 30° vale:", opt: ["1/2", "√3/2", "√2/2", "1"], cor: 0 },
            { id: "MAT-GEO-050", cat: "Matemática", sub: "Geometria", txt: "Tangente é a razão entre:", opt: ["Seno e Cosseno", "Cosseno e Seno", "Hipotenusa e Cateto", "Cateto e Hipotenusa"], cor: 0 },
            { id: "MAT-GEO-051", cat: "Matemática", sub: "Geometria", txt: "Num triângulo retângulo, cateto oposto sobre hipotenusa é:", opt: ["Cosseno", "Seno", "Tangente", "Secante"], cor: 1 },
            { id: "MAT-GEO-052", cat: "Matemática", sub: "Geometria", txt: "A área total de um cubo de aresta 2 é:", opt: ["4", "8", "16", "24"], cor: 3 },
            { id: "MAT-GEO-053", cat: "Matemática", sub: "Geometria", txt: "Duas retas que nunca se cruzam são:", opt: ["Perpendiculares", "Concorrentes", "Paralelas", "Coincidentes"], cor: 2 },
            { id: "MAT-GEO-054", cat: "Matemática", sub: "Geometria", txt: "O Teorema de Pitágoras é:", opt: ["a² = b² + c²", "a = b + c", "a² = b + c", "a = b² + c²"], cor: 0 },
            { id: "MAT-GEO-055", cat: "Matemática", sub: "Geometria", txt: "Qual o complemento de um ângulo de 30°?", opt: ["60°", "90°", "150°", "180°"], cor: 0 },
            { id: "MAT-GEO-056", cat: "Matemática", sub: "Geometria", txt: "Qual o suplemento de um ângulo de 100°?", opt: ["10°", "80°", "90°", "260°"], cor: 1 },
            { id: "MAT-GEO-057", cat: "Matemática", sub: "Geometria", txt: "Um polígono regular tem:", opt: ["Lados iguais e ângulos diferentes", "Lados diferentes", "Lados e ângulos congruentes", "Nenhuma das anteriores"], cor: 2 },
            { id: "MAT-GEO-058", cat: "Matemática", sub: "Geometria", txt: "A distância entre dois pontos A(0,0) e B(3,4) é:", opt: ["3", "4", "5", "7"], cor: 2 },
            { id: "MAT-GEO-059", cat: "Matemática", sub: "Geometria", txt: "Área de um triângulo equilátero de lado L:", opt: ["L²", "(L²√3)/4", "L.h", "3L"], cor: 1 },
            { id: "MAT-GEO-060", cat: "Matemática", sub: "Geometria", txt: "O vértice de um cone fica oposto à:", opt: ["Altura", "Geratriz", "Base", "Lateral"], cor: 2 },
            { id: "MAT-GEO-061", cat: "Matemática", sub: "Geometria", txt: "A diagonal de um quadrado de lado L é:", opt: ["L√2", "L√3", "L/2", "2L"], cor: 0 },
            { id: "MAT-GEO-062", cat: "Matemática", sub: "Geometria", txt: "A diagonal de um cubo de aresta a é:", opt: ["a√2", "a√3", "a/2", "3a"], cor: 1 },
            { id: "MAT-GEO-063", cat: "Matemática", sub: "Geometria", txt: "Quantas faces tem um tetraedro?", opt: ["4", "6", "8", "12"], cor: 0 },
            { id: "MAT-GEO-064", cat: "Matemática", sub: "Geometria", txt: "O apótema é uma linha que vai do centro até:", opt: ["O vértice", "O meio do lado", "Fora da figura", "A diagonal"], cor: 1 },
            { id: "MAT-GEO-065", cat: "Matemática", sub: "Geometria", txt: "Se o perímetro de um triângulo equilátero é 30, o lado é:", opt: ["5", "10", "15", "30"], cor: 1 },
            { id: "MAT-GEO-066", cat: "Matemática", sub: "Geometria", txt: "A área de um círculo de diâmetro 20 é (use π no resultado):", opt: ["10π", "20π", "100π", "400π"], cor: 2 },
            { id: "MAT-GEO-067", cat: "Matemática", sub: "Geometria", txt: "Qual sólido tem duas bases circulares paralelas?", opt: ["Cone", "Cilindro", "Esfera", "Tronco"], cor: 1 },
            { id: "MAT-GEO-068", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um triângulo retângulo é:", opt: ["90°", "180°", "270°", "360°"], cor: 1 },
            { id: "MAT-GEO-069", cat: "Matemática", sub: "Geometria", txt: "Um polígono convexo de 4 lados é um:", opt: ["Triângulo", "Quadrilátero", "Pentágono", "Círculo"], cor: 1 },
            { id: "MAT-GEO-070", cat: "Matemática", sub: "Geometria", txt: "A altura de um triângulo equilátero de lado L é:", opt: ["L/2", "L√3/2", "L√2", "L"], cor: 1 },
            { id: "MAT-GEO-071", cat: "Matemática", sub: "Geometria", txt: "Se dobrarmos o raio de um círculo, a área:", opt: ["Dobra", "Quadruplica", "Triplica", "Fica igual"], cor: 1 },
            { id: "MAT-GEO-072", cat: "Matemática", sub: "Geometria", txt: "Volume de um prisma é:", opt: ["Área da Base x Altura", "Área da Base + Altura", "Lado³", "π.r²"], cor: 0 },
            { id: "MAT-GEO-073", cat: "Matemática", sub: "Geometria", txt: "Dois ângulos opostos pelo vértice (O.P.V.) são:", opt: ["Congruentes (Iguais)", "Suplementares", "Complementares", "Diferentes"], cor: 0 },
            { id: "MAT-GEO-074", cat: "Matemática", sub: "Geometria", txt: "O triângulo 3, 4 e 5 é famoso por ser:", opt: ["Equilátero", "Pitágorico (Retângulo)", "Obtusângulo", "Inexistente"], cor: 1 },
            { id: "MAT-GEO-075", cat: "Matemática", sub: "Geometria", txt: "A intersecção das três alturas de um triângulo é o:", opt: ["Baricentro", "Incentro", "Ortocentro", "Circuncentro"], cor: 2 },
            { id: "MAT-GEO-076", cat: "Matemática", sub: "Geometria", txt: "Qual a área de um quadrado cuja diagonal é 10?", opt: ["50", "100", "25", "10"], cor: 0 },
            { id: "MAT-GEO-077", cat: "Matemática", sub: "Geometria", txt: "Um polígono de 12 lados chama-se:", opt: ["Decágono", "Dodecágono", "Icoságono", "Undecágono"], cor: 1 },
            { id: "MAT-GEO-078", cat: "Matemática", sub: "Geometria", txt: "Se a área da base do cone é 10 e altura 3, o volume é:", opt: ["30", "10", "15", "90"], cor: 1 },
            { id: "MAT-GEO-079", cat: "Matemática", sub: "Geometria", txt: "O ângulo inscrito numa semicircunferência mede:", opt: ["45°", "60°", "90°", "180°"], cor: 2 },
            { id: "MAT-GEO-080", cat: "Matemática", sub: "Geometria", txt: "Quantas faces laterais tem uma pirâmide quadrangular?", opt: ["3", "4", "5", "6"], cor: 1 },
            { id: "MAT-GEO-081", cat: "Matemática", sub: "Geometria", txt: "A área de um setor circular de 90° num círculo de raio 2 é:", opt: ["π", "2π", "4π", "π/2"], cor: 0 },
            { id: "MAT-GEO-082", cat: "Matemática", sub: "Geometria", txt: "Quantas faces tem um tetraedro?", opt: ["3", "4", "5", "6"], cor: 1 },
            { id: "MAT-GEO-083", cat: "Matemática", sub: "Geometria", txt: "O perímetro de um triângulo de lados 3, 4 e 5 é:", opt: ["10", "12", "15", "7"], cor: 1 },
            { id: "MAT-GEO-084", cat: "Matemática", sub: "Geometria", txt: "Dois ângulos colaterais internos são:", opt: ["Congruentes", "Suplementares (soma 180°)", "Complementares", "Relementares"], cor: 1 },
            { id: "MAT-GEO-085", cat: "Matemática", sub: "Geometria", txt: "Se a área de um quadrado é 100, o lado mede:", opt: ["50", "25", "20", "10"], cor: 3 },
            { id: "MAT-GEO-086", cat: "Matemática", sub: "Geometria", txt: "A soma dos ângulos internos de um decágono é:", opt: ["1440°", "1800°", "1080°", "360°"], cor: 0 },
            { id: "MAT-GEO-087", cat: "Matemática", sub: "Geometria", txt: "Num triângulo equilátero, o baricentro, ortocentro e incentro são:", opt: ["Pontos distintos", "O mesmo ponto", "Colineares", "Inexistentes"], cor: 1 },
            { id: "MAT-GEO-088", cat: "Matemática", sub: "Geometria", txt: "O volume de um cone é ___ do volume de um cilindro de mesma base e altura.", opt: ["1/2", "1/3", "2/3", "Igual"], cor: 1 },
            { id: "MAT-GEO-089", cat: "Matemática", sub: "Geometria", txt: "A distância do centro à corda, se a corda é o diâmetro, é:", opt: ["O raio", "Zero", "O diâmetro", "Infinita"], cor: 1 },
            { id: "MAT-GEO-090", cat: "Matemática", sub: "Geometria", txt: "Qual a área lateral de um cubo de aresta 3?", opt: ["9", "27", "36", "54"], cor: 2 },
            { id: "MAT-GEO-091", cat: "Matemática", sub: "Geometria", txt: "O ponto (3, 0) está localizado no:", opt: ["Eixo X (Abscissas)", "Eixo Y (Ordenadas)", "Origem", "1º Quadrante"], cor: 0 },
            { id: "MAT-GEO-092", cat: "Matemática", sub: "Geometria", txt: "Retas que formam 90° entre si são:", opt: ["Paralelas", "Perpendiculares", "Coincidentes", "Reversas"], cor: 1 },
            { id: "MAT-GEO-093", cat: "Matemática", sub: "Geometria", txt: "Um polígono convexo de 3 lados é um:", opt: ["Quadrilátero", "Triângulo", "Círculo", "Trapézio"], cor: 1 },
            { id: "MAT-GEO-094", cat: "Matemática", sub: "Geometria", txt: "A diagonal de um paralelepípedo de lados a, b, c é:", opt: ["a+b+c", "√(a²+b²+c²)", "abc", "a²+b²+c²"], cor: 1 },
            { id: "MAT-GEO-095", cat: "Matemática", sub: "Geometria", txt: "O apótema de um hexágono regular de lado L é:", opt: ["L", "L√3/2", "L/2", "L√2"], cor: 1 },
            { id: "MAT-GEO-096", cat: "Matemática", sub: "Geometria", txt: "Dois círculos com mesmo centro são:", opt: ["Tangentes", "Concêntricos", "Secantes", "Externos"], cor: 1 },
            { id: "MAT-GEO-097", cat: "Matemática", sub: "Geometria", txt: "A área de um trapézio de bases 10 e 5 e altura 4 é:", opt: ["60", "30", "15", "20"], cor: 1 },
            { id: "MAT-GEO-098", cat: "Matemática", sub: "Geometria", txt: "Um icosaedro tem quantas arestas?", opt: ["12", "20", "30", "10"], cor: 2 },
            { id: "MAT-GEO-099", cat: "Matemática", sub: "Geometria", txt: "Se o volume do cubo é 8, a aresta é:", opt: ["2", "4", "64", "2,8"], cor: 0 },
            { id: "MAT-GEO-100", cat: "Matemática", sub: "Geometria", txt: "Qual a condição de existência de um triângulo (Lado 'a')?", opt: ["a = b + c", "a > b + c", "a < b + c", "a = b - c"], cor: 2 },
           ];
